
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.InteropServices.JavaScript", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Invalid argument: {0} can not be null.
        /// </summary>
        internal static string ArgumentCannotBeNull
        {
            get
            {
                return "Invalid argument: {0} can not be null.";
            }
        }


        internal static string FormatArgumentCannotBeNull(object arg1)
        {
            return string.Format("Invalid argument: {0} can not be null.", arg1);
        }


        /// <summary>
        /// Invalid argument: {0} can not be null and must have a length.
        /// </summary>
        internal static string ArgumentCannotBeNullWithLength
        {
            get
            {
                return "Invalid argument: {0} can not be null and must have a length.";
            }
        }


        internal static string FormatArgumentCannotBeNullWithLength(object arg1)
        {
            return string.Format("Invalid argument: {0} can not be null and must have a length.", arg1);
        }


        /// <summary>
        /// System.Runtime.InteropServices.JavaScript is not supported on this platform.
        /// </summary>
        internal static string SystemRuntimeInteropServicesJavaScript_PlatformNotSupported
        {
            get
            {
                return "System.Runtime.InteropServices.JavaScript is not supported on this platform.";
            }
        }



        /// <summary>
        /// TypedArray is not of correct type.
        /// </summary>
        internal static string TypedArrayNotCorrectType
        {
            get
            {
                return "TypedArray is not of correct type.";
            }
        }



        /// <summary>
        /// Unable to cast null to type {0}.
        /// </summary>
        internal static string UnableCastNullToType
        {
            get
            {
                return "Unable to cast null to type {0}.";
            }
        }


        internal static string FormatUnableCastNullToType(object arg1)
        {
            return string.Format("Unable to cast null to type {0}.", arg1);
        }


        /// <summary>
        /// Unable to cast object of type {0} to type {1}.
        /// </summary>
        internal static string UnableCastObjectToType
        {
            get
            {
                return "Unable to cast object of type {0} to type {1}.";
            }
        }


        internal static string FormatUnableCastObjectToType(object arg1, object arg2)
        {
            return string.Format("Unable to cast object of type {0} to type {1}.", arg1, arg2);
        }


        /// <summary>
        /// Managed entrypoint handle is not set.
        /// </summary>
        internal static string MissingManagedEntrypointHandle
        {
            get
            {
                return "Managed entrypoint handle is not set.";
            }
        }



        /// <summary>
        /// Cannot resolve managed entrypoint handle.
        /// </summary>
        internal static string CannotResolveManagedEntrypointHandle
        {
            get
            {
                return "Cannot resolve managed entrypoint handle.";
            }
        }



        /// <summary>
        /// Return type '{0}' from main method in not supported.
        /// </summary>
        internal static string ReturnTypeNotSupportedForMain
        {
            get
            {
                return "Return type '{0}' from main method in not supported.";
            }
        }


        internal static string FormatReturnTypeNotSupportedForMain(object arg1)
        {
            return string.Format("Return type '{0}' from main method in not supported.", arg1);
        }


        /// <summary>
        /// ToManagedCallback is null.
        /// </summary>
        internal static string NullToManagedCallback
        {
            get
            {
                return "ToManagedCallback is null.";
            }
        }



        /// <summary>
        /// PromiseHolder is null.
        /// </summary>
        internal static string NullPromiseHolder
        {
            get
            {
                return "PromiseHolder is null.";
            }
        }



        /// <summary>
        /// Empty profile data.
        /// </summary>
        internal static string EmptyProfileData
        {
            get
            {
                return "Empty profile data.";
            }
        }



        /// <summary>
        /// Error setting {0} on (js-obj js '{1}'): {2}.
        /// </summary>
        internal static string ErrorLegacySettingProperty
        {
            get
            {
                return "Error setting {0} on (js-obj js '{1}'): {2}.";
            }
        }


        internal static string FormatErrorLegacySettingProperty(object arg1, object arg2, object arg3)
        {
            return string.Format("Error setting {0} on (js-obj js '{1}'): {2}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Error resolving property {0} from globalThis.
        /// </summary>
        internal static string ErrorResolvingFromGlobalThis
        {
            get
            {
                return "Error resolving property {0} from globalThis.";
            }
        }


        internal static string FormatErrorResolvingFromGlobalThis(object arg1)
        {
            return string.Format("Error resolving property {0} from globalThis.", arg1);
        }


        /// <summary>
        /// Failed to marshal exception.
        /// </summary>
        internal static string FailedToMarshalException
        {
            get
            {
                return "Failed to marshal exception.";
            }
        }



        /// <summary>
        /// Failed to marshal Promise callback.
        /// </summary>
        internal static string FailedToMarshalPromiseHolder
        {
            get
            {
                return "Failed to marshal Promise callback.";
            }
        }



        /// <summary>
        /// Invalid InFlightCounter for JSObject {0}, expected: {1}, actual: {2}.
        /// </summary>
        internal static string InvalidInFlightCounter
        {
            get
            {
                return "Invalid InFlightCounter for JSObject {0}, expected: {1}, actual: {2}.";
            }
        }


        internal static string FormatInvalidInFlightCounter(object arg1, object arg2, object arg3)
        {
            return string.Format("Invalid InFlightCounter for JSObject {0}, expected: {1}, actual: {2}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// ToJS for {0} is not implemented.
        /// </summary>
        internal static string ToJSNotImplemented
        {
            get
            {
                return "ToJS for {0} is not implemented.";
            }
        }


        internal static string FormatToJSNotImplemented(object arg1)
        {
            return string.Format("ToJS for {0} is not implemented.", arg1);
        }


        /// <summary>
        /// ToManaged for {0} is not implemented.
        /// </summary>
        internal static string ToManagedNotImplemented
        {
            get
            {
                return "ToManaged for {0} is not implemented.";
            }
        }


        internal static string FormatToManagedNotImplemented(object arg1)
        {
            return string.Format("ToManaged for {0} is not implemented.", arg1);
        }


        /// <summary>
        /// Unable to resolve the handle as an Exception.
        /// </summary>
        internal static string UnableToResolveHandleAsException
        {
            get
            {
                return "Unable to resolve the handle as an Exception.";
            }
        }



        /// <summary>
        /// Unsupported array type {0}. Only single-dimensional arrays with a zero lower bound can be marshaled to JS.
        /// </summary>
        internal static string UnsupportedArrayType
        {
            get
            {
                return "Unsupported array type {0}. Only single-dimensional arrays with a zero lower bound can be marshaled to JS.";
            }
        }


        internal static string FormatUnsupportedArrayType(object arg1)
        {
            return string.Format("Unsupported array type {0}. Only single-dimensional arrays with a zero lower bound can be marshaled to JS.", arg1);
        }


        /// <summary>
        /// Unsupported element type {0}.
        /// </summary>
        internal static string UnsupportedElementType
        {
            get
            {
                return "Unsupported element type {0}.";
            }
        }


        internal static string FormatUnsupportedElementType(object arg1)
        {
            return string.Format("Unsupported element type {0}.", arg1);
        }


        /// <summary>
        /// Unsupported enum type {0}.
        /// </summary>
        internal static string UnsupportedEnumType
        {
            get
            {
                return "Unsupported enum type {0}.";
            }
        }


        internal static string FormatUnsupportedEnumType(object arg1)
        {
            return string.Format("Unsupported enum type {0}.", arg1);
        }


        /// <summary>
        /// Unsupported marshal type {0}.
        /// </summary>
        internal static string UnsupportedLegacyMarshlerType
        {
            get
            {
                return "Unsupported marshal type {0}.";
            }
        }


        internal static string FormatUnsupportedLegacyMarshlerType(object arg1)
        {
            return string.Format("Unsupported marshal type {0}.", arg1);
        }


        /// <summary>
        /// Unsupported nullable type {0}.
        /// </summary>
        internal static string UnsupportedNullableType
        {
            get
            {
                return "Unsupported nullable type {0}.";
            }
        }


        internal static string FormatUnsupportedNullableType(object arg1)
        {
            return string.Format("Unsupported nullable type {0}.", arg1);
        }


        /// <summary>
        /// Unsupported task result type {0}.
        /// </summary>
        internal static string UnsupportedTaskResultType
        {
            get
            {
                return "Unsupported task result type {0}.";
            }
        }


        internal static string FormatUnsupportedTaskResultType(object arg1)
        {
            return string.Format("Unsupported task result type {0}.", arg1);
        }


        /// <summary>
        /// Constructor on type 'System.Uri' not found. Please consider to protect it's constructor from trimming.
        /// </summary>
        internal static string UriConstructorMissing
        {
            get
            {
                return "Constructor on type 'System.Uri' not found. Please consider to protect it's constructor from trimming.";
            }
        }



        /// <summary>
        /// The type System.Uri could not be found. Please consider to protect the class and it's constructor from trimming.
        /// </summary>
        internal static string UriTypeMissing
        {
            get
            {
                return "The type System.Uri could not be found. Please consider to protect the class and it's constructor from trimming.";
            }
        }



        /// <summary>
        /// Overflow: value {0} is out of {1} {2} range.
        /// </summary>
        internal static string ValueOutOf52BitRange
        {
            get
            {
                return "Overflow: value {0} is out of {1} {2} range.";
            }
        }


        internal static string FormatValueOutOf52BitRange(object arg1, object arg2, object arg3)
        {
            return string.Format("Overflow: value {0} is out of {1} {2} range.", arg1, arg2, arg3);
        }
    }
}
