
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Private.Xml.Linq", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// An attribute cannot be added to content.
        /// </summary>
        internal static string Argument_AddAttribute
        {
            get
            {
                return "An attribute cannot be added to content.";
            }
        }



        /// <summary>
        /// A node of type {0} cannot be added to content.
        /// </summary>
        internal static string Argument_AddNode
        {
            get
            {
                return "A node of type {0} cannot be added to content.";
            }
        }


        internal static string FormatArgument_AddNode(object arg1)
        {
            return string.Format("A node of type {0} cannot be added to content.", arg1);
        }


        /// <summary>
        /// Non-whitespace characters cannot be added to content.
        /// </summary>
        internal static string Argument_AddNonWhitespace
        {
            get
            {
                return "Non-whitespace characters cannot be added to content.";
            }
        }



        /// <summary>
        /// The argument cannot be converted to a string.
        /// </summary>
        internal static string Argument_ConvertToString
        {
            get
            {
                return "The argument cannot be converted to a string.";
            }
        }



        /// <summary>
        /// '{0}' is an invalid expanded name.
        /// </summary>
        internal static string Argument_InvalidExpandedName
        {
            get
            {
                return "'{0}' is an invalid expanded name.";
            }
        }


        internal static string FormatArgument_InvalidExpandedName(object arg1)
        {
            return string.Format("'{0}' is an invalid expanded name.", arg1);
        }


        /// <summary>
        /// '{0}' is an invalid name for a processing instruction.
        /// </summary>
        internal static string Argument_InvalidPIName
        {
            get
            {
                return "'{0}' is an invalid name for a processing instruction.";
            }
        }


        internal static string FormatArgument_InvalidPIName(object arg1)
        {
            return string.Format("'{0}' is an invalid name for a processing instruction.", arg1);
        }


        /// <summary>
        /// The argument must be derived from {0}.
        /// </summary>
        internal static string Argument_MustBeDerivedFrom
        {
            get
            {
                return "The argument must be derived from {0}.";
            }
        }


        internal static string FormatArgument_MustBeDerivedFrom(object arg1)
        {
            return string.Format("The argument must be derived from {0}.", arg1);
        }


        /// <summary>
        /// The prefix '{0}' cannot be bound to the empty namespace name.
        /// </summary>
        internal static string Argument_NamespaceDeclarationPrefixed
        {
            get
            {
                return "The prefix '{0}' cannot be bound to the empty namespace name.";
            }
        }


        internal static string FormatArgument_NamespaceDeclarationPrefixed(object arg1)
        {
            return string.Format("The prefix '{0}' cannot be bound to the empty namespace name.", arg1);
        }


        /// <summary>
        /// The prefix 'xml' is bound to the namespace name 'http://www.w3.org/XML/1998/namespace'. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.
        /// </summary>
        internal static string Argument_NamespaceDeclarationXml
        {
            get
            {
                return "The prefix 'xml' is bound to the namespace name 'http://www.w3.org/XML/1998/namespace'. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.";
            }
        }



        /// <summary>
        /// The prefix 'xmlns' is bound to the namespace name 'http://www.w3.org/2000/xmlns/'. It must not be declared. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.
        /// </summary>
        internal static string Argument_NamespaceDeclarationXmlns
        {
            get
            {
                return "The prefix 'xmlns' is bound to the namespace name 'http://www.w3.org/2000/xmlns/'. It must not be declared. Other prefixes must not be bound to this namespace name, and it must not be declared as the default namespace.";
            }
        }



        /// <summary>
        /// An XObject cannot be used as a value.
        /// </summary>
        internal static string Argument_XObjectValue
        {
            get
            {
                return "An XObject cannot be used as a value.";
            }
        }



        /// <summary>
        /// This instance cannot be deserialized.
        /// </summary>
        internal static string InvalidOperation_DeserializeInstance
        {
            get
            {
                return "This instance cannot be deserialized.";
            }
        }



        /// <summary>
        /// This operation would create an incorrectly structured document.
        /// </summary>
        internal static string InvalidOperation_DocumentStructure
        {
            get
            {
                return "This operation would create an incorrectly structured document.";
            }
        }



        /// <summary>
        /// Duplicate attribute.
        /// </summary>
        internal static string InvalidOperation_DuplicateAttribute
        {
            get
            {
                return "Duplicate attribute.";
            }
        }



        /// <summary>
        /// The XmlReader state should be EndOfFile after this operation.
        /// </summary>
        internal static string InvalidOperation_ExpectedEndOfFile
        {
            get
            {
                return "The XmlReader state should be EndOfFile after this operation.";
            }
        }



        /// <summary>
        /// The XmlReader state should be Interactive.
        /// </summary>
        internal static string InvalidOperation_ExpectedInteractive
        {
            get
            {
                return "The XmlReader state should be Interactive.";
            }
        }



        /// <summary>
        /// The XmlReader must be on a node of type {0} instead of a node of type {1}.
        /// </summary>
        internal static string InvalidOperation_ExpectedNodeType
        {
            get
            {
                return "The XmlReader must be on a node of type {0} instead of a node of type {1}.";
            }
        }


        internal static string FormatInvalidOperation_ExpectedNodeType(object arg1, object arg2)
        {
            return string.Format("The XmlReader must be on a node of type {0} instead of a node of type {1}.", arg1, arg2);
        }


        /// <summary>
        /// This operation was corrupted by external code.
        /// </summary>
        internal static string InvalidOperation_ExternalCode
        {
            get
            {
                return "This operation was corrupted by external code.";
            }
        }



        /// <summary>
        /// A common ancestor is missing.
        /// </summary>
        internal static string InvalidOperation_MissingAncestor
        {
            get
            {
                return "A common ancestor is missing.";
            }
        }



        /// <summary>
        /// The parent is missing.
        /// </summary>
        internal static string InvalidOperation_MissingParent
        {
            get
            {
                return "The parent is missing.";
            }
        }



        /// <summary>
        /// The root element is missing.
        /// </summary>
        internal static string InvalidOperation_MissingRoot
        {
            get
            {
                return "The root element is missing.";
            }
        }



        /// <summary>
        /// The XmlReader should not be on a node of type {0}.
        /// </summary>
        internal static string InvalidOperation_UnexpectedNodeType
        {
            get
            {
                return "The XmlReader should not be on a node of type {0}.";
            }
        }


        internal static string FormatInvalidOperation_UnexpectedNodeType(object arg1)
        {
            return string.Format("The XmlReader should not be on a node of type {0}.", arg1);
        }


        /// <summary>
        /// The XmlReader cannot resolve entity references.
        /// </summary>
        internal static string InvalidOperation_UnresolvedEntityReference
        {
            get
            {
                return "The XmlReader cannot resolve entity references.";
            }
        }



        /// <summary>
        /// An attribute cannot be written after content.
        /// </summary>
        internal static string InvalidOperation_WriteAttribute
        {
            get
            {
                return "An attribute cannot be written after content.";
            }
        }



        /// <summary>
        /// This XmlWriter does not support base64 encoded data.
        /// </summary>
        internal static string NotSupported_WriteBase64
        {
            get
            {
                return "This XmlWriter does not support base64 encoded data.";
            }
        }



        /// <summary>
        /// This XmlWriter does not support entity references.
        /// </summary>
        internal static string NotSupported_WriteEntityRef
        {
            get
            {
                return "This XmlWriter does not support entity references.";
            }
        }



        /// <summary>
        /// This XPathNavigator cannot be created on a node of type {0}.
        /// </summary>
        internal static string Argument_CreateNavigator
        {
            get
            {
                return "This XPathNavigator cannot be created on a node of type {0}.";
            }
        }


        internal static string FormatArgument_CreateNavigator(object arg1)
        {
            return string.Format("This XPathNavigator cannot be created on a node of type {0}.", arg1);
        }


        /// <summary>
        /// This operation is not valid on a node of type {0}.
        /// </summary>
        internal static string InvalidOperation_BadNodeType
        {
            get
            {
                return "This operation is not valid on a node of type {0}.";
            }
        }


        internal static string FormatInvalidOperation_BadNodeType(object arg1)
        {
            return string.Format("This operation is not valid on a node of type {0}.", arg1);
        }


        /// <summary>
        /// The XPath expression evaluated to unexpected type {0}.
        /// </summary>
        internal static string InvalidOperation_UnexpectedEvaluation
        {
            get
            {
                return "The XPath expression evaluated to unexpected type {0}.";
            }
        }


        internal static string FormatInvalidOperation_UnexpectedEvaluation(object arg1)
        {
            return string.Format("The XPath expression evaluated to unexpected type {0}.", arg1);
        }


        /// <summary>
        /// This XPathNavigator does not support IDs.
        /// </summary>
        internal static string NotSupported_MoveToId
        {
            get
            {
                return "This XPathNavigator does not support IDs.";
            }
        }

    }
}
