
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ComponentModel.Primitives", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The value of argument '{0}' ({1}) is invalid for Enum type '{2}'.
        /// </summary>
        internal static string InvalidEnumArgument
        {
            get
            {
                return "The value of argument '{0}' ({1}) is invalid for Enum type '{2}'.";
            }
        }


        internal static string FormatInvalidEnumArgument(object arg1, object arg2, object arg3)
        {
            return string.Format("The value of argument '{0}' ({1}) is invalid for Enum type '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Action
        /// </summary>
        internal static string PropertyCategoryAction
        {
            get
            {
                return "Action";
            }
        }



        /// <summary>
        /// Appearance
        /// </summary>
        internal static string PropertyCategoryAppearance
        {
            get
            {
                return "Appearance";
            }
        }



        /// <summary>
        /// Asynchronous
        /// </summary>
        internal static string PropertyCategoryAsynchronous
        {
            get
            {
                return "Asynchronous";
            }
        }



        /// <summary>
        /// Behavior
        /// </summary>
        internal static string PropertyCategoryBehavior
        {
            get
            {
                return "Behavior";
            }
        }



        /// <summary>
        /// Configurations
        /// </summary>
        internal static string PropertyCategoryConfig
        {
            get
            {
                return "Configurations";
            }
        }



        /// <summary>
        /// Data
        /// </summary>
        internal static string PropertyCategoryData
        {
            get
            {
                return "Data";
            }
        }



        /// <summary>
        /// DDE
        /// </summary>
        internal static string PropertyCategoryDDE
        {
            get
            {
                return "DDE";
            }
        }



        /// <summary>
        /// Misc
        /// </summary>
        internal static string PropertyCategoryDefault
        {
            get
            {
                return "Misc";
            }
        }



        /// <summary>
        /// Design
        /// </summary>
        internal static string PropertyCategoryDesign
        {
            get
            {
                return "Design";
            }
        }



        /// <summary>
        /// Drag Drop
        /// </summary>
        internal static string PropertyCategoryDragDrop
        {
            get
            {
                return "Drag Drop";
            }
        }



        /// <summary>
        /// Focus
        /// </summary>
        internal static string PropertyCategoryFocus
        {
            get
            {
                return "Focus";
            }
        }



        /// <summary>
        /// Font
        /// </summary>
        internal static string PropertyCategoryFont
        {
            get
            {
                return "Font";
            }
        }



        /// <summary>
        /// Format
        /// </summary>
        internal static string PropertyCategoryFormat
        {
            get
            {
                return "Format";
            }
        }



        /// <summary>
        /// Key
        /// </summary>
        internal static string PropertyCategoryKey
        {
            get
            {
                return "Key";
            }
        }



        /// <summary>
        /// Layout
        /// </summary>
        internal static string PropertyCategoryLayout
        {
            get
            {
                return "Layout";
            }
        }



        /// <summary>
        /// List
        /// </summary>
        internal static string PropertyCategoryList
        {
            get
            {
                return "List";
            }
        }



        /// <summary>
        /// Mouse
        /// </summary>
        internal static string PropertyCategoryMouse
        {
            get
            {
                return "Mouse";
            }
        }



        /// <summary>
        /// Position
        /// </summary>
        internal static string PropertyCategoryPosition
        {
            get
            {
                return "Position";
            }
        }



        /// <summary>
        /// Scale
        /// </summary>
        internal static string PropertyCategoryScale
        {
            get
            {
                return "Scale";
            }
        }



        /// <summary>
        /// Text
        /// </summary>
        internal static string PropertyCategoryText
        {
            get
            {
                return "Text";
            }
        }



        /// <summary>
        /// Window Style
        /// </summary>
        internal static string PropertyCategoryWindowStyle
        {
            get
            {
                return "Window Style";
            }
        }

    }
}
