
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections.NonGeneric", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Item has already been added. Key in dictionary: '{0}'  Key being added: '{1}'
        /// </summary>
        internal static string Argument_AddingDuplicate_OldAndNewKeys
        {
            get
            {
                return "Item has already been added. Key in dictionary: '{0}'  Key being added: '{1}'";
            }
        }


        internal static string FormatArgument_AddingDuplicate_OldAndNewKeys(object arg1, object arg2)
        {
            return string.Format("Item has already been added. Key in dictionary: '{0}'  Key being added: '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Destination array is not long enough to copy all the items in the collection. Check array index and length.
        /// </summary>
        internal static string Arg_ArrayPlusOffTooSmall
        {
            get
            {
                return "Destination array is not long enough to copy all the items in the collection. Check array index and length.";
            }
        }



        /// <summary>
        /// Only single dimensional arrays are supported for the requested action.
        /// </summary>
        internal static string Arg_RankMultiDimNotSupported
        {
            get
            {
                return "Only single dimensional arrays are supported for the requested action.";
            }
        }



        /// <summary>
        /// Cannot remove the specified item because it was not found in the specified Collection.
        /// </summary>
        internal static string Arg_RemoveArgNotFound
        {
            get
            {
                return "Cannot remove the specified item because it was not found in the specified Collection.";
            }
        }



        /// <summary>
        /// Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
        /// </summary>
        internal static string Argument_InvalidOffLen
        {
            get
            {
                return "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.";
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLess
        {
            get
            {
                return "Index was out of range. Must be non-negative and less than the size of the collection.";
            }
        }



        /// <summary>
        /// Index was out of range. Must be non-negative and less than or equal to the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLessOrEqual
        {
            get
            {
                return "Index was out of range. Must be non-negative and less than or equal to the size of the collection.";
            }
        }



        /// <summary>
        /// capacity was less than the current size.
        /// </summary>
        internal static string ArgumentOutOfRange_SmallCapacity
        {
            get
            {
                return "capacity was less than the current size.";
            }
        }



        /// <summary>
        /// Queue empty.
        /// </summary>
        internal static string InvalidOperation_EmptyQueue
        {
            get
            {
                return "Queue empty.";
            }
        }



        /// <summary>
        /// Stack empty.
        /// </summary>
        internal static string InvalidOperation_EmptyStack
        {
            get
            {
                return "Stack empty.";
            }
        }



        /// <summary>
        /// Enumeration already finished.
        /// </summary>
        internal static string InvalidOperation_EnumEnded
        {
            get
            {
                return "Enumeration already finished.";
            }
        }



        /// <summary>
        /// Collection was modified after the enumerator was instantiated.
        /// </summary>
        internal static string InvalidOperation_EnumFailedVersion
        {
            get
            {
                return "Collection was modified after the enumerator was instantiated.";
            }
        }



        /// <summary>
        /// Enumeration has not started. Call MoveNext.
        /// </summary>
        internal static string InvalidOperation_EnumNotStarted
        {
            get
            {
                return "Enumeration has not started. Call MoveNext.";
            }
        }



        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string InvalidOperation_EnumOpCantHappen
        {
            get
            {
                return "Enumeration has either not started or has already finished.";
            }
        }



        /// <summary>
        /// Mutating a key collection derived from a dictionary is not allowed.
        /// </summary>
        internal static string NotSupported_KeyCollectionSet
        {
            get
            {
                return "Mutating a key collection derived from a dictionary is not allowed.";
            }
        }



        /// <summary>
        /// This operation is not supported on SortedList nested types because they require modifying the original SortedList.
        /// </summary>
        internal static string NotSupported_SortedListNestedWrite
        {
            get
            {
                return "This operation is not supported on SortedList nested types because they require modifying the original SortedList.";
            }
        }

    }
}
