<Project>
	<PropertyGroup>
		<NetCoreAppCurrent>net10.0-browser</NetCoreAppCurrent>
		<TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
		<!--TargetFramework>$(NetCoreAppCurrent)-browser</TargetFramework-->
		<!--TargetPlatformIdentifier>browser</TargetPlatformIdentifier-->
		<TargetsBrowser>true</TargetsBrowser>
		<OutputType>Library</OutputType>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<Version>1.0.35</Version>
		<Authors>Samson A.</Authors>
		<Company>SIT</Company>
		<IsPackable>true</IsPackable>
		<NugetAudit>false</NugetAudit>
		<!--PublishTrimmed>true</PublishTrimmed-->
		<!--ImplicitUsings>true</ImplicitUsings-->
		<Nullable>enable</Nullable>
		<RazorLangVersion>Latest</RazorLangVersion>
		<DefaultNugetVersion>7.0.1</DefaultNugetVersion>
		<DefineConstants>$(DefineConstants);$(CommandLineDefineConstants);NET;FEATURE_SERIALIZATION</DefineConstants>		
		
		<NoWarn>CS0824,CS0626,CS8500,CS3021</NoWarn>
		<OutputMode>SingleFile,Global,InlineConstants</OutputMode>
		
		<RuntimeFlavor>Mono</RuntimeFlavor>
		<Platform>wasm</Platform>
		<NetJsFolder>E:\Apps\NetJs\</NetJsFolder>
		<DotnetGitRoot>$(NetJsFolder)dotnet\</DotnetGitRoot>
		<DotnetRuntimeRoot>$(DotnetGitRoot)runtime\</DotnetRuntimeRoot>
		<RepoRoot>$(DotnetGitRoot)aspnetcore\</RepoRoot>

		<SharedSourceRoot>$(RepoRoot)src\Shared\</SharedSourceRoot>
		<ComponentsSharedSourceRoot>$(RepoRoot)src\Components\Shared\</ComponentsSharedSourceRoot>
		
		<CoreClrProjectRoot>$(DotnetRuntimeRoot)src\coreclr\</CoreClrProjectRoot>
		<CoreLibRoot>$(DotnetRuntimeRoot)src\libraries\System.Private.CoreLib\src\</CoreLibRoot>
		<CoreLibSharedDir>$(DotnetRuntimeRoot)src\libraries\System.Private.CoreLib\src\</CoreLibSharedDir>
		<LibrariesProjectRoot>$(DotnetRuntimeRoot)src\libraries\</LibrariesProjectRoot>
		<CommonPath>$(DotnetRuntimeRoot)src\libraries\Common\src\</CommonPath>
		<BclSourcesRoot>$(DotnetRuntimeRoot)src/mono/System.Private.CoreLib/src</BclSourcesRoot>
		<!--ILLinkDirectory>$(DotnetRuntimeRoot)src\mono\System.Private.CoreLib\src\ILLink\</ILLinkDirectory-->
		<PrivateCoreLibSharedProjectDirectory>$(DotnetRuntimeRoot)src\libraries\System.Private.CoreLib\src\</PrivateCoreLibSharedProjectDirectory>


		<NewLibrariesProjectRoot>E:\Apps\NetJs\libraries\</NewLibrariesProjectRoot>
		<DotnetJsRuntimeRoot>$(MsBuildThisFileDirectory)/dotnetJs.Runtime</DotnetJsRuntimeRoot>
		<CoreLibProject>$(NewLibrariesProjectRoot)System.Private.CoreLib\NetJs.System.Private.CoreLib.csproj</CoreLibProject>
		<UriProject>$(NewLibrariesProjectRoot)System.Private.Uri\NetJs.System.Private.Uri.csproj</UriProject>
		<LoggingGenerator>$(LibrariesProjectRoot)Microsoft.Extensions.Logging.Abstractions\gen\Microsoft.Extensions.Logging.Generators.Roslyn4.4.csproj</LoggingGenerator>	
		<RegexGenerator>$(LibrariesProjectRoot)System.Text.RegularExpressions\gen\System.Text.RegularExpressions.Generator.csproj</RegexGenerator>
		<OptionGenerator>$(LibrariesProjectRoot)Microsoft.Extensions.Options\gen\Microsoft.Extensions.Options.SourceGeneration.csproj</OptionGenerator>
		<JsonGenerator>$(LibrariesProjectRoot)System.Text.Json\gen\System.Text.Json.SourceGeneration.Roslyn4.4.csproj</JsonGenerator>
	</PropertyGroup>
	
	<PropertyGroup>
		<ExcludeMscorlibFacade>true</ExcludeMscorlibFacade>	
		<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>

		<RunAnalyzers>false</RunAnalyzers>
		<RunAnalyzersDuringLiveAnalisis>false</RunAnalyzersDuringLiveAnalisis>
		<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
		<SkipImportNuGetProps>false</SkipImportNuGetProps>
		<SkipImportNuGetBuildTargets>false</SkipImportNuGetBuildTargets>
		<NoStdLib>true</NoStdLib>
		<NoExplicitReferenceToStdLib>true</NoExplicitReferenceToStdLib>
		<NoCompilerStandardLib>true</NoCompilerStandardLib>
		<AddAdditionalExplicitAssemblyReferences>false</AddAdditionalExplicitAssemblyReferences>
		<AdditionalExplicitAssemblyReferences />
	
		<ZipPackageFolder>$(NetJsFolder)zpackages</ZipPackageFolder>
	
		<!--CoreBuildDependsOn Condition="'$(NoNetJs)' != 'true'">
			$(CoreBuildDependsOn);
			CoreCompile;
			NetJsBuild;
			PostBuildEvent
		</CoreBuildDependsOn-->
	</PropertyGroup>
	
	<ItemGroup>
		<!--<Compile Include="$(DotnetRuntimeRoot)src/libraries/Common/src/System/SR.cs" Link="Common/System/SR.cs" />-->
		<!--<Content Include="$(DotnetRuntimeRoot)src/libraries/System.Collections/src/Resources/Strings.resx">
			<GenerateSource>true</GenerateSource>
			<ClassName>System.SR</ClassName>
		</Content>-->
	</ItemGroup>

	<!--Target Name="CoreCompile"  Condition="'$(NoNetJs)' != 'true'"/-->

	<Target Name="NetJsBuild" 
		AfterTargets="CoreCompile" 
        Inputs="@(Compile)"
        Outputs="$(IntermediateOutputPath)NetJsBuild.timestamp"
		Condition="'$(NoNetJs)' != 'true' and '$(BuildingProject)' == 'true' and '$(DesignTimeBuild)' != 'true'">
		<Message Importance="high" Text="NetJs compiling..."/>
		<Exec Command="NetJs build --project &quot;$(ProjectPath)&quot; -c &quot;$(Configuration)&quot; -s" ConsoleToMsBuild="true" YieldDuringToolExecution="true" WorkingDirectory="$(ProjectDir)" ContinueOnError="ErrorAndStop" IgnoreExitCode="false"/>			
		<Touch Files="$(IntermediateOutputPath)NetJsBuild.timestamp" AlwaysCreate="true" />
		<ItemGroup>
			<FileWrites Include="$(IntermediateOutputPath)NetJsBuild.timestamp" />
		</ItemGroup>
		<Message Importance="high" Text="NetJs compilation success!" />

	</Target>

	<Target Name="CleanNetJsGeneratedFiles" BeforeTargets="Clean">
		<Message Importance="high" Text="Cleaning NetJs generated binaries and web assets..." />
		
		<RemoveDir Directories="$(TargetDir)wwwroot" Condition="Exists('$(TargetDir)wwwroot')" />

		<ItemGroup>
			<NetJsFilesToDelete Include="$(TargetDir)*.js.dll" />
			<NetJsFilesToDelete Include="$(TargetDir)*.js.pdb" />
			<NetJsFilesToDelete Include="$(TargetDir)*.js.xml" />
			<NetJsFilesToDelete Include="$(TargetDir)*.Symbols.yaml" />
			<NetJsFilesToDelete Include="$(TargetDir)*.package.zip" />
		</ItemGroup>

		<Delete Files="@(NetJsFilesToDelete)" Condition="'@(NetJsFilesToDelete)' != ''" />
	</Target>
</Project>
