
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reflection.Metadata", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Image is too small.
        /// </summary>
        internal static string ImageTooSmall
        {
            get
            {
                return "Image is too small.";
            }
        }



        /// <summary>
        /// Invalid COR header size.
        /// </summary>
        internal static string InvalidCorHeaderSize
        {
            get
            {
                return "Invalid COR header size.";
            }
        }



        /// <summary>
        /// Invalid handle.
        /// </summary>
        internal static string InvalidHandle
        {
            get
            {
                return "Invalid handle.";
            }
        }



        /// <summary>
        /// Unexpected handle kind: {0}.
        /// </summary>
        internal static string UnexpectedHandleKind
        {
            get
            {
                return "Unexpected handle kind: {0}.";
            }
        }


        internal static string FormatUnexpectedHandleKind(object arg1)
        {
            return string.Format("Unexpected handle kind: {0}.", arg1);
        }


        /// <summary>
        /// Unexpected op-code: {0}.
        /// </summary>
        internal static string UnexpectedOpCode
        {
            get
            {
                return "Unexpected op-code: {0}.";
            }
        }


        internal static string FormatUnexpectedOpCode(object arg1)
        {
            return string.Format("Unexpected op-code: {0}.", arg1);
        }


        /// <summary>
        /// Invalid local signature token: 0x{0:X8}
        /// </summary>
        internal static string InvalidLocalSignatureToken
        {
            get
            {
                return "Invalid local signature token: 0x{0:X8}";
            }
        }


        internal static string FormatInvalidLocalSignatureToken(object arg1)
        {
            return string.Format("Invalid local signature token: 0x{0:X8}", arg1);
        }


        /// <summary>
        /// Invalid metadata section span.
        /// </summary>
        internal static string InvalidMetadataSectionSpan
        {
            get
            {
                return "Invalid metadata section span.";
            }
        }



        /// <summary>
        /// Invalid method header: 0x{0:X2}
        /// </summary>
        internal static string InvalidMethodHeader1
        {
            get
            {
                return "Invalid method header: 0x{0:X2}";
            }
        }


        internal static string FormatInvalidMethodHeader1(object arg1)
        {
            return string.Format("Invalid method header: 0x{0:X2}", arg1);
        }


        /// <summary>
        /// Invalid method header: 0x{0:X2} 0x{1:X2}
        /// </summary>
        internal static string InvalidMethodHeader2
        {
            get
            {
                return "Invalid method header: 0x{0:X2} 0x{1:X2}";
            }
        }


        internal static string FormatInvalidMethodHeader2(object arg1, object arg2)
        {
            return string.Format("Invalid method header: 0x{0:X2} 0x{1:X2}", arg1, arg2);
        }


        /// <summary>
        /// Invalid PE signature.
        /// </summary>
        internal static string InvalidPESignature
        {
            get
            {
                return "Invalid PE signature.";
            }
        }



        /// <summary>
        /// Invalid SEH header: 0x{0:X2}
        /// </summary>
        internal static string InvalidSehHeader
        {
            get
            {
                return "Invalid SEH header: 0x{0:X2}";
            }
        }


        internal static string FormatInvalidSehHeader(object arg1)
        {
            return string.Format("Invalid SEH header: 0x{0:X2}", arg1);
        }


        /// <summary>
        /// Invalid token.
        /// </summary>
        internal static string InvalidToken
        {
            get
            {
                return "Invalid token.";
            }
        }



        /// <summary>
        /// Metadata image doesn't represent an assembly.
        /// </summary>
        internal static string MetadataImageDoesNotRepresentAnAssembly
        {
            get
            {
                return "Metadata image doesn't represent an assembly.";
            }
        }



        /// <summary>
        /// Standalone debug metadata image doesn't contain Module table.
        /// </summary>
        internal static string StandaloneDebugMetadataImageDoesNotContainModuleTable
        {
            get
            {
                return "Standalone debug metadata image doesn't contain Module table.";
            }
        }



        /// <summary>
        /// PE image not available.
        /// </summary>
        internal static string PEImageNotAvailable
        {
            get
            {
                return "PE image not available.";
            }
        }



        /// <summary>
        /// Missing data directory.
        /// </summary>
        internal static string MissingDataDirectory
        {
            get
            {
                return "Missing data directory.";
            }
        }



        /// <summary>
        /// Specified handle is not a valid metadata heap handle.
        /// </summary>
        internal static string NotMetadataHeapHandle
        {
            get
            {
                return "Specified handle is not a valid metadata heap handle.";
            }
        }



        /// <summary>
        /// Specified handle is not a valid metadata table or UserString heap handle.
        /// </summary>
        internal static string NotMetadataTableOrUserStringHandle
        {
            get
            {
                return "Specified handle is not a valid metadata table or UserString heap handle.";
            }
        }



        /// <summary>
        /// Section too small.
        /// </summary>
        internal static string SectionTooSmall
        {
            get
            {
                return "Section too small.";
            }
        }



        /// <summary>
        /// Stream must support read and seek operations.
        /// </summary>
        internal static string StreamMustSupportReadAndSeek
        {
            get
            {
                return "Stream must support read and seek operations.";
            }
        }



        /// <summary>
        /// Unknown file format.
        /// </summary>
        internal static string UnknownFileFormat
        {
            get
            {
                return "Unknown file format.";
            }
        }



        /// <summary>
        /// Unknown PE Magic value.
        /// </summary>
        internal static string UnknownPEMagicValue
        {
            get
            {
                return "Unknown PE Magic value.";
            }
        }



        /// <summary>
        /// Metadata table {0} not sorted.
        /// </summary>
        internal static string MetadataTableNotSorted
        {
            get
            {
                return "Metadata table {0} not sorted.";
            }
        }


        internal static string FormatMetadataTableNotSorted(object arg1)
        {
            return string.Format("Metadata table {0} not sorted.", arg1);
        }


        /// <summary>
        /// Invalid number of rows of Module table: {0}.
        /// </summary>
        internal static string ModuleTableInvalidNumberOfRows
        {
            get
            {
                return "Invalid number of rows of Module table: {0}.";
            }
        }


        internal static string FormatModuleTableInvalidNumberOfRows(object arg1)
        {
            return string.Format("Invalid number of rows of Module table: {0}.", arg1);
        }


        /// <summary>
        /// Unknown tables: 0x{0:x16}.
        /// </summary>
        internal static string UnknownTables
        {
            get
            {
                return "Unknown tables: 0x{0:x16}.";
            }
        }


        internal static string FormatUnknownTables(object arg1)
        {
            return string.Format("Unknown tables: 0x{0:x16}.", arg1);
        }


        /// <summary>
        /// Illegal tables in compressed metadata stream.
        /// </summary>
        internal static string IllegalTablesInCompressedMetadataStream
        {
            get
            {
                return "Illegal tables in compressed metadata stream.";
            }
        }



        /// <summary>
        /// Table row count space to small.
        /// </summary>
        internal static string TableRowCountSpaceTooSmall
        {
            get
            {
                return "Table row count space to small.";
            }
        }



        /// <summary>
        /// Read out of bounds.
        /// </summary>
        internal static string OutOfBoundsRead
        {
            get
            {
                return "Read out of bounds.";
            }
        }



        /// <summary>
        /// Write out of bounds.
        /// </summary>
        internal static string OutOfBoundsWrite
        {
            get
            {
                return "Write out of bounds.";
            }
        }



        /// <summary>
        /// Metadata header too small.
        /// </summary>
        internal static string MetadataHeaderTooSmall
        {
            get
            {
                return "Metadata header too small.";
            }
        }



        /// <summary>
        /// Invalid COR20 header signature.
        /// </summary>
        internal static string MetadataSignature
        {
            get
            {
                return "Invalid COR20 header signature.";
            }
        }



        /// <summary>
        /// Not enough space for version string.
        /// </summary>
        internal static string NotEnoughSpaceForVersionString
        {
            get
            {
                return "Not enough space for version string.";
            }
        }



        /// <summary>
        /// Stream header too small.
        /// </summary>
        internal static string StreamHeaderTooSmall
        {
            get
            {
                return "Stream header too small.";
            }
        }



        /// <summary>
        /// Not enough space for stream header name.
        /// </summary>
        internal static string NotEnoughSpaceForStreamHeaderName
        {
            get
            {
                return "Not enough space for stream header name.";
            }
        }



        /// <summary>
        /// Not enough space for String stream.
        /// </summary>
        internal static string NotEnoughSpaceForStringStream
        {
            get
            {
                return "Not enough space for String stream.";
            }
        }



        /// <summary>
        /// Not enough space for Blob stream.
        /// </summary>
        internal static string NotEnoughSpaceForBlobStream
        {
            get
            {
                return "Not enough space for Blob stream.";
            }
        }



        /// <summary>
        /// Not enough space for GUID stream.
        /// </summary>
        internal static string NotEnoughSpaceForGUIDStream
        {
            get
            {
                return "Not enough space for GUID stream.";
            }
        }



        /// <summary>
        /// Not enough space for Metadata stream.
        /// </summary>
        internal static string NotEnoughSpaceForMetadataStream
        {
            get
            {
                return "Not enough space for Metadata stream.";
            }
        }



        /// <summary>
        /// Invalid Metadata stream format.
        /// </summary>
        internal static string InvalidMetadataStreamFormat
        {
            get
            {
                return "Invalid Metadata stream format.";
            }
        }



        /// <summary>
        /// Metadata tables too small.
        /// </summary>
        internal static string MetadataTablesTooSmall
        {
            get
            {
                return "Metadata tables too small.";
            }
        }



        /// <summary>
        /// Metadata table header too small.
        /// </summary>
        internal static string MetadataTableHeaderTooSmall
        {
            get
            {
                return "Metadata table header too small.";
            }
        }



        /// <summary>
        /// Missing mscorlib reference in AssemblyRef table.
        /// </summary>
        internal static string WinMDMissingMscorlibRef
        {
            get
            {
                return "Missing mscorlib reference in AssemblyRef table.";
            }
        }



        /// <summary>
        /// Unexpected stream end.
        /// </summary>
        internal static string UnexpectedStreamEnd
        {
            get
            {
                return "Unexpected stream end.";
            }
        }



        /// <summary>
        /// Invalid relative virtual address (RVA): 0x{0:X8}
        /// </summary>
        internal static string InvalidMethodRva
        {
            get
            {
                return "Invalid relative virtual address (RVA): 0x{0:X8}";
            }
        }


        internal static string FormatInvalidMethodRva(object arg1)
        {
            return string.Format("Invalid relative virtual address (RVA): 0x{0:X8}", arg1);
        }


        /// <summary>
        /// Can't get a heap offset for a virtual heap handle
        /// </summary>
        internal static string CantGetOffsetForVirtualHeapHandle
        {
            get
            {
                return "Can't get a heap offset for a virtual heap handle";
            }
        }



        /// <summary>
        /// Invalid number of sections declared in PE header.
        /// </summary>
        internal static string InvalidNumberOfSections
        {
            get
            {
                return "Invalid number of sections declared in PE header.";
            }
        }



        /// <summary>
        /// Invalid signature.
        /// </summary>
        internal static string InvalidSignature
        {
            get
            {
                return "Invalid signature.";
            }
        }



        /// <summary>
        /// PE image does not have metadata.
        /// </summary>
        internal static string PEImageDoesNotHaveMetadata
        {
            get
            {
                return "PE image does not have metadata.";
            }
        }



        /// <summary>
        /// Invalid coded index.
        /// </summary>
        internal static string InvalidCodedIndex
        {
            get
            {
                return "Invalid coded index.";
            }
        }



        /// <summary>
        /// Invalid compressed integer.
        /// </summary>
        internal static string InvalidCompressedInteger
        {
            get
            {
                return "Invalid compressed integer.";
            }
        }



        /// <summary>
        /// Invalid document name.
        /// </summary>
        internal static string InvalidDocumentName
        {
            get
            {
                return "Invalid document name.";
            }
        }



        /// <summary>
        /// Row ID or heap offset is too large.
        /// </summary>
        internal static string RowIdOrHeapOffsetTooLarge
        {
            get
            {
                return "Row ID or heap offset is too large.";
            }
        }



        /// <summary>
        /// EnCMap table not sorted or has missing records.
        /// </summary>
        internal static string EnCMapNotSorted
        {
            get
            {
                return "EnCMap table not sorted or has missing records.";
            }
        }



        /// <summary>
        /// Invalid serialized string.
        /// </summary>
        internal static string InvalidSerializedString
        {
            get
            {
                return "Invalid serialized string.";
            }
        }



        /// <summary>
        /// Stream length minus starting position is too large to hold a PEImage.
        /// </summary>
        internal static string StreamTooLarge
        {
            get
            {
                return "Stream length minus starting position is too large to hold a PEImage.";
            }
        }



        /// <summary>
        /// Image is either too small or contains an invalid byte offset or count.
        /// </summary>
        internal static string ImageTooSmallOrContainsInvalidOffsetOrCount
        {
            get
            {
                return "Image is either too small or contains an invalid byte offset or count.";
            }
        }



        /// <summary>
        /// The MetadataStringDecoder instance used to instantiate the Metadata reader must have a UTF-8 encoding.
        /// </summary>
        internal static string MetadataStringDecoderEncodingMustBeUtf8
        {
            get
            {
                return "The MetadataStringDecoder instance used to instantiate the Metadata reader must have a UTF-8 encoding.";
            }
        }



        /// <summary>
        /// Invalid constant value.
        /// </summary>
        internal static string InvalidConstantValue
        {
            get
            {
                return "Invalid constant value.";
            }
        }



        /// <summary>
        /// Value of type '{0}' is not a constant.
        /// </summary>
        internal static string InvalidConstantValueOfType
        {
            get
            {
                return "Value of type '{0}' is not a constant.";
            }
        }


        internal static string FormatInvalidConstantValueOfType(object arg1)
        {
            return string.Format("Value of type '{0}' is not a constant.", arg1);
        }


        /// <summary>
        /// Invalid import definition kind: {0}.
        /// </summary>
        internal static string InvalidImportDefinitionKind
        {
            get
            {
                return "Invalid import definition kind: {0}.";
            }
        }


        internal static string FormatInvalidImportDefinitionKind(object arg1)
        {
            return string.Format("Invalid import definition kind: {0}.", arg1);
        }


        /// <summary>
        /// Value is too large.
        /// </summary>
        internal static string ValueTooLarge
        {
            get
            {
                return "Value is too large.";
            }
        }



        /// <summary>
        /// Blob is to large.
        /// </summary>
        internal static string BlobTooLarge
        {
            get
            {
                return "Blob is to large.";
            }
        }



        /// <summary>
        /// Invalid type size.
        /// </summary>
        internal static string InvalidTypeSize
        {
            get
            {
                return "Invalid type size.";
            }
        }



        /// <summary>
        /// Handle belongs to a future generation
        /// </summary>
        internal static string HandleBelongsToFutureGeneration
        {
            get
            {
                return "Handle belongs to a future generation";
            }
        }



        /// <summary>
        /// Invalid row count: {0}
        /// </summary>
        internal static string InvalidRowCount
        {
            get
            {
                return "Invalid row count: {0}";
            }
        }


        internal static string FormatInvalidRowCount(object arg1)
        {
            return string.Format("Invalid row count: {0}", arg1);
        }


        /// <summary>
        /// Invalid entry point token: 0x{0:8X}
        /// </summary>
        internal static string InvalidEntryPointToken
        {
            get
            {
                return "Invalid entry point token: 0x{0:8X}";
            }
        }


        internal static string FormatInvalidEntryPointToken(object arg1)
        {
            return string.Format("Invalid entry point token: 0x{0:8X}", arg1);
        }


        /// <summary>
        /// There are too many subnamespaces.
        /// </summary>
        internal static string TooManySubnamespaces
        {
            get
            {
                return "There are too many subnamespaces.";
            }
        }



        /// <summary>
        /// There are too many exception regions.
        /// </summary>
        internal static string TooManyExceptionRegions
        {
            get
            {
                return "There are too many exception regions.";
            }
        }



        /// <summary>
        /// Sequence point value is out of range.
        /// </summary>
        internal static string SequencePointValueOutOfRange
        {
            get
            {
                return "Sequence point value is out of range.";
            }
        }



        /// <summary>
        /// Invalid directory relative virtual address.
        /// </summary>
        internal static string InvalidDirectoryRVA
        {
            get
            {
                return "Invalid directory relative virtual address.";
            }
        }



        /// <summary>
        /// Invalid directory size.
        /// </summary>
        internal static string InvalidDirectorySize
        {
            get
            {
                return "Invalid directory size.";
            }
        }



        /// <summary>
        /// The value of field Characteristics in debug directory entry must be zero.
        /// </summary>
        internal static string InvalidDebugDirectoryEntryCharacteristics
        {
            get
            {
                return "The value of field Characteristics in debug directory entry must be zero.";
            }
        }



        /// <summary>
        /// Unexpected CodeView data signature value.
        /// </summary>
        internal static string UnexpectedCodeViewDataSignature
        {
            get
            {
                return "Unexpected CodeView data signature value.";
            }
        }



        /// <summary>
        /// Unexpected Embedded Portable PDB data signature value.
        /// </summary>
        internal static string UnexpectedEmbeddedPortablePdbDataSignature
        {
            get
            {
                return "Unexpected Embedded Portable PDB data signature value.";
            }
        }



        /// <summary>
        /// Invalid PDB Checksum data format.
        /// </summary>
        internal static string InvalidPdbChecksumDataFormat
        {
            get
            {
                return "Invalid PDB Checksum data format.";
            }
        }



        /// <summary>
        /// Expected signature header for '{0}', but found '{1}' (0x{2:x2}).
        /// </summary>
        internal static string UnexpectedSignatureHeader
        {
            get
            {
                return "Expected signature header for '{0}', but found '{1}' (0x{2:x2}).";
            }
        }


        internal static string FormatUnexpectedSignatureHeader(object arg1, object arg2, object arg3)
        {
            return string.Format("Expected signature header for '{0}', but found '{1}' (0x{2:x2}).", arg1, arg2, arg3);
        }


        /// <summary>
        /// Expected signature header for '{0}' or '{1}', but found '{2}' (0x{3:x2}).
        /// </summary>
        internal static string UnexpectedSignatureHeader2
        {
            get
            {
                return "Expected signature header for '{0}' or '{1}', but found '{2}' (0x{3:x2}).";
            }
        }


        internal static string FormatUnexpectedSignatureHeader2(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format("Expected signature header for '{0}' or '{1}', but found '{2}' (0x{3:x2}).", arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// Specified handle is not a TypeDefinitionHandle or TypeReferenceHandle.
        /// </summary>
        internal static string NotTypeDefOrRefHandle
        {
            get
            {
                return "Specified handle is not a TypeDefinitionHandle or TypeReferenceHandle.";
            }
        }



        /// <summary>
        /// Unexpected SignatureTypeCode: (0x{0:x}).
        /// </summary>
        internal static string UnexpectedSignatureTypeCode
        {
            get
            {
                return "Unexpected SignatureTypeCode: (0x{0:x}).";
            }
        }


        internal static string FormatUnexpectedSignatureTypeCode(object arg1)
        {
            return string.Format("Unexpected SignatureTypeCode: (0x{0:x}).", arg1);
        }


        /// <summary>
        /// Signature type sequence must have at least one element.
        /// </summary>
        internal static string SignatureTypeSequenceMustHaveAtLeastOneElement
        {
            get
            {
                return "Signature type sequence must have at least one element.";
            }
        }



        /// <summary>
        /// Specified handle is not a TypeDefinitionHandle, TypeReferenceHandle, or TypeSpecificationHandle.
        /// </summary>
        internal static string NotTypeDefOrRefOrSpecHandle
        {
            get
            {
                return "Specified handle is not a TypeDefinitionHandle, TypeReferenceHandle, or TypeSpecificationHandle.";
            }
        }



        /// <summary>
        /// The Debug directory was not of type {0}.
        /// </summary>
        internal static string UnexpectedDebugDirectoryType
        {
            get
            {
                return "The Debug directory was not of type {0}.";
            }
        }


        internal static string FormatUnexpectedDebugDirectoryType(object arg1)
        {
            return string.Format("The Debug directory was not of type {0}.", arg1);
        }


        /// <summary>
        /// The limit on the size of {0} heap has been exceeded.
        /// </summary>
        internal static string HeapSizeLimitExceeded
        {
            get
            {
                return "The limit on the size of {0} heap has been exceeded.";
            }
        }


        internal static string FormatHeapSizeLimitExceeded(object arg1)
        {
            return string.Format("The limit on the size of {0} heap has been exceeded.", arg1);
        }


        /// <summary>
        /// Builder must be aligned to 4 byte boundary.
        /// </summary>
        internal static string BuilderMustAligned
        {
            get
            {
                return "Builder must be aligned to 4 byte boundary.";
            }
        }



        /// <summary>
        /// The operation is not valid on this builder as it has been linked with another one.
        /// </summary>
        internal static string BuilderAlreadyLinked
        {
            get
            {
                return "The operation is not valid on this builder as it has been linked with another one.";
            }
        }



        /// <summary>
        /// The size of the builder returned by {0}.{1} is smaller than requested.
        /// </summary>
        internal static string ReturnedBuilderSizeTooSmall
        {
            get
            {
                return "The size of the builder returned by {0}.{1} is smaller than requested.";
            }
        }


        internal static string FormatReturnedBuilderSizeTooSmall(object arg1, object arg2)
        {
            return string.Format("The size of the builder returned by {0}.{1} is smaller than requested.", arg1, arg2);
        }


        /// <summary>
        /// Can't add vararg parameters to non-vararg signature.
        /// </summary>
        internal static string SignatureNotVarArg
        {
            get
            {
                return "Can't add vararg parameters to non-vararg signature.";
            }
        }



        /// <summary>
        /// Specified label doesn't belong to the current builder.
        /// </summary>
        internal static string LabelDoesntBelongToBuilder
        {
            get
            {
                return "Specified label doesn't belong to the current builder.";
            }
        }



        /// <summary>
        /// Can't emit a branch or exception region, the current encoder not created with a control flow builder.
        /// </summary>
        internal static string ControlFlowBuilderNotAvailable
        {
            get
            {
                return "Can't emit a branch or exception region, the current encoder not created with a control flow builder.";
            }
        }



        /// <summary>
        /// Base reader must be a full metadata reader.
        /// </summary>
        internal static string BaseReaderMustBeFullMetadataReader
        {
            get
            {
                return "Base reader must be a full metadata reader.";
            }
        }



        /// <summary>
        /// Module already added.
        /// </summary>
        internal static string ModuleAlreadyAdded
        {
            get
            {
                return "Module already added.";
            }
        }



        /// <summary>
        /// Assembly already added.
        /// </summary>
        internal static string AssemblyAlreadyAdded
        {
            get
            {
                return "Assembly already added.";
            }
        }



        /// <summary>
        /// Expected list of size {0}.
        /// </summary>
        internal static string ExpectedListOfSize
        {
            get
            {
                return "Expected list of size {0}.";
            }
        }


        internal static string FormatExpectedListOfSize(object arg1)
        {
            return string.Format("Expected list of size {0}.", arg1);
        }


        /// <summary>
        /// Expected array of size {0}.
        /// </summary>
        internal static string ExpectedArrayOfSize
        {
            get
            {
                return "Expected array of size {0}.";
            }
        }


        internal static string FormatExpectedArrayOfSize(object arg1)
        {
            return string.Format("Expected array of size {0}.", arg1);
        }


        /// <summary>
        /// Expected non-empty list.
        /// </summary>
        internal static string ExpectedNonEmptyList
        {
            get
            {
                return "Expected non-empty list.";
            }
        }



        /// <summary>
        /// Expected non-empty array.
        /// </summary>
        internal static string ExpectedNonEmptyArray
        {
            get
            {
                return "Expected non-empty array.";
            }
        }



        /// <summary>
        /// Expected non-empty string.
        /// </summary>
        internal static string ExpectedNonEmptyString
        {
            get
            {
                return "Expected non-empty string.";
            }
        }



        /// <summary>
        /// Specified readers must be minimal delta metadata readers.
        /// </summary>
        internal static string ReadersMustBeDeltaReaders
        {
            get
            {
                return "Specified readers must be minimal delta metadata readers.";
            }
        }



        /// <summary>
        /// Signature provider returned invalid signature.
        /// </summary>
        internal static string SignatureProviderReturnedInvalidSignature
        {
            get
            {
                return "Signature provider returned invalid signature.";
            }
        }



        /// <summary>
        /// Unknown section name: '{0}'.
        /// </summary>
        internal static string UnknownSectionName
        {
            get
            {
                return "Unknown section name: '{0}'.";
            }
        }


        internal static string FormatUnknownSectionName(object arg1)
        {
            return string.Format("Unknown section name: '{0}'.", arg1);
        }


        /// <summary>
        /// Hash must be at least {0}B long.
        /// </summary>
        internal static string HashTooShort
        {
            get
            {
                return "Hash must be at least {0}B long.";
            }
        }


        internal static string FormatHashTooShort(object arg1)
        {
            return string.Format("Hash must be at least {0}B long.", arg1);
        }


        /// <summary>
        /// Expected array of length {0}.
        /// </summary>
        internal static string UnexpectedArrayLength
        {
            get
            {
                return "Expected array of length {0}.";
            }
        }


        internal static string FormatUnexpectedArrayLength(object arg1)
        {
            return string.Format("Expected array of length {0}.", arg1);
        }


        /// <summary>
        /// Value must be multiple of {0}.
        /// </summary>
        internal static string ValueMustBeMultiple
        {
            get
            {
                return "Value must be multiple of {0}.";
            }
        }


        internal static string FormatValueMustBeMultiple(object arg1)
        {
            return string.Format("Value must be multiple of {0}.", arg1);
        }


        /// <summary>
        /// {0} must not return null.
        /// </summary>
        internal static string MustNotReturnNull
        {
            get
            {
                return "{0} must not return null.";
            }
        }


        internal static string FormatMustNotReturnNull(object arg1)
        {
            return string.Format("{0} must not return null.", arg1);
        }


        /// <summary>
        /// Metadata version too long.
        /// </summary>
        internal static string MetadataVersionTooLong
        {
            get
            {
                return "Metadata version too long.";
            }
        }



        /// <summary>
        /// Row count must be zero for table #{0}.
        /// </summary>
        internal static string RowCountMustBeZero
        {
            get
            {
                return "Row count must be zero for table #{0}.";
            }
        }


        internal static string FormatRowCountMustBeZero(object arg1)
        {
            return string.Format("Row count must be zero for table #{0}.", arg1);
        }


        /// <summary>
        /// Row count specified for table index {0} is out of allowed range.
        /// </summary>
        internal static string RowCountOutOfRange
        {
            get
            {
                return "Row count specified for table index {0} is out of allowed range.";
            }
        }


        internal static string FormatRowCountOutOfRange(object arg1)
        {
            return string.Format("Row count specified for table index {0} is out of allowed range.", arg1);
        }


        /// <summary>
        /// Declared size doesn't correspond to the actual size.
        /// </summary>
        internal static string SizeMismatch
        {
            get
            {
                return "Declared size doesn't correspond to the actual size.";
            }
        }



        /// <summary>
        /// Data too big to fit in memory.
        /// </summary>
        internal static string DataTooBig
        {
            get
            {
                return "Data too big to fit in memory.";
            }
        }



        /// <summary>
        /// Unsupported format version: {0}
        /// </summary>
        internal static string UnsupportedFormatVersion
        {
            get
            {
                return "Unsupported format version: {0}";
            }
        }


        internal static string FormatUnsupportedFormatVersion(object arg1)
        {
            return string.Format("Unsupported format version: {0}", arg1);
        }


        /// <summary>
        /// The distance between the instruction {0} (offset {1}) and the target label doesn't fit the operand size: {2}
        /// </summary>
        internal static string DistanceBetweenInstructionAndLabelTooBig
        {
            get
            {
                return "The distance between the instruction {0} (offset {1}) and the target label doesn't fit the operand size: {2}";
            }
        }


        internal static string FormatDistanceBetweenInstructionAndLabelTooBig(object arg1, object arg2, object arg3)
        {
            return string.Format("The distance between the instruction {0} (offset {1}) and the target label doesn't fit the operand size: {2}", arg1, arg2, arg3);
        }


        /// <summary>
        /// Label {0} has not been marked.
        /// </summary>
        internal static string LabelNotMarked
        {
            get
            {
                return "Label {0} has not been marked.";
            }
        }


        internal static string FormatLabelNotMarked(object arg1)
        {
            return string.Format("Label {0} has not been marked.", arg1);
        }


        /// <summary>
        /// Method body was created with no exception regions.
        /// </summary>
        internal static string MethodHasNoExceptionRegions
        {
            get
            {
                return "Method body was created with no exception regions.";
            }
        }



        /// <summary>
        /// Invalid exception region bounds: start offset ({0}) is greater than end offset ({1}).
        /// </summary>
        internal static string InvalidExceptionRegionBounds
        {
            get
            {
                return "Invalid exception region bounds: start offset ({0}) is greater than end offset ({1}).";
            }
        }


        internal static string FormatInvalidExceptionRegionBounds(object arg1, object arg2)
        {
            return string.Format("Invalid exception region bounds: start offset ({0}) is greater than end offset ({1}).", arg1, arg2);
        }


        /// <summary>
        /// Unexpected value '{0}' of type '{1}'
        /// </summary>
        internal static string UnexpectedValue
        {
            get
            {
                return "Unexpected value '{0}' of type '{1}'";
            }
        }


        internal static string FormatUnexpectedValue(object arg1, object arg2)
        {
            return string.Format("Unexpected value '{0}' of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Unexpected value '{0}' of unknown type.
        /// </summary>
        internal static string UnexpectedValueUnknownType
        {
            get
            {
                return "Unexpected value '{0}' of unknown type.";
            }
        }


        internal static string FormatUnexpectedValueUnknownType(object arg1)
        {
            return string.Format("Unexpected value '{0}' of unknown type.", arg1);
        }


        /// <summary>
        /// The SwitchInstructionEncoder.Branch method was invoked too few times.
        /// </summary>
        internal static string SwitchInstructionEncoderTooFewBranches
        {
            get
            {
                return "The SwitchInstructionEncoder.Branch method was invoked too few times.";
            }
        }



        /// <summary>
        /// The SwitchInstructionEncoder.Branch method was invoked too many times.
        /// </summary>
        internal static string SwitchInstructionEncoderTooManyBranches
        {
            get
            {
                return "The SwitchInstructionEncoder.Branch method was invoked too many times.";
            }
        }



        /// <summary>
        /// The name of the type is invalid.
        /// </summary>
        internal static string Argument_InvalidTypeName
        {
            get
            {
                return "The name of the type is invalid.";
            }
        }



        /// <summary>
        /// Maximum node count of {0} exceeded.
        /// </summary>
        internal static string InvalidOperation_MaxNodesExceeded
        {
            get
            {
                return "Maximum node count of {0} exceeded.";
            }
        }


        internal static string FormatInvalidOperation_MaxNodesExceeded(object arg1)
        {
            return string.Format("Maximum node count of {0} exceeded.", arg1);
        }


        /// <summary>
        /// Must be an array type.
        /// </summary>
        internal static string Argument_HasToBeArrayClass
        {
            get
            {
                return "Must be an array type.";
            }
        }



        /// <summary>
        /// This operation is only valid on generic types.
        /// </summary>
        internal static string InvalidOperation_NotGenericType
        {
            get
            {
                return "This operation is only valid on generic types.";
            }
        }



        /// <summary>
        /// This operation is only valid on nested types.
        /// </summary>
        internal static string InvalidOperation_NotNestedType
        {
            get
            {
                return "This operation is only valid on nested types.";
            }
        }



        /// <summary>
        /// This operation is only valid on arrays, pointers and references.
        /// </summary>
        internal static string InvalidOperation_NoElement
        {
            get
            {
                return "This operation is only valid on arrays, pointers and references.";
            }
        }



        /// <summary>
        /// Cannot retrieve the namespace of a nested type.
        /// </summary>
        internal static string InvalidOperation_NestedTypeNamespace
        {
            get
            {
                return "Cannot retrieve the namespace of a nested type.";
            }
        }



        /// <summary>
        /// The given assembly name was invalid.
        /// </summary>
        internal static string InvalidAssemblyName
        {
            get
            {
                return "The given assembly name was invalid.";
            }
        }



        /// <summary>
        /// '{0}' is not a simple TypeName.
        /// </summary>
        internal static string Arg_NotSimpleTypeName
        {
            get
            {
                return "'{0}' is not a simple TypeName.";
            }
        }


        internal static string FormatArg_NotSimpleTypeName(object arg1)
        {
            return string.Format("'{0}' is not a simple TypeName.", arg1);
        }
    }
}
