
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Formats.Asn1", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Destination is too short.
        /// </summary>
        internal static string Argument_DestinationTooShort
        {
            get
            {
                return "Destination is too short.";
            }
        }



        /// <summary>
        /// ASN.1 Enumerated values only apply to enum types without the [Flags] attribute.
        /// </summary>
        internal static string Argument_EnumeratedValueRequiresNonFlagsEnum
        {
            get
            {
                return "ASN.1 Enumerated values only apply to enum types without the [Flags] attribute.";
            }
        }



        /// <summary>
        /// Enumerations with a backing type of '{0}' are not supported for ReadEnumeratedValue.
        /// </summary>
        internal static string Argument_EnumeratedValueBackingTypeNotSupported
        {
            get
            {
                return "Enumerations with a backing type of '{0}' are not supported for ReadEnumeratedValue.";
            }
        }


        internal static string FormatArgument_EnumeratedValueBackingTypeNotSupported(object arg1)
        {
            return string.Format("Enumerations with a backing type of '{0}' are not supported for ReadEnumeratedValue.", arg1);
        }


        /// <summary>
        /// The OID value is invalid.
        /// </summary>
        internal static string Argument_InvalidOidValue
        {
            get
            {
                return "The OID value is invalid.";
            }
        }



        /// <summary>
        /// Named bit list operations require an enum with the [Flags] attribute.
        /// </summary>
        internal static string Argument_NamedBitListRequiresFlagsEnum
        {
            get
            {
                return "Named bit list operations require an enum with the [Flags] attribute.";
            }
        }



        /// <summary>
        /// The destination buffer overlaps the source buffer.
        /// </summary>
        internal static string Argument_SourceOverlapsDestination
        {
            get
            {
                return "The destination buffer overlaps the source buffer.";
            }
        }



        /// <summary>
        /// The specified tag has the Universal TagClass, but the TagValue does not correspond with a known character string type.
        /// </summary>
        internal static string Argument_Tag_NotCharacterString
        {
            get
            {
                return "The specified tag has the Universal TagClass, but the TagValue does not correspond with a known character string type.";
            }
        }



        /// <summary>
        /// An integer value cannot be empty.
        /// </summary>
        internal static string Argument_IntegerCannotBeEmpty
        {
            get
            {
                return "An integer value cannot be empty.";
            }
        }



        /// <summary>
        /// The first 9 bits of the integer value all have the same value. Ensure the input is in big-endian byte order and that all redundant leading bytes have been removed.
        /// </summary>
        internal static string Argument_IntegerRedundantByte
        {
            get
            {
                return "The first 9 bits of the integer value all have the same value. Ensure the input is in big-endian byte order and that all redundant leading bytes have been removed.";
            }
        }



        /// <summary>
        /// Tags with TagClass Universal must have the appropriate TagValue value for the data type being read or written.
        /// </summary>
        internal static string Argument_UniversalValueIsFixed
        {
            get
            {
                return "Tags with TagClass Universal must have the appropriate TagValue value for the data type being read or written.";
            }
        }



        /// <summary>
        /// Unused bit count must be 0 when the bit string is empty.
        /// </summary>
        internal static string Argument_UnusedBitCountMustBeZero
        {
            get
            {
                return "Unused bit count must be 0 when the bit string is empty.";
            }
        }



        /// <summary>
        /// Unused bit count must be between 0 and 7, inclusive.
        /// </summary>
        internal static string Argument_UnusedBitCountRange
        {
            get
            {
                return "Unused bit count must be between 0 and 7, inclusive.";
            }
        }



        /// <summary>
        /// One or more of the bits covered by the provided unusedBitCount value is set. All unused bits must be cleared.
        /// </summary>
        internal static string Argument_UnusedBitWasSet
        {
            get
            {
                return "One or more of the bits covered by the provided unusedBitCount value is set. All unused bits must be cleared.";
            }
        }



        /// <summary>
        /// The input to WriteEncodedValue must represent a single encoded value with no trailing data.
        /// </summary>
        internal static string Argument_WriteEncodedValue_OneValueAtATime
        {
            get
            {
                return "The input to WriteEncodedValue must represent a single encoded value with no trailing data.";
            }
        }



        /// <summary>
        /// Non-negative number required.
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum
        {
            get
            {
                return "Non-negative number required.";
            }
        }



        /// <summary>
        /// Encode cannot be called while a Sequence, Set-Of, or Octet String is still open.
        /// </summary>
        internal static string AsnWriter_EncodeUnbalancedStack
        {
            get
            {
                return "Encode cannot be called while a Sequence, Set-Of, or Octet String is still open.";
            }
        }



        /// <summary>
        /// The AsnWriter cannot be written to while performing the Encode callback.
        /// </summary>
        internal static string AsnWriter_ModifyingWhileEncoding
        {
            get
            {
                return "The AsnWriter cannot be written to while performing the Encode callback.";
            }
        }



        /// <summary>
        /// Cannot pop the requested tag as it is not currently in progress.
        /// </summary>
        internal static string AsnWriter_PopWrongTag
        {
            get
            {
                return "Cannot pop the requested tag as it is not currently in progress.";
            }
        }



        /// <summary>
        /// A constructed tag used a definite length encoding, which is invalid for CER data. The input may be encoded with BER or DER.
        /// </summary>
        internal static string ContentException_CerRequiresIndefiniteLength
        {
            get
            {
                return "A constructed tag used a definite length encoding, which is invalid for CER data. The input may be encoded with BER or DER.";
            }
        }



        /// <summary>
        /// The encoded value uses a primitive encoding, which is invalid for '{0}' values.
        /// </summary>
        internal static string ContentException_ConstructedEncodingRequired
        {
            get
            {
                return "The encoded value uses a primitive encoding, which is invalid for '{0}' values.";
            }
        }


        internal static string FormatContentException_ConstructedEncodingRequired(object arg1)
        {
            return string.Format("The encoded value uses a primitive encoding, which is invalid for '{0}' values.", arg1);
        }


        /// <summary>
        /// The ASN.1 value is invalid.
        /// </summary>
        internal static string ContentException_DefaultMessage
        {
            get
            {
                return "The ASN.1 value is invalid.";
            }
        }



        /// <summary>
        /// The encoded enumerated value is larger than the value size of the '{0}' enum.
        /// </summary>
        internal static string ContentException_EnumeratedValueTooBig
        {
            get
            {
                return "The encoded enumerated value is larger than the value size of the '{0}' enum.";
            }
        }


        internal static string FormatContentException_EnumeratedValueTooBig(object arg1)
        {
            return string.Format("The encoded enumerated value is larger than the value size of the '{0}' enum.", arg1);
        }


        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER or DER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderCer_TryBerOrDer
        {
            get
            {
                return "The encoded value is not valid under the selected encoding, but it may be valid under the BER or DER encoding.";
            }
        }



        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderCerOrDer_TryBer
        {
            get
            {
                return "The encoded value is not valid under the selected encoding, but it may be valid under the BER encoding.";
            }
        }



        /// <summary>
        /// The encoded value is not valid under the selected encoding, but it may be valid under the BER or CER encoding.
        /// </summary>
        internal static string ContentException_InvalidUnderDer_TryBerOrCer
        {
            get
            {
                return "The encoded value is not valid under the selected encoding, but it may be valid under the BER or CER encoding.";
            }
        }



        /// <summary>
        /// The provided data does not represent a valid tag.
        /// </summary>
        internal static string ContentException_InvalidTag
        {
            get
            {
                return "The provided data does not represent a valid tag.";
            }
        }



        /// <summary>
        /// The encoded length exceeds the number of bytes remaining in the input buffer.
        /// </summary>
        internal static string ContentException_LengthExceedsPayload
        {
            get
            {
                return "The encoded length exceeds the number of bytes remaining in the input buffer.";
            }
        }



        /// <summary>
        /// The encoded length is not valid under the requested encoding rules, the value may be valid under the BER encoding.
        /// </summary>
        internal static string ContentException_LengthRuleSetConstraint
        {
            get
            {
                return "The encoded length is not valid under the requested encoding rules, the value may be valid under the BER encoding.";
            }
        }



        /// <summary>
        /// The encoded length exceeds the maximum supported by this library (Int32.MaxValue).
        /// </summary>
        internal static string ContentException_LengthTooBig
        {
            get
            {
                return "The encoded length exceeds the maximum supported by this library (Int32.MaxValue).";
            }
        }



        /// <summary>
        /// The encoded named bit list value is larger than the value size of the '{0}' enum.
        /// </summary>
        internal static string ContentException_NamedBitListValueTooBig
        {
            get
            {
                return "The encoded named bit list value is larger than the value size of the '{0}' enum.";
            }
        }


        internal static string FormatContentException_NamedBitListValueTooBig(object arg1)
        {
            return string.Format("The encoded named bit list value is larger than the value size of the '{0}' enum.", arg1);
        }


        /// <summary>
        /// The encoded object identifier (OID) exceeds the limits supported by this library. Supported OIDs are limited to 64 arcs and each subidentifier is limited to a 128-bit value.
        /// </summary>
        internal static string ContentException_OidTooBig
        {
            get
            {
                return "The encoded object identifier (OID) exceeds the limits supported by this library. Supported OIDs are limited to 64 arcs and each subidentifier is limited to a 128-bit value.";
            }
        }



        /// <summary>
        /// The encoded value uses a constructed encoding, which is invalid for '{0}' values.
        /// </summary>
        internal static string ContentException_PrimitiveEncodingRequired
        {
            get
            {
                return "The encoded value uses a constructed encoding, which is invalid for '{0}' values.";
            }
        }


        internal static string FormatContentException_PrimitiveEncodingRequired(object arg1)
        {
            return string.Format("The encoded value uses a constructed encoding, which is invalid for '{0}' values.", arg1);
        }


        /// <summary>
        /// The encoded set is not sorted as required by the current encoding rules. The value may be valid under the BER encoding, or you can ignore the sort validation by specifying skipSortValidation=true.
        /// </summary>
        internal static string ContentException_SetOfNotSorted
        {
            get
            {
                return "The encoded set is not sorted as required by the current encoding rules. The value may be valid under the BER encoding, or you can ignore the sort validation by specifying skipSortValidation=true.";
            }
        }



        /// <summary>
        /// The last expected value has been read, but the reader still has pending data. This value may be from a newer schema, or is corrupt.
        /// </summary>
        internal static string ContentException_TooMuchData
        {
            get
            {
                return "The last expected value has been read, but the reader still has pending data. This value may be from a newer schema, or is corrupt.";
            }
        }



        /// <summary>
        /// The provided data is tagged with '{0}' class value '{1}', but it should have been '{2}' class value '{3}'.
        /// </summary>
        internal static string ContentException_WrongTag
        {
            get
            {
                return "The provided data is tagged with '{0}' class value '{1}', but it should have been '{2}' class value '{3}'.";
            }
        }


        internal static string FormatContentException_WrongTag(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format("The provided data is tagged with '{0}' class value '{1}', but it should have been '{2}' class value '{3}'.", arg1, arg2, arg3, arg4);
        }
    }
}
