
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections.Specialized", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// An item with the same key has already been added. Key: {0}
        /// </summary>
        internal static string Argument_AddingDuplicate
        {
            get
            {
                return "An item with the same key has already been added. Key: {0}";
            }
        }


        internal static string FormatArgument_AddingDuplicate(object arg1)
        {
            return string.Format("An item with the same key has already been added. Key: {0}", arg1);
        }


        /// <summary>
        /// Collection was modified after the enumerator was instantiated.
        /// </summary>
        internal static string InvalidOperation_EnumFailedVersion
        {
            get
            {
                return "Collection was modified after the enumerator was instantiated.";
            }
        }



        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string InvalidOperation_EnumOpCantHappen
        {
            get
            {
                return "Enumeration has either not started or has already finished.";
            }
        }



        /// <summary>
        /// Multi dimension array is not supported on this operation.
        /// </summary>
        internal static string Arg_MultiRank
        {
            get
            {
                return "Multi dimension array is not supported on this operation.";
            }
        }



        /// <summary>
        /// Insufficient space in the target location to copy the information.
        /// </summary>
        internal static string Arg_InsufficientSpace
        {
            get
            {
                return "Insufficient space in the target location to copy the information.";
            }
        }



        /// <summary>
        /// Collection is read-only.
        /// </summary>
        internal static string CollectionReadOnly
        {
            get
            {
                return "Collection is read-only.";
            }
        }



        /// <summary>
        /// Bit vector is full.
        /// </summary>
        internal static string BitVectorFull
        {
            get
            {
                return "Bit vector is full.";
            }
        }



        /// <summary>
        /// The OrderedDictionary is read-only and cannot be modified.
        /// </summary>
        internal static string OrderedDictionary_ReadOnly
        {
            get
            {
                return "The OrderedDictionary is read-only and cannot be modified.";
            }
        }



        /// <summary>
        /// At least one object must implement IComparable.
        /// </summary>
        internal static string Argument_ImplementIComparable
        {
            get
            {
                return "At least one object must implement IComparable.";
            }
        }



        /// <summary>
        /// There was an error deserializing the OrderedDictionary.  The ArrayList does not contain DictionaryEntries.
        /// </summary>
        internal static string OrderedDictionary_SerializationMismatch
        {
            get
            {
                return "There was an error deserializing the OrderedDictionary.  The ArrayList does not contain DictionaryEntries.";
            }
        }



        /// <summary>
        /// OnDeserialization method was called while the object was not being deserialized.
        /// </summary>
        internal static string Serialization_InvalidOnDeser
        {
            get
            {
                return "OnDeserialization method was called while the object was not being deserialized.";
            }
        }



        /// <summary>
        /// Mutating a key collection derived from a dictionary is not allowed.
        /// </summary>
        internal static string NotSupported_KeyCollectionSet
        {
            get
            {
                return "Mutating a key collection derived from a dictionary is not allowed.";
            }
        }



        /// <summary>
        /// Mutating a value collection derived from a dictionary is not allowed.
        /// </summary>
        internal static string NotSupported_ValueCollectionSet
        {
            get
            {
                return "Mutating a value collection derived from a dictionary is not allowed.";
            }
        }

    }
}
