
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Extensions.DependencyInjection.Abstractions", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.
        /// </summary>
        internal static string AmbiguousConstructorMatch
        {
            get
            {
                return "Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.";
            }
        }


        internal static string FormatAmbiguousConstructorMatch(object arg1)
        {
            return string.Format("Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.", arg1);
        }


        /// <summary>
        /// Unable to resolve service for type '{0}' while attempting to activate '{1}'.
        /// </summary>
        internal static string CannotResolveService
        {
            get
            {
                return "Unable to resolve service for type '{0}' while attempting to activate '{1}'.";
            }
        }


        internal static string FormatCannotResolveService(object arg1, object arg2)
        {
            return string.Format("Unable to resolve service for type '{0}' while attempting to activate '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
        /// </summary>
        internal static string NoConstructorMatch
        {
            get
            {
                return "A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.";
            }
        }


        internal static string FormatNoConstructorMatch(object arg1)
        {
            return string.Format("A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.", arg1);
        }


        /// <summary>
        /// No service for type '{0}' has been registered.
        /// </summary>
        internal static string NoServiceRegistered
        {
            get
            {
                return "No service for type '{0}' has been registered.";
            }
        }


        internal static string FormatNoServiceRegistered(object arg1)
        {
            return string.Format("No service for type '{0}' has been registered.", arg1);
        }


        /// <summary>
        /// The service collection cannot be modified because it is read-only.
        /// </summary>
        internal static string ServiceCollectionReadOnly
        {
            get
            {
                return "The service collection cannot be modified because it is read-only.";
            }
        }



        /// <summary>
        /// Implementation type cannot be '{0}' because it is indistinguishable from other services registered for '{1}'.
        /// </summary>
        internal static string TryAddIndistinguishableTypeToEnumerable
        {
            get
            {
                return "Implementation type cannot be '{0}' because it is indistinguishable from other services registered for '{1}'.";
            }
        }


        internal static string FormatTryAddIndistinguishableTypeToEnumerable(object arg1, object arg2)
        {
            return string.Format("Implementation type cannot be '{0}' because it is indistinguishable from other services registered for '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Multiple constructors were marked with {0}.
        /// </summary>
        internal static string MultipleCtorsMarkedWithAttribute
        {
            get
            {
                return "Multiple constructors were marked with {0}.";
            }
        }


        internal static string FormatMultipleCtorsMarkedWithAttribute(object arg1)
        {
            return string.Format("Multiple constructors were marked with {0}.", arg1);
        }


        /// <summary>
        /// Constructor marked with {0} does not accept all given argument types.
        /// </summary>
        internal static string MarkedCtorMissingArgumentTypes
        {
            get
            {
                return "Constructor marked with {0} does not accept all given argument types.";
            }
        }


        internal static string FormatMarkedCtorMissingArgumentTypes(object arg1)
        {
            return string.Format("Constructor marked with {0} does not accept all given argument types.", arg1);
        }


        /// <summary>
        /// Instances of abstract classes cannot be created.
        /// </summary>
        internal static string CannotCreateAbstractClasses
        {
            get
            {
                return "Instances of abstract classes cannot be created.";
            }
        }



        /// <summary>
        /// Multiple constructors for type '{0}' were found with length {1}.
        /// </summary>
        internal static string MultipleCtorsFoundWithBestLength
        {
            get
            {
                return "Multiple constructors for type '{0}' were found with length {1}.";
            }
        }


        internal static string FormatMultipleCtorsFoundWithBestLength(object arg1, object arg2)
        {
            return string.Format("Multiple constructors for type '{0}' were found with length {1}.", arg1, arg2);
        }


        /// <summary>
        /// Unable to resolve service for type '{0}' while attempting to activate '{1}'.
        /// </summary>
        internal static string UnableToResolveService
        {
            get
            {
                return "Unable to resolve service for type '{0}' while attempting to activate '{1}'.";
            }
        }


        internal static string FormatUnableToResolveService(object arg1, object arg2)
        {
            return string.Format("Unable to resolve service for type '{0}' while attempting to activate '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
        /// </summary>
        internal static string CtorNotLocated
        {
            get
            {
                return "A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.";
            }
        }


        internal static string FormatCtorNotLocated(object arg1)
        {
            return string.Format("A suitable constructor for type '{0}' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.", arg1);
        }


        /// <summary>
        /// Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.
        /// </summary>
        internal static string MultipleCtorsFound
        {
            get
            {
                return "Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.";
            }
        }


        internal static string FormatMultipleCtorsFound(object arg1)
        {
            return string.Format("Multiple constructors accepting all given argument types have been found in type '{0}'. There should only be one applicable constructor.", arg1);
        }


        /// <summary>
        /// This service provider doesn't support keyed services.
        /// </summary>
        internal static string KeyedServicesNotSupported
        {
            get
            {
                return "This service provider doesn't support keyed services.";
            }
        }



        /// <summary>
        /// This service descriptor is not keyed.
        /// </summary>
        internal static string NonKeyedDescriptorMisuse
        {
            get
            {
                return "This service descriptor is not keyed.";
            }
        }

    }
}
