
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.IO.Compression", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Enum value was out of legal range.
        /// </summary>
        internal static string ArgumentOutOfRange_Enum
        {
            get
            {
                return "Enum value was out of legal range.";
            }
        }



        /// <summary>
        /// Reading from the compression stream is not supported.
        /// </summary>
        internal static string CannotReadFromDeflateStream
        {
            get
            {
                return "Reading from the compression stream is not supported.";
            }
        }



        /// <summary>
        /// Writing to the compression stream is not supported.
        /// </summary>
        internal static string CannotWriteToDeflateStream
        {
            get
            {
                return "Writing to the compression stream is not supported.";
            }
        }



        /// <summary>
        /// Found invalid data while decoding.
        /// </summary>
        internal static string GenericInvalidData
        {
            get
            {
                return "Found invalid data while decoding.";
            }
        }



        /// <summary>
        /// Only one asynchronous reader or writer is allowed time at one time.
        /// </summary>
        internal static string InvalidBeginCall
        {
            get
            {
                return "Only one asynchronous reader or writer is allowed time at one time.";
            }
        }



        /// <summary>
        /// Block length does not match with its complement.
        /// </summary>
        internal static string InvalidBlockLength
        {
            get
            {
                return "Block length does not match with its complement.";
            }
        }



        /// <summary>
        /// Failed to construct a huffman tree using the length array. The stream might be corrupted.
        /// </summary>
        internal static string InvalidHuffmanData
        {
            get
            {
                return "Failed to construct a huffman tree using the length array. The stream might be corrupted.";
            }
        }



        /// <summary>
        /// This operation is not supported.
        /// </summary>
        internal static string NotSupported
        {
            get
            {
                return "This operation is not supported.";
            }
        }



        /// <summary>
        /// Stream does not support reading.
        /// </summary>
        internal static string NotSupported_UnreadableStream
        {
            get
            {
                return "Stream does not support reading.";
            }
        }



        /// <summary>
        /// Stream does not support writing.
        /// </summary>
        internal static string NotSupported_UnwritableStream
        {
            get
            {
                return "Stream does not support writing.";
            }
        }



        /// <summary>
        /// Unknown block type. Stream might be corrupted.
        /// </summary>
        internal static string UnknownBlockType
        {
            get
            {
                return "Unknown block type. Stream might be corrupted.";
            }
        }



        /// <summary>
        /// Decoder is in some unknown state. This might be caused by corrupted data.
        /// </summary>
        internal static string UnknownState
        {
            get
            {
                return "Decoder is in some unknown state. This might be caused by corrupted data.";
            }
        }



        /// <summary>
        /// The underlying compression routine could not be loaded correctly.
        /// </summary>
        internal static string ZLibErrorDLLLoadError
        {
            get
            {
                return "The underlying compression routine could not be loaded correctly.";
            }
        }



        /// <summary>
        /// The stream state of the underlying compression routine is inconsistent.
        /// </summary>
        internal static string ZLibErrorInconsistentStream
        {
            get
            {
                return "The stream state of the underlying compression routine is inconsistent.";
            }
        }



        /// <summary>
        /// The underlying compression routine received incorrect initialization parameters.
        /// </summary>
        internal static string ZLibErrorIncorrectInitParameters
        {
            get
            {
                return "The underlying compression routine received incorrect initialization parameters.";
            }
        }



        /// <summary>
        /// The underlying compression routine could not reserve sufficient memory.
        /// </summary>
        internal static string ZLibErrorNotEnoughMemory
        {
            get
            {
                return "The underlying compression routine could not reserve sufficient memory.";
            }
        }



        /// <summary>
        /// The version of the underlying compression routine does not match expected version.
        /// </summary>
        internal static string ZLibErrorVersionMismatch
        {
            get
            {
                return "The version of the underlying compression routine does not match expected version.";
            }
        }



        /// <summary>
        /// The underlying compression routine returned an unexpected error code.
        /// </summary>
        internal static string ZLibErrorUnexpected
        {
            get
            {
                return "The underlying compression routine returned an unexpected error code.";
            }
        }



        /// <summary>
        /// Central Directory corrupt.
        /// </summary>
        internal static string CDCorrupt
        {
            get
            {
                return "Central Directory corrupt.";
            }
        }



        /// <summary>
        /// Central Directory is invalid.
        /// </summary>
        internal static string CentralDirectoryInvalid
        {
            get
            {
                return "Central Directory is invalid.";
            }
        }



        /// <summary>
        /// Cannot create entries on an archive opened in read mode.
        /// </summary>
        internal static string CreateInReadMode
        {
            get
            {
                return "Cannot create entries on an archive opened in read mode.";
            }
        }



        /// <summary>
        /// Cannot use create mode on a non-writable stream.
        /// </summary>
        internal static string CreateModeCapabilities
        {
            get
            {
                return "Cannot use create mode on a non-writable stream.";
            }
        }



        /// <summary>
        /// Entries cannot be created while previously created entries are still open.
        /// </summary>
        internal static string CreateModeCreateEntryWhileOpen
        {
            get
            {
                return "Entries cannot be created while previously created entries are still open.";
            }
        }



        /// <summary>
        /// Entries in create mode may only be written to once, and only one entry may be held open at a time.
        /// </summary>
        internal static string CreateModeWriteOnceAndOneEntryAtATime
        {
            get
            {
                return "Entries in create mode may only be written to once, and only one entry may be held open at a time.";
            }
        }



        /// <summary>
        /// The DateTimeOffset specified cannot be converted into a Zip file timestamp.
        /// </summary>
        internal static string DateTimeOutOfRange
        {
            get
            {
                return "The DateTimeOffset specified cannot be converted into a Zip file timestamp.";
            }
        }



        /// <summary>
        /// Cannot modify deleted entry.
        /// </summary>
        internal static string DeletedEntry
        {
            get
            {
                return "Cannot modify deleted entry.";
            }
        }



        /// <summary>
        /// Delete can only be used when the archive is in Update mode.
        /// </summary>
        internal static string DeleteOnlyInUpdate
        {
            get
            {
                return "Delete can only be used when the archive is in Update mode.";
            }
        }



        /// <summary>
        /// Cannot delete an entry currently open for writing.
        /// </summary>
        internal static string DeleteOpenEntry
        {
            get
            {
                return "Cannot delete an entry currently open for writing.";
            }
        }



        /// <summary>
        /// Cannot access entries in Create mode.
        /// </summary>
        internal static string EntriesInCreateMode
        {
            get
            {
                return "Cannot access entries in Create mode.";
            }
        }



        /// <summary>
        /// The specified encoding is not supported for entry names and comments.
        /// </summary>
        internal static string EntryNameAndCommentEncodingNotSupported
        {
            get
            {
                return "The specified encoding is not supported for entry names and comments.";
            }
        }



        /// <summary>
        /// Entry names cannot require more than 2^16 bits.
        /// </summary>
        internal static string EntryNamesTooLong
        {
            get
            {
                return "Entry names cannot require more than 2^16 bits.";
            }
        }



        /// <summary>
        /// Entries larger than 4GB are not supported in Update mode.
        /// </summary>
        internal static string EntryTooLarge
        {
            get
            {
                return "Entries larger than 4GB are not supported in Update mode.";
            }
        }



        /// <summary>
        /// End of Central Directory record could not be found.
        /// </summary>
        internal static string EOCDNotFound
        {
            get
            {
                return "End of Central Directory record could not be found.";
            }
        }



        /// <summary>
        /// Compressed Size cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigCompressedSize
        {
            get
            {
                return "Compressed Size cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Local Header Offset cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigLocalHeaderOffset
        {
            get
            {
                return "Local Header Offset cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Number of Entries cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigNumEntries
        {
            get
            {
                return "Number of Entries cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Offset to Central Directory cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigOffsetToCD
        {
            get
            {
                return "Offset to Central Directory cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Offset to Zip64 End Of Central Directory record cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigOffsetToZip64EOCD
        {
            get
            {
                return "Offset to Zip64 End Of Central Directory record cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Uncompressed Size cannot be held in an Int64.
        /// </summary>
        internal static string FieldTooBigUncompressedSize
        {
            get
            {
                return "Uncompressed Size cannot be held in an Int64.";
            }
        }



        /// <summary>
        /// Cannot modify entry in Create mode after entry has been opened for writing.
        /// </summary>
        internal static string FrozenAfterWrite
        {
            get
            {
                return "Cannot modify entry in Create mode after entry has been opened for writing.";
            }
        }



        /// <summary>
        /// A stream from ZipArchiveEntry has been disposed.
        /// </summary>
        internal static string HiddenStreamName
        {
            get
            {
                return "A stream from ZipArchiveEntry has been disposed.";
            }
        }



        /// <summary>
        /// Length properties are unavailable once an entry has been opened for writing.
        /// </summary>
        internal static string LengthAfterWrite
        {
            get
            {
                return "Length properties are unavailable once an entry has been opened for writing.";
            }
        }



        /// <summary>
        /// A local file header is corrupt.
        /// </summary>
        internal static string LocalFileHeaderCorrupt
        {
            get
            {
                return "A local file header is corrupt.";
            }
        }



        /// <summary>
        /// Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
        /// </summary>
        internal static string NumEntriesWrong
        {
            get
            {
                return "Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.";
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support reading.
        /// </summary>
        internal static string ReadingNotSupported
        {
            get
            {
                return "This stream from ZipArchiveEntry does not support reading.";
            }
        }



        /// <summary>
        /// Cannot use read mode on a non-readable stream.
        /// </summary>
        internal static string ReadModeCapabilities
        {
            get
            {
                return "Cannot use read mode on a non-readable stream.";
            }
        }



        /// <summary>
        /// Cannot modify read-only archive.
        /// </summary>
        internal static string ReadOnlyArchive
        {
            get
            {
                return "Cannot modify read-only archive.";
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support seeking.
        /// </summary>
        internal static string SeekingNotSupported
        {
            get
            {
                return "This stream from ZipArchiveEntry does not support seeking.";
            }
        }



        /// <summary>
        /// SetLength requires a stream that supports seeking and writing.
        /// </summary>
        internal static string SetLengthRequiresSeekingAndWriting
        {
            get
            {
                return "SetLength requires a stream that supports seeking and writing.";
            }
        }



        /// <summary>
        /// Split or spanned archives are not supported.
        /// </summary>
        internal static string SplitSpanned
        {
            get
            {
                return "Split or spanned archives are not supported.";
            }
        }



        /// <summary>
        /// Found truncated data while decoding.
        /// </summary>
        internal static string TruncatedData
        {
            get
            {
                return "Found truncated data while decoding.";
            }
        }



        /// <summary>
        /// Zip file corrupt: unexpected end of stream reached.
        /// </summary>
        internal static string UnexpectedEndOfStream
        {
            get
            {
                return "Zip file corrupt: unexpected end of stream reached.";
            }
        }



        /// <summary>
        /// The archive entry was compressed using an unsupported compression method.
        /// </summary>
        internal static string UnsupportedCompression
        {
            get
            {
                return "The archive entry was compressed using an unsupported compression method.";
            }
        }



        /// <summary>
        /// The archive entry was compressed using {0} and is not supported.
        /// </summary>
        internal static string UnsupportedCompressionMethod
        {
            get
            {
                return "The archive entry was compressed using {0} and is not supported.";
            }
        }


        internal static string FormatUnsupportedCompressionMethod(object arg1)
        {
            return string.Format("The archive entry was compressed using {0} and is not supported.", arg1);
        }


        /// <summary>
        /// Update mode requires a stream with read, write, and seek capabilities.
        /// </summary>
        internal static string UpdateModeCapabilities
        {
            get
            {
                return "Update mode requires a stream with read, write, and seek capabilities.";
            }
        }



        /// <summary>
        /// Entries cannot be opened multiple times in Update mode.
        /// </summary>
        internal static string UpdateModeOneStream
        {
            get
            {
                return "Entries cannot be opened multiple times in Update mode.";
            }
        }



        /// <summary>
        /// This stream from ZipArchiveEntry does not support writing.
        /// </summary>
        internal static string WritingNotSupported
        {
            get
            {
                return "This stream from ZipArchiveEntry does not support writing.";
            }
        }



        /// <summary>
        /// Zip 64 End of Central Directory Record not where indicated.
        /// </summary>
        internal static string Zip64EOCDNotWhereExpected
        {
            get
            {
                return "Zip 64 End of Central Directory Record not where indicated.";
            }
        }



        /// <summary>
        /// System.IO.Compression is not supported on this platform.
        /// </summary>
        internal static string PlatformNotSupported_Compression
        {
            get
            {
                return "System.IO.Compression is not supported on this platform.";
            }
        }



        /// <summary>
        /// Invalid offset to the Zip64 End of Central Directory record.
        /// </summary>
        internal static string InvalidOffsetToZip64EOCD
        {
            get
            {
                return "Invalid offset to the Zip64 End of Central Directory record.";
            }
        }

    }
}
