
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections.Concurrent", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// CompleteAdding may not be used concurrently with additions to the collection.
        /// </summary>
        internal static string BlockingCollection_Add_ConcurrentCompleteAdd
        {
            get
            {
                return "CompleteAdding may not be used concurrently with additions to the collection.";
            }
        }



        /// <summary>
        /// The underlying collection didn't accept the item.
        /// </summary>
        internal static string BlockingCollection_Add_Failed
        {
            get
            {
                return "The underlying collection didn't accept the item.";
            }
        }



        /// <summary>
        /// At least one of the specified collections is marked as complete with regards to additions.
        /// </summary>
        internal static string BlockingCollection_CantAddAnyWhenCompleted
        {
            get
            {
                return "At least one of the specified collections is marked as complete with regards to additions.";
            }
        }



        /// <summary>
        /// All collections are marked as complete with regards to additions.
        /// </summary>
        internal static string BlockingCollection_CantTakeAnyWhenAllDone
        {
            get
            {
                return "All collections are marked as complete with regards to additions.";
            }
        }



        /// <summary>
        /// The collection argument is empty and has been marked as complete with regards to additions.
        /// </summary>
        internal static string BlockingCollection_CantTakeWhenDone
        {
            get
            {
                return "The collection argument is empty and has been marked as complete with regards to additions.";
            }
        }



        /// <summary>
        /// The collection has been marked as complete with regards to additions.
        /// </summary>
        internal static string BlockingCollection_Completed
        {
            get
            {
                return "The collection has been marked as complete with regards to additions.";
            }
        }



        /// <summary>
        /// The array argument is of the incorrect type.
        /// </summary>
        internal static string BlockingCollection_CopyTo_IncorrectType
        {
            get
            {
                return "The array argument is of the incorrect type.";
            }
        }



        /// <summary>
        /// The array argument is multidimensional.
        /// </summary>
        internal static string BlockingCollection_CopyTo_MultiDim
        {
            get
            {
                return "The array argument is multidimensional.";
            }
        }



        /// <summary>
        /// The index argument must be greater than or equal zero.
        /// </summary>
        internal static string BlockingCollection_CopyTo_NonNegative
        {
            get
            {
                return "The index argument must be greater than or equal zero.";
            }
        }



        /// <summary>
        /// The number of elements in the collection is greater than the available space from index to the end of the destination array.
        /// </summary>
        internal static string Collection_CopyTo_TooManyElems
        {
            get
            {
                return "The number of elements in the collection is greater than the available space from index to the end of the destination array.";
            }
        }



        /// <summary>
        /// The collection argument contains more items than are allowed by the boundedCapacity.
        /// </summary>
        internal static string BlockingCollection_ctor_CountMoreThanCapacity
        {
            get
            {
                return "The collection argument contains more items than are allowed by the boundedCapacity.";
            }
        }



        /// <summary>
        /// The underlying collection was modified from outside of the BlockingCollection<T>.
        /// </summary>
        internal static string BlockingCollection_Take_CollectionModified
        {
            get
            {
                return "The underlying collection was modified from outside of the BlockingCollection<T>.";
            }
        }



        /// <summary>
        /// The specified timeout must represent a value between -1 and {0}, inclusive.
        /// </summary>
        internal static string BlockingCollection_TimeoutInvalid
        {
            get
            {
                return "The specified timeout must represent a value between -1 and {0}, inclusive.";
            }
        }


        internal static string FormatBlockingCollection_TimeoutInvalid(object arg1)
        {
            return string.Format("The specified timeout must represent a value between -1 and {0}, inclusive.", arg1);
        }


        /// <summary>
        /// The collections argument contains at least one disposed element.
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_DispElems
        {
            get
            {
                return "The collections argument contains at least one disposed element.";
            }
        }



        /// <summary>
        /// The collections length is greater than the supported range.
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_LargeSize
        {
            get
            {
                return "The collections length is greater than the supported range.";
            }
        }



        /// <summary>
        /// The collections argument contains at least one null element.
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_NullElems
        {
            get
            {
                return "The collections argument contains at least one null element.";
            }
        }



        /// <summary>
        /// The collections argument is a zero-length array.
        /// </summary>
        internal static string BlockingCollection_ValidateCollectionsArray_ZeroSize
        {
            get
            {
                return "The collections argument is a zero-length array.";
            }
        }



        /// <summary>
        /// The SyncRoot property may not be used for the synchronization of concurrent collections.
        /// </summary>
        internal static string ConcurrentCollection_SyncRoot_NotSupported
        {
            get
            {
                return "The SyncRoot property may not be used for the synchronization of concurrent collections.";
            }
        }



        /// <summary>
        /// The array is multidimensional, or the type parameter for the set cannot be cast automatically to the type of the destination array.
        /// </summary>
        internal static string ConcurrentDictionary_ArrayIncorrectType
        {
            get
            {
                return "The array is multidimensional, or the type parameter for the set cannot be cast automatically to the type of the destination array.";
            }
        }



        /// <summary>
        /// The source argument contains duplicate keys.
        /// </summary>
        internal static string ConcurrentDictionary_SourceContainsDuplicateKeys
        {
            get
            {
                return "The source argument contains duplicate keys.";
            }
        }



        /// <summary>
        /// The concurrencyLevel argument must be positive, or -1 to indicate a default level.
        /// </summary>
        internal static string ConcurrentDictionary_ConcurrencyLevelMustBePositiveOrNegativeOne
        {
            get
            {
                return "The concurrencyLevel argument must be positive, or -1 to indicate a default level.";
            }
        }



        /// <summary>
        /// The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
        /// </summary>
        internal static string ConcurrentDictionary_ArrayNotLargeEnough
        {
            get
            {
                return "The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.";
            }
        }



        /// <summary>
        /// The key already existed in the dictionary.
        /// </summary>
        internal static string ConcurrentDictionary_KeyAlreadyExisted
        {
            get
            {
                return "The key already existed in the dictionary.";
            }
        }



        /// <summary>
        /// TKey is a reference type and item.Key is null.
        /// </summary>
        internal static string ConcurrentDictionary_ItemKeyIsNull
        {
            get
            {
                return "TKey is a reference type and item.Key is null.";
            }
        }



        /// <summary>
        /// The key was of an incorrect type for this dictionary.
        /// </summary>
        internal static string ConcurrentDictionary_TypeOfKeyIncorrect
        {
            get
            {
                return "The key was of an incorrect type for this dictionary.";
            }
        }



        /// <summary>
        /// The value was of an incorrect type for this dictionary.
        /// </summary>
        internal static string ConcurrentDictionary_TypeOfValueIncorrect
        {
            get
            {
                return "The value was of an incorrect type for this dictionary.";
            }
        }



        /// <summary>
        /// The sum of the startIndex and count arguments must be less than or equal to the collection's Count.
        /// </summary>
        internal static string ConcurrentStack_PushPopRange_InvalidCount
        {
            get
            {
                return "The sum of the startIndex and count arguments must be less than or equal to the collection's Count.";
            }
        }



        /// <summary>
        /// Dynamic partitions are not supported by this partitioner.
        /// </summary>
        internal static string Partitioner_DynamicPartitionsNotSupported
        {
            get
            {
                return "Dynamic partitions are not supported by this partitioner.";
            }
        }



        /// <summary>
        /// MoveNext must be called at least once before calling Current.
        /// </summary>
        internal static string PartitionerStatic_CurrentCalledBeforeMoveNext
        {
            get
            {
                return "MoveNext must be called at least once before calling Current.";
            }
        }



        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string ConcurrentBag_Enumerator_EnumerationNotStartedOrAlreadyFinished
        {
            get
            {
                return "Enumeration has either not started or has already finished.";
            }
        }



        /// <summary>
        /// The given key '{0}' was not present in the dictionary.
        /// </summary>
        internal static string Arg_KeyNotFoundWithKey
        {
            get
            {
                return "The given key '{0}' was not present in the dictionary.";
            }
        }


        internal static string FormatArg_KeyNotFoundWithKey(object arg1)
        {
            return string.Format("The given key '{0}' was not present in the dictionary.", arg1);
        }


        /// <summary>
        /// Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
        /// </summary>
        internal static string Arg_HTCapacityOverflow
        {
            get
            {
                return "Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.";
            }
        }



        /// <summary>
        /// The collection's comparer does not support the requested operation.
        /// </summary>
        internal static string InvalidOperation_IncompatibleComparer
        {
            get
            {
                return "The collection's comparer does not support the requested operation.";
            }
        }

    }
}
