
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Text.Encodings.Web", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Index was out of range. Must be non-negative and less than the size of the collection.
        /// </summary>
        internal static string ArgumentOutOfRange_IndexMustBeLess
        {
            get
            {
                return "Index was out of range. Must be non-negative and less than the size of the collection.";
            }
        }



        /// <summary>
        /// Cannot extract a Unicode scalar value from the specified index in the input.
        /// </summary>
        internal static string Argument_CannotExtractScalar
        {
            get
            {
                return "Cannot extract a Unicode scalar value from the specified index in the input.";
            }
        }



        /// <summary>
        /// Destination is too short.
        /// </summary>
        internal static string Argument_DestinationTooShort
        {
            get
            {
                return "Destination is too short.";
            }
        }



        /// <summary>
        /// Object must be of type Rune.
        /// </summary>
        internal static string Arg_MustBeRune
        {
            get
            {
                return "Object must be of type Rune.";
            }
        }



        /// <summary>
        /// TextEncoder does not implement MaxOutputCharsPerInputChar correctly.
        /// </summary>
        internal static string TextEncoderDoesNotImplementMaxOutputCharsPerInputChar
        {
            get
            {
                return "TextEncoder does not implement MaxOutputCharsPerInputChar correctly.";
            }
        }

    }
}
