
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class Resources
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Http.Abstractions", typeof(Resources).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// '{0}' is not available.
        /// </summary>
        internal static string Exception_UseMiddlewareIServiceProviderNotAvailable
        {
            get
            {
                return "'{0}' is not available.";
            }
        }


        internal static string FormatException_UseMiddlewareIServiceProviderNotAvailable(object arg1)
        {
            return string.Format("'{0}' is not available.", arg1);
        }


        /// <summary>
        /// No public '{0}' or '{1}' method found for middleware of type '{2}'.
        /// </summary>
        internal static string Exception_UseMiddlewareNoInvokeMethod
        {
            get
            {
                return "No public '{0}' or '{1}' method found for middleware of type '{2}'.";
            }
        }


        internal static string FormatException_UseMiddlewareNoInvokeMethod(object arg1, object arg2, object arg3)
        {
            return string.Format("No public '{0}' or '{1}' method found for middleware of type '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// '{0}' or '{1}' does not return an object of type '{2}'.
        /// </summary>
        internal static string Exception_UseMiddlewareNonTaskReturnType
        {
            get
            {
                return "'{0}' or '{1}' does not return an object of type '{2}'.";
            }
        }


        internal static string FormatException_UseMiddlewareNonTaskReturnType(object arg1, object arg2, object arg3)
        {
            return string.Format("'{0}' or '{1}' does not return an object of type '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The '{0}' or '{1}' method's first argument must be of type '{2}'.
        /// </summary>
        internal static string Exception_UseMiddlewareNoParameters
        {
            get
            {
                return "The '{0}' or '{1}' method's first argument must be of type '{2}'.";
            }
        }


        internal static string FormatException_UseMiddlewareNoParameters(object arg1, object arg2, object arg3)
        {
            return string.Format("The '{0}' or '{1}' method's first argument must be of type '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Multiple public '{0}' or '{1}' methods are available.
        /// </summary>
        internal static string Exception_UseMiddleMutlipleInvokes
        {
            get
            {
                return "Multiple public '{0}' or '{1}' methods are available.";
            }
        }


        internal static string FormatException_UseMiddleMutlipleInvokes(object arg1, object arg2)
        {
            return string.Format("Multiple public '{0}' or '{1}' methods are available.", arg1, arg2);
        }


        /// <summary>
        /// The path in '{0}' must start with '/'.
        /// </summary>
        internal static string Exception_PathMustStartWithSlash
        {
            get
            {
                return "The path in '{0}' must start with '/'.";
            }
        }


        internal static string FormatException_PathMustStartWithSlash(object arg1)
        {
            return string.Format("The path in '{0}' must start with '/'.", arg1);
        }


        /// <summary>
        /// Unable to resolve service for type '{0}' while attempting to Invoke middleware '{1}'.
        /// </summary>
        internal static string Exception_InvokeMiddlewareNoService
        {
            get
            {
                return "Unable to resolve service for type '{0}' while attempting to Invoke middleware '{1}'.";
            }
        }


        internal static string FormatException_InvokeMiddlewareNoService(object arg1, object arg2)
        {
            return string.Format("Unable to resolve service for type '{0}' while attempting to Invoke middleware '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The '{0}' method must not have ref or out parameters.
        /// </summary>
        internal static string Exception_InvokeDoesNotSupportRefOrOutParams
        {
            get
            {
                return "The '{0}' method must not have ref or out parameters.";
            }
        }


        internal static string FormatException_InvokeDoesNotSupportRefOrOutParams(object arg1)
        {
            return string.Format("The '{0}' method must not have ref or out parameters.", arg1);
        }


        /// <summary>
        /// The value must be greater than zero.
        /// </summary>
        internal static string Exception_PortMustBeGreaterThanZero
        {
            get
            {
                return "The value must be greater than zero.";
            }
        }



        /// <summary>
        /// No service for type '{0}' has been registered.
        /// </summary>
        internal static string Exception_UseMiddlewareNoMiddlewareFactory
        {
            get
            {
                return "No service for type '{0}' has been registered.";
            }
        }


        internal static string FormatException_UseMiddlewareNoMiddlewareFactory(object arg1)
        {
            return string.Format("No service for type '{0}' has been registered.", arg1);
        }


        /// <summary>
        /// '{0}' failed to create middleware of type '{1}'.
        /// </summary>
        internal static string Exception_UseMiddlewareUnableToCreateMiddleware
        {
            get
            {
                return "'{0}' failed to create middleware of type '{1}'.";
            }
        }


        internal static string FormatException_UseMiddlewareUnableToCreateMiddleware(object arg1, object arg2)
        {
            return string.Format("'{0}' failed to create middleware of type '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Types that implement '{0}' do not support explicit arguments.
        /// </summary>
        internal static string Exception_UseMiddlewareExplicitArgumentsNotSupported
        {
            get
            {
                return "Types that implement '{0}' do not support explicit arguments.";
            }
        }


        internal static string FormatException_UseMiddlewareExplicitArgumentsNotSupported(object arg1)
        {
            return string.Format("Types that implement '{0}' do not support explicit arguments.", arg1);
        }


        /// <summary>
        /// Argument cannot be null or empty.
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty
        {
            get
            {
                return "Argument cannot be null or empty.";
            }
        }



        /// <summary>
        /// An element with the key '{0}' already exists in the {1}.
        /// </summary>
        internal static string RouteValueDictionary_DuplicateKey
        {
            get
            {
                return "An element with the key '{0}' already exists in the {1}.";
            }
        }


        internal static string FormatRouteValueDictionary_DuplicateKey(object arg1, object arg2)
        {
            return string.Format("An element with the key '{0}' already exists in the {1}.", arg1, arg2);
        }


        /// <summary>
        /// The type '{0}' defines properties '{1}' and '{2}' which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons.
        /// </summary>
        internal static string RouteValueDictionary_DuplicatePropertyName
        {
            get
            {
                return "The type '{0}' defines properties '{1}' and '{2}' which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons.";
            }
        }


        internal static string FormatRouteValueDictionary_DuplicatePropertyName(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format("The type '{0}' defines properties '{1}' and '{2}' which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons.", arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// This service provider doesn't support keyed services.
        /// </summary>
        internal static string Exception_KeyedServicesNotSupported
        {
            get
            {
                return "This service provider doesn't support keyed services.";
            }
        }

    }

