
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Resources.Writer", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The resource writer has already been closed and cannot be edited.
        /// </summary>
        internal static string InvalidOperation_ResourceWriterSaved
        {
            get
            {
                return "The resource writer has already been closed and cannot be edited.";
            }
        }



        /// <summary>
        /// Stream was not writable.
        /// </summary>
        internal static string Argument_StreamNotWritable
        {
            get
            {
                return "Stream was not writable.";
            }
        }



        /// <summary>
        /// Stream does not support seeking.
        /// </summary>
        internal static string NotSupported_UnseekableStream
        {
            get
            {
                return "Stream does not support seeking.";
            }
        }



        /// <summary>
        /// This platform does not support binary serialized resources.
        /// </summary>
        internal static string NotSupported_BinarySerializedResources
        {
            get
            {
                return "This platform does not support binary serialized resources.";
            }
        }



        /// <summary>
        /// Stream length must be non-negative and less than 2^31 - 1 - origin.
        /// </summary>
        internal static string ArgumentOutOfRange_StreamLength
        {
            get
            {
                return "Stream length must be non-negative and less than 2^31 - 1 - origin.";
            }
        }

    }
}
