<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.AspNetCore.Components\NetJs.Microsoft.AspNetCore.Components.csproj" />
  </ItemGroup>
</Project>
