
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Extensions.FileProviders.Physical", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
        /// </summary>
        internal static string Argument_InvalidOffLen
        {
            get
            {
                return "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.";
            }
        }



        /// <summary>
        /// Non-negative number required.
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum
        {
            get
            {
                return "Non-negative number required.";
            }
        }



        /// <summary>
        /// The fileSystemWatcher parameter must be non-null when pollForChanges is false.
        /// </summary>
        internal static string Error_FileSystemWatcherRequiredWithoutPolling
        {
            get
            {
                return "The fileSystemWatcher parameter must be non-null when pollForChanges is false.";
            }
        }



        /// <summary>
        /// Cannot create a stream for a directory.
        /// </summary>
        internal static string CannotCreateStream
        {
            get
            {
                return "Cannot create a stream for a directory.";
            }
        }



        /// <summary>
        /// Cannot modify {0} once file watcher has been initialized.
        /// </summary>
        internal static string CannotModifyWhenFileWatcherInitialized
        {
            get
            {
                return "Cannot modify {0} once file watcher has been initialized.";
            }
        }


        internal static string FormatCannotModifyWhenFileWatcherInitialized(object arg1)
        {
            return string.Format("Cannot modify {0} once file watcher has been initialized.", arg1);
        }


        /// <summary>
        /// The hash algorithm name cannot be null or empty.
        /// </summary>
        internal static string Cryptography_HashAlgorithmNameNullOrEmpty
        {
            get
            {
                return "The hash algorithm name cannot be null or empty.";
            }
        }



        /// <summary>
        /// Unexpected type of FileSystemInfo
        /// </summary>
        internal static string UnexpectedFileSystemInfo
        {
            get
            {
                return "Unexpected type of FileSystemInfo";
            }
        }



        /// <summary>
        /// The type '{0}' is not supported on this platform, use polling instead.
        /// </summary>
        internal static string FileSystemWatcher_PlatformNotSupported
        {
            get
            {
                return "The type '{0}' is not supported on this platform, use polling instead.";
            }
        }


        internal static string FormatFileSystemWatcher_PlatformNotSupported(object arg1)
        {
            return string.Format("The type '{0}' is not supported on this platform, use polling instead.", arg1);
        }
    }
}
