using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace NetJs.Translator
{
    public static class ResXGenerator
    {
//        public static void GenerateStaticResource(XElement? doc, string projectName, string sourceProjectDirectory, string newProjectDirectory, string? outputResourceFileName = null)
//        {
//            var resx = Directory.EnumerateFiles(sourceProjectDirectory, "*.resx", SearchOption.AllDirectories)
//                .OrderBy(o => o.EndsWith("Strings.resx") ? 1 : int.MaxValue)
//                .GroupBy(srPath =>
//                {
//                    var className = "SR";
//                    if (Path.GetFileNameWithoutExtension(srPath) != "Strings")
//                    {
//                        className = Path.GetFileNameWithoutExtension(srPath);
//                    }
//                    return className;
//                });
//            foreach (var srPath in resx)
//            //var srPath = Path.Join(projectFolderPath, "Resources", "Strings.resx");
//            //if (File.Exists(srPath))
//            {
//                var className = srPath.Key;
//                var keyValues = srPath.SelectMany(s =>
//                {
//                    var srxml = File.ReadAllText(s);
//                    var srdoc = XElement.Parse(srxml);
//                    var keyValues = srdoc.Elements("data")
//                    .Where(r => r.Attribute("name") is not null && r.Element("value") is not null);
//                    return keyValues;
//                }).DistinctBy(e => e.Attribute("name")!.Value)
//                .ToDictionary(e => e.Attribute("name")!.Value, e => e.Element("value")!.Value)
//                .Select(kv =>
//                {
//                    int countParams = 0;
//                    for (int i = 0; i < kv.Value.Length; i++)
//                    {
//                        if (kv.Value[i] == '{')
//                        {
//                            if (kv.Value[i + 1] != '{')
//                                countParams++;
//                            else
//                                i++;
//                        }
//                    }
//                    return @$"
//        /// <summary>
//{string.Join("\r\n", kv.Value.Trim().Split(['\n']).Select(e => $"        /// {e}"))}
//        /// </summary>
//        internal static string {kv.Key}
//        {{
//            get
//            {{
//                return ResourceManager.GetString(""{kv.Key}"", resourceCulture);
//            }}
//        }}
//" + (countParams > 0 ? @$"

//        internal static string Format{kv.Key}({string.Join(", ", Enumerable.Range(1, countParams).Select(c => $"object arg{c}"))})
//        {{
//            return string.Format({kv.Key}, {string.Join(", ", Enumerable.Range(1, countParams).Select(c => $"arg{c}"))});
//        }}" : "");
//                });
//                var hasNamespace = className == "SR";
//                var SRTemplate = $@"
////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//{(hasNamespace ? $"namespace {(className == "SR" ? "System" : projectName)}" : "")}
//{(hasNamespace ? $"{{" : "")}

//    /// <summary>
//    ///   A strongly-typed resource class, for looking up localized strings, etc.
//    /// </summary>
//    // This class was auto-generated by the StronglyTypedResourceBuilder
//    // class via a tool like ResGen or Visual Studio.
//    // To add or remove a member, edit your .ResX file then rerun ResGen
//    // with the /str option, or rebuild your VS project.
//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""17.0.0.0"")]
//    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//    internal static partial class {className}
//    {{

//        private static global::System.Resources.ResourceManager s_resourceManager;

//        private static global::System.Globalization.CultureInfo resourceCulture;

//        /// <summary>
//        ///   Returns the cached ResourceManager instance used by this class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Resources.ResourceManager ResourceManager
//        {{
//            get
//            {{
//                if (object.ReferenceEquals(s_resourceManager, null))
//                {{
//                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""{projectName}"", typeof({className}).Assembly);
//                    s_resourceManager = temp;
//                }}
//                return s_resourceManager;
//            }}
//        }}

//        /// <summary>
//        ///   Overrides the current thread's CurrentUICulture property for all
//        ///   resource lookups using this strongly typed resource class.
//        /// </summary>
//        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
//        internal static global::System.Globalization.CultureInfo Culture
//        {{
//            get
//            {{
//                return resourceCulture;
//            }}
//            set
//            {{
//                resourceCulture = value;
//            }}
//        }}
//        {string.Join("\r\n\r\n", keyValues)}
//    }}
//{(hasNamespace ? $"}}" : "")}
//";
//                var sroutPath = Path.Join(newProjectDirectory, $"{outputResourceFileName ?? className}.cs");
//                File.WriteAllText(sroutPath, SRTemplate);
//                //var itemGroup = new XElement("ItemGroup");
//                //var content = new XElement("Content");
//                //content.Add(new XAttribute("Include", $"{projectFolderPathAsVariable}\\Resources\\Strings.resx"));
//                //content.Add(new XElement("GenerateSource", "true"));
//                //content.Add(new XElement("ClassName", "System.SR"));
//                //content.Add(new XElement("Generator", "ResXFileCodeGenerator"));
//                ////content.Add(new XElement("LastGenOutput", "SR.cs"));
//                //itemGroup.Add(content);
//                //doc.Add(itemGroup);
//            }
//            if (doc != null && resx.Any(e => e.Key == "SR"))
//            {
//                //Add reference to partial SR class
//                //<Compile Include="$(DotnetRuntimeRoot)src/libraries/Common/src/System/SR.cs"></Compile>
//                var itemGroup = new XElement("ItemGroup");
//                var content = new XElement("Compile");
//                content.Add(new XAttribute("Include", $"$(DotnetRuntimeRoot)src/libraries/Common/src/System/SR.cs"));
//                itemGroup.Add(content);
//                doc.Add(itemGroup);
//            }
//        }

        public static List<string> GenerateStaticResource(
            XElement? doc,
            string projectName,
            string sourceProjectDirectory,
            string? newProjectDirectory = null,
            string? outputResourceFileName = null,
            Func<string, string>? useNamespace = null)
        {
            List<string> sources = new List<string>();
            var resxs = Directory.EnumerateFiles(sourceProjectDirectory, "*.resx", SearchOption.AllDirectories)
                .OrderBy(o => o.EndsWith("Strings.resx") ? 1 : int.MaxValue)
                .GroupBy(srPath =>
                {
                    var className = "SR";
                    if (Path.GetFileNameWithoutExtension(srPath) != "Strings")
                    {
                        className = Path.GetFileNameWithoutExtension(srPath);
                    }
                    return (srPath, className);
                });
            int i = 0;
            foreach (var resx in resxs)
            //var srPath = Path.Join(projectFolderPath, "Resources", "Strings.resx");
            //if (File.Exists(srPath))
            {
                var srPath = resx.Key.srPath;
                var className = resx.Key.className;
                var keyValues = resx.SelectMany(s =>
                {
                    var srxml = File.ReadAllText(s);
                    var srdoc = XElement.Parse(srxml);
                    var keyValues = srdoc.Elements("data")
                    .Where(r => r.Attribute("name") is not null && r.Element("value") is not null);
                    return keyValues;
                }).DistinctBy(e => e.Attribute("name")!.Value)
                .ToDictionary(e => e.Attribute("name")!.Value, e => e.Element("value")!.Value)
                .Select(kv =>
                {
                    int countParams = 0;
                    for (int i = 0; i < kv.Value.Length; i++)
                    {
                        if (kv.Value[i] == '{')
                        {
                            if (kv.Value[i + 1] != '{')
                                countParams++;
                            else
                                i++;
                        }
                    }
                    return @$"
        /// <summary>
{string.Join("\r\n", kv.Value.Trim().Split(['\n']).Select(e => $"        /// {e}"))}
        /// </summary>
        internal static string {kv.Key}
        {{
            get
            {{
                return ""{(Constants.ResourceNamesInlined ? kv.Value.EscapeString() : $"ResourceManager.GetString(\"{kv.Key}\", resourceCulture)")}"";
            }}
        }}
" + (countParams > 0 ? @$"

        internal static string Format{kv.Key}({string.Join(", ", Enumerable.Range(1, countParams).Select(c => $"object arg{c}"))})
        {{
            return string.Format(""{kv.Value.EscapeString()}"", {string.Join(", ", Enumerable.Range(1, countParams).Select(c => $"arg{c}"))});
        }}" : "");
                });
                var hasNamespace = useNamespace != null || className == "SR";
                var SRTemplate = $@"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{(hasNamespace ? $"namespace {useNamespace?.Invoke(srPath) ?? (className == "SR" ? "System" : projectName)}" : "")}
{(hasNamespace ? $"{{" : "")}

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(""System.Resources.Tools.StronglyTypedResourceBuilder"", ""17.0.0.0"")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class {className}
    {{

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {{
            get
            {{
                if (object.ReferenceEquals(s_resourceManager, null))
                {{
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(""{projectName}"", typeof({className}).Assembly);
                    s_resourceManager = temp;
                }}
                return s_resourceManager;
            }}
        }}

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {{
            get
            {{
                return resourceCulture;
            }}
            set
            {{
                resourceCulture = value;
            }}
        }}
        {string.Join("\r\n\r\n", keyValues)}
    }}
{(hasNamespace ? $"}}" : "")}
";
                if (newProjectDirectory != null)
                {
                    //var oldsroutPath = Path.Join(newProjectDirectory, $"{outputResourceFileName ?? className}.g.cs");
                    //if (File.Exists(oldsroutPath))
                    //File.Delete(oldsroutPath);
                    var sroutPath = Path.Join(newProjectDirectory, $"{Path.GetFileNameWithoutExtension(srPath)}.g.cs");
                    File.WriteAllText(sroutPath, SRTemplate);
                }
                sources.Add(SRTemplate);
                //var itemGroup = new XElement("ItemGroup");
                //var content = new XElement("Content");
                //content.Add(new XAttribute("Include", $"{projectFolderPathAsVariable}\\Resources\\Strings.resx"));
                //content.Add(new XElement("GenerateSource", "true"));
                //content.Add(new XElement("ClassName", "System.SR"));
                //content.Add(new XElement("Generator", "ResXFileCodeGenerator"));
                ////content.Add(new XElement("LastGenOutput", "SR.cs"));
                //itemGroup.Add(content);
                //doc.Add(itemGroup);
                i++;
            }
            if (doc != null && resxs.Any(e => e.Key.className == "SR"))
            {
                //Add reference to partial SR class
                //<Compile Include="$(DotnetRuntimeRoot)src/libraries/Common/src/System/SR.cs"></Compile>
                var itemGroup = new XElement("ItemGroup");
                var content = new XElement("Compile");
                content.Add(new XAttribute("Include", $"$(DotnetRuntimeRoot)src/libraries/Common/src/System/SR.cs"));
                itemGroup.Add(content);
                doc.Add(itemGroup);
            }
            return sources;
        }
    }
}
