
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.Serialization.Formatters", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
        /// </summary>
        internal static string Arg_HTCapacityOverflow
        {
            get
            {
                return "Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.";
            }
        }



        /// <summary>
        /// Type '{0}' in Assembly '{1}' is not marked as serializable.
        /// </summary>
        internal static string Serialization_NonSerType
        {
            get
            {
                return "Type '{0}' in Assembly '{1}' is not marked as serializable.";
            }
        }


        internal static string FormatSerialization_NonSerType(object arg1, object arg2)
        {
            return string.Format("Type '{0}' in Assembly '{1}' is not marked as serializable.", arg1, arg2);
        }


        /// <summary>
        /// Parameters 'members' and 'data' must have the same length.
        /// </summary>
        internal static string Argument_DataLengthDifferent
        {
            get
            {
                return "Parameters 'members' and 'data' must have the same length.";
            }
        }



        /// <summary>
        /// Member at position {0} was null.
        /// </summary>
        internal static string ArgumentNull_NullMember
        {
            get
            {
                return "Member at position {0} was null.";
            }
        }


        internal static string FormatArgumentNull_NullMember(object arg1)
        {
            return string.Format("Member at position {0} was null.", arg1);
        }


        /// <summary>
        /// Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized.
        /// </summary>
        internal static string Serialization_UnknownMemberInfo
        {
            get
            {
                return "Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized.";
            }
        }



        /// <summary>
        /// Object has never been assigned an objectID.
        /// </summary>
        internal static string Serialization_NoID
        {
            get
            {
                return "Object has never been assigned an objectID.";
            }
        }



        /// <summary>
        /// The internal array cannot expand to greater than Int32.MaxValue elements.
        /// </summary>
        internal static string Serialization_TooManyElements
        {
            get
            {
                return "The internal array cannot expand to greater than Int32.MaxValue elements.";
            }
        }



        /// <summary>
        /// The FieldInfo object is not valid.
        /// </summary>
        internal static string Argument_InvalidFieldInfo
        {
            get
            {
                return "The FieldInfo object is not valid.";
            }
        }



        /// <summary>
        /// A fixup is registered to the object with ID {0}, but the object does not appear in the graph.
        /// </summary>
        internal static string Serialization_NeverSeen
        {
            get
            {
                return "A fixup is registered to the object with ID {0}, but the object does not appear in the graph.";
            }
        }


        internal static string FormatSerialization_NeverSeen(object arg1)
        {
            return string.Format("A fixup is registered to the object with ID {0}, but the object does not appear in the graph.", arg1);
        }


        /// <summary>
        /// The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.
        /// </summary>
        internal static string Serialization_IORIncomplete
        {
            get
            {
                return "The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.";
            }
        }


        internal static string FormatSerialization_IORIncomplete(object arg1)
        {
            return string.Format("The object with ID {0} implements the IObjectReference interface for which all dependencies cannot be resolved. The likely cause is two instances of IObjectReference that have a mutual dependency on each other.", arg1);
        }


        /// <summary>
        /// The object with ID {0} was referenced in a fixup but does not exist.
        /// </summary>
        internal static string Serialization_ObjectNotSupplied
        {
            get
            {
                return "The object with ID {0} was referenced in a fixup but does not exist.";
            }
        }


        internal static string FormatSerialization_ObjectNotSupplied(object arg1)
        {
            return string.Format("The object with ID {0} was referenced in a fixup but does not exist.", arg1);
        }


        /// <summary>
        /// {0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.
        /// </summary>
        internal static string Serialization_NotCyclicallyReferenceableSurrogate
        {
            get
            {
                return "{0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.";
            }
        }


        internal static string FormatSerialization_NotCyclicallyReferenceableSurrogate(object arg1)
        {
            return string.Format("{0}.SetObjectData returns a value that is neither null nor equal to the first parameter. Such Surrogates cannot be part of cyclical reference.", arg1);
        }


        /// <summary>
        /// The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference.
        /// </summary>
        internal static string Serialization_TooManyReferences
        {
            get
            {
                return "The implementation of the IObjectReference interface returns too many nested references to other objects that implement IObjectReference.";
            }
        }



        /// <summary>
        /// The object with ID {0} was referenced in a fixup but has not been registered.
        /// </summary>
        internal static string Serialization_MissingObject
        {
            get
            {
                return "The object with ID {0} was referenced in a fixup but has not been registered.";
            }
        }


        internal static string FormatSerialization_MissingObject(object arg1)
        {
            return string.Format("The object with ID {0} was referenced in a fixup but has not been registered.", arg1);
        }


        /// <summary>
        /// A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available.
        /// </summary>
        internal static string Serialization_InvalidFixupDiscovered
        {
            get
            {
                return "A fixup on an object implementing ISerializable or having a surrogate was discovered for an object which does not have a SerializationInfo available.";
            }
        }



        /// <summary>
        /// Unable to load type {0} required for deserialization.
        /// </summary>
        internal static string Serialization_TypeLoadFailure
        {
            get
            {
                return "Unable to load type {0} required for deserialization.";
            }
        }


        internal static string FormatSerialization_TypeLoadFailure(object arg1)
        {
            return string.Format("Unable to load type {0} required for deserialization.", arg1);
        }


        /// <summary>
        /// ValueType fixup on Arrays is not implemented.
        /// </summary>
        internal static string Serialization_ValueTypeFixup
        {
            get
            {
                return "ValueType fixup on Arrays is not implemented.";
            }
        }



        /// <summary>
        /// Fixing up a partially available ValueType chain is not implemented.
        /// </summary>
        internal static string Serialization_PartialValueTypeFixup
        {
            get
            {
                return "Fixing up a partially available ValueType chain is not implemented.";
            }
        }



        /// <summary>
        /// Cannot perform fixup.
        /// </summary>
        internal static string Serialization_UnableToFixup
        {
            get
            {
                return "Cannot perform fixup.";
            }
        }



        /// <summary>
        /// objectID cannot be less than or equal to zero.
        /// </summary>
        internal static string ArgumentOutOfRange_ObjectID
        {
            get
            {
                return "objectID cannot be less than or equal to zero.";
            }
        }



        /// <summary>
        /// An object cannot be registered twice.
        /// </summary>
        internal static string Serialization_RegisterTwice
        {
            get
            {
                return "An object cannot be registered twice.";
            }
        }



        /// <summary>
        /// The given object does not implement the ISerializable interface.
        /// </summary>
        internal static string Serialization_NotISer
        {
            get
            {
                return "The given object does not implement the ISerializable interface.";
            }
        }



        /// <summary>
        /// The constructor to deserialize an object of type '{0}' was not found.
        /// </summary>
        internal static string Serialization_ConstructorNotFound
        {
            get
            {
                return "The constructor to deserialize an object of type '{0}' was not found.";
            }
        }


        internal static string FormatSerialization_ConstructorNotFound(object arg1)
        {
            return string.Format("The constructor to deserialize an object of type '{0}' was not found.", arg1);
        }


        /// <summary>
        /// The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.
        /// </summary>
        internal static string Serialization_IncorrectNumberOfFixups
        {
            get
            {
                return "The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.";
            }
        }



        /// <summary>
        /// A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used.
        /// </summary>
        internal static string Serialization_InvalidFixupType
        {
            get
            {
                return "A member fixup was registered for an object which implements ISerializable or has a surrogate. In this situation, a delayed fixup must be used.";
            }
        }



        /// <summary>
        /// Object IDs must be greater than zero.
        /// </summary>
        internal static string Serialization_IdTooSmall
        {
            get
            {
                return "Object IDs must be greater than zero.";
            }
        }



        /// <summary>
        /// The ID of the containing object cannot be the same as the object ID.
        /// </summary>
        internal static string Serialization_ParentChildIdentical
        {
            get
            {
                return "The ID of the containing object cannot be the same as the object ID.";
            }
        }



        /// <summary>
        /// Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.
        /// </summary>
        internal static string Serialization_InvalidType
        {
            get
            {
                return "Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.";
            }
        }


        internal static string FormatSerialization_InvalidType(object arg1)
        {
            return string.Format("Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.", arg1);
        }


        /// <summary>
        /// When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied.
        /// </summary>
        internal static string Argument_MustSupplyParent
        {
            get
            {
                return "When supplying the ID of a containing object, the FieldInfo that identifies the current field within that object must also be supplied.";
            }
        }



        /// <summary>
        /// Cannot supply both a MemberInfo and an Array to indicate the parent of a value type.
        /// </summary>
        internal static string Argument_MemberAndArray
        {
            get
            {
                return "Cannot supply both a MemberInfo and an Array to indicate the parent of a value type.";
            }
        }



        /// <summary>
        /// Invalid BinaryFormatter stream.
        /// </summary>
        internal static string Serialization_CorruptedStream
        {
            get
            {
                return "Invalid BinaryFormatter stream.";
            }
        }



        /// <summary>
        /// Attempting to deserialize an empty stream.
        /// </summary>
        internal static string Serialization_Stream
        {
            get
            {
                return "Attempting to deserialize an empty stream.";
            }
        }



        /// <summary>
        /// Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
        /// </summary>
        internal static string Serialization_BinaryHeader
        {
            get
            {
                return "Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.";
            }
        }


        internal static string FormatSerialization_BinaryHeader(object arg1)
        {
            return string.Format("Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.", arg1);
        }


        /// <summary>
        /// Invalid expected type.
        /// </summary>
        internal static string Serialization_TypeExpected
        {
            get
            {
                return "Invalid expected type.";
            }
        }



        /// <summary>
        /// End of Stream encountered before parsing was completed.
        /// </summary>
        internal static string Serialization_StreamEnd
        {
            get
            {
                return "End of Stream encountered before parsing was completed.";
            }
        }



        /// <summary>
        /// Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.
        /// </summary>
        internal static string Serialization_CrossAppDomainError
        {
            get
            {
                return "Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.";
            }
        }


        internal static string FormatSerialization_CrossAppDomainError(object arg1, object arg2)
        {
            return string.Format("Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// No map for object '{0}'.
        /// </summary>
        internal static string Serialization_Map
        {
            get
            {
                return "No map for object '{0}'.";
            }
        }


        internal static string FormatSerialization_Map(object arg1)
        {
            return string.Format("No map for object '{0}'.", arg1);
        }


        /// <summary>
        /// No assembly information is available for object on the wire, '{0}'.
        /// </summary>
        internal static string Serialization_Assembly
        {
            get
            {
                return "No assembly information is available for object on the wire, '{0}'.";
            }
        }


        internal static string FormatSerialization_Assembly(object arg1)
        {
            return string.Format("No assembly information is available for object on the wire, '{0}'.", arg1);
        }


        /// <summary>
        /// Invalid ObjectTypeEnum {0}.
        /// </summary>
        internal static string Serialization_ObjectTypeEnum
        {
            get
            {
                return "Invalid ObjectTypeEnum {0}.";
            }
        }


        internal static string FormatSerialization_ObjectTypeEnum(object arg1)
        {
            return string.Format("Invalid ObjectTypeEnum {0}.", arg1);
        }


        /// <summary>
        /// No assembly ID for object type '{0}'.
        /// </summary>
        internal static string Serialization_AssemblyId
        {
            get
            {
                return "No assembly ID for object type '{0}'.";
            }
        }


        internal static string FormatSerialization_AssemblyId(object arg1)
        {
            return string.Format("No assembly ID for object type '{0}'.", arg1);
        }


        /// <summary>
        /// Invalid array type '{0}'.
        /// </summary>
        internal static string Serialization_ArrayType
        {
            get
            {
                return "Invalid array type '{0}'.";
            }
        }


        internal static string FormatSerialization_ArrayType(object arg1)
        {
            return string.Format("Invalid array type '{0}'.", arg1);
        }


        /// <summary>
        /// Invalid type code in stream '{0}'.
        /// </summary>
        internal static string Serialization_TypeCode
        {
            get
            {
                return "Invalid type code in stream '{0}'.";
            }
        }


        internal static string FormatSerialization_TypeCode(object arg1)
        {
            return string.Format("Invalid type code in stream '{0}'.", arg1);
        }


        /// <summary>
        /// Invalid write type request '{0}'.
        /// </summary>
        internal static string Serialization_TypeWrite
        {
            get
            {
                return "Invalid write type request '{0}'.";
            }
        }


        internal static string FormatSerialization_TypeWrite(object arg1)
        {
            return string.Format("Invalid write type request '{0}'.", arg1);
        }


        /// <summary>
        /// Invalid read type request '{0}'.
        /// </summary>
        internal static string Serialization_TypeRead
        {
            get
            {
                return "Invalid read type request '{0}'.";
            }
        }


        internal static string FormatSerialization_TypeRead(object arg1)
        {
            return string.Format("Invalid read type request '{0}'.", arg1);
        }


        /// <summary>
        /// Unable to find assembly '{0}'.
        /// </summary>
        internal static string Serialization_AssemblyNotFound
        {
            get
            {
                return "Unable to find assembly '{0}'.";
            }
        }


        internal static string FormatSerialization_AssemblyNotFound(object arg1)
        {
            return string.Format("Unable to find assembly '{0}'.", arg1);
        }


        /// <summary>
        /// The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...
        /// </summary>
        internal static string Serialization_InvalidFormat
        {
            get
            {
                return "The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...";
            }
        }


        internal static string FormatSerialization_InvalidFormat(object arg1)
        {
            return string.Format("The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...", arg1);
        }


        /// <summary>
        /// No top object.
        /// </summary>
        internal static string Serialization_TopObject
        {
            get
            {
                return "No top object.";
            }
        }



        /// <summary>
        /// Invalid element '{0}'.
        /// </summary>
        internal static string Serialization_XMLElement
        {
            get
            {
                return "Invalid element '{0}'.";
            }
        }


        internal static string FormatSerialization_XMLElement(object arg1)
        {
            return string.Format("Invalid element '{0}'.", arg1);
        }


        /// <summary>
        /// Top object cannot be instantiated for element '{0}'.
        /// </summary>
        internal static string Serialization_TopObjectInstantiate
        {
            get
            {
                return "Top object cannot be instantiated for element '{0}'.";
            }
        }


        internal static string FormatSerialization_TopObjectInstantiate(object arg1)
        {
            return string.Format("Top object cannot be instantiated for element '{0}'.", arg1);
        }


        /// <summary>
        /// Array element type is Object, 'dt' attribute is null.
        /// </summary>
        internal static string Serialization_ArrayTypeObject
        {
            get
            {
                return "Array element type is Object, 'dt' attribute is null.";
            }
        }



        /// <summary>
        /// Type is missing for member of type Object '{0}'.
        /// </summary>
        internal static string Serialization_TypeMissing
        {
            get
            {
                return "Type is missing for member of type Object '{0}'.";
            }
        }


        internal static string FormatSerialization_TypeMissing(object arg1)
        {
            return string.Format("Type is missing for member of type Object '{0}'.", arg1);
        }


        /// <summary>
        /// Object {0} has never been assigned an objectID.
        /// </summary>
        internal static string Serialization_ObjNoID
        {
            get
            {
                return "Object {0} has never been assigned an objectID.";
            }
        }


        internal static string FormatSerialization_ObjNoID(object arg1)
        {
            return string.Format("Object {0} has never been assigned an objectID.", arg1);
        }


        /// <summary>
        /// MemberInfo type {0} cannot be serialized.
        /// </summary>
        internal static string Serialization_SerMemberInfo
        {
            get
            {
                return "MemberInfo type {0} cannot be serialized.";
            }
        }


        internal static string FormatSerialization_SerMemberInfo(object arg1)
        {
            return string.Format("MemberInfo type {0} cannot be serialized.", arg1);
        }


        /// <summary>
        /// When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied.
        /// </summary>
        internal static string Argument_MustSupplyContainer
        {
            get
            {
                return "When supplying a FieldInfo for fixing up a nested type, a valid ID for that containing object must also be supplied.";
            }
        }



        /// <summary>
        /// Parse error. Current element is not compatible with the next element, {0}.
        /// </summary>
        internal static string Serialization_ParseError
        {
            get
            {
                return "Parse error. Current element is not compatible with the next element, {0}.";
            }
        }


        internal static string FormatSerialization_ParseError(object arg1)
        {
            return string.Format("Parse error. Current element is not compatible with the next element, {0}.", arg1);
        }


        /// <summary>
        /// MemberInfo requested for ISerializable type.
        /// </summary>
        internal static string Serialization_ISerializableMemberInfo
        {
            get
            {
                return "MemberInfo requested for ISerializable type.";
            }
        }



        /// <summary>
        /// MemberInfo cannot be obtained for ISerialized Object '{0}'.
        /// </summary>
        internal static string Serialization_MemberInfo
        {
            get
            {
                return "MemberInfo cannot be obtained for ISerialized Object '{0}'.";
            }
        }


        internal static string FormatSerialization_MemberInfo(object arg1)
        {
            return string.Format("MemberInfo cannot be obtained for ISerialized Object '{0}'.", arg1);
        }


        /// <summary>
        /// Types not available for ISerializable object '{0}'.
        /// </summary>
        internal static string Serialization_ISerializableTypes
        {
            get
            {
                return "Types not available for ISerializable object '{0}'.";
            }
        }


        internal static string FormatSerialization_ISerializableTypes(object arg1)
        {
            return string.Format("Types not available for ISerializable object '{0}'.", arg1);
        }


        /// <summary>
        /// Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.
        /// </summary>
        internal static string Serialization_MissingMember
        {
            get
            {
                return "Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.";
            }
        }


        internal static string FormatSerialization_MissingMember(object arg1, object arg2, object arg3)
        {
            return string.Format("Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// No MemberInfo for Object {0}.
        /// </summary>
        internal static string Serialization_NoMemberInfo
        {
            get
            {
                return "No MemberInfo for Object {0}.";
            }
        }


        internal static string FormatSerialization_NoMemberInfo(object arg1)
        {
            return string.Format("No MemberInfo for Object {0}.", arg1);
        }


        /// <summary>
        /// Selector contained a cycle.
        /// </summary>
        internal static string Serialization_SurrogateCycleInArgument
        {
            get
            {
                return "Selector contained a cycle.";
            }
        }



        /// <summary>
        /// Adding selector will introduce a cycle.
        /// </summary>
        internal static string Serialization_SurrogateCycle
        {
            get
            {
                return "Adding selector will introduce a cycle.";
            }
        }



        /// <summary>
        /// Unable to read beyond the end of the stream.
        /// </summary>
        internal static string IO_EOF_ReadBeyondEOF
        {
            get
            {
                return "Unable to read beyond the end of the stream.";
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_SerializationDisallowed
        {
            get
            {
                return "BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.";
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization are not supported on this platform. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_SerializationNotSupportedOnThisPlatform
        {
            get
            {
                return "BinaryFormatter serialization and deserialization are not supported on this platform. See https://aka.ms/binaryformatter for more information.";
            }
        }



        /// <summary>
        /// BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.
        /// </summary>
        internal static string BinaryFormatter_Removed
        {
            get
            {
                return "BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.";
            }
        }

    }
}
