
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reflection.Emit", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Cannot populate assembly metadata multiple times.
        /// </summary>
        internal static string InvalidOperation_CannotPopulateMultipleTimes
        {
            get
            {
                return "Cannot populate assembly metadata multiple times.";
            }
        }



        /// <summary>
        /// Cannot set parent to an interface.
        /// </summary>
        internal static string Argument_CannotSetParentToInterface
        {
            get
            {
                return "Cannot set parent to an interface.";
            }
        }



        /// <summary>
        /// Interface must be declared abstract.
        /// </summary>
        internal static string InvalidOperation_BadInterfaceNotAbstract
        {
            get
            {
                return "Interface must be declared abstract.";
            }
        }



        /// <summary>
        /// Assembly needs at least one module defined.
        /// </summary>
        internal static string InvalidOperation_AModuleRequired
        {
            get
            {
                return "Assembly needs at least one module defined.";
            }
        }



        /// <summary>
        /// You cannot have more than one dynamic module in each dynamic assembly in this version of the runtime.
        /// </summary>
        internal static string InvalidOperation_NoMultiModuleAssembly
        {
            get
            {
                return "You cannot have more than one dynamic module in each dynamic assembly in this version of the runtime.";
            }
        }



        /// <summary>
        /// The invoked member is not supported in a dynamic module.
        /// </summary>
        internal static string NotSupported_DynamicModule
        {
            get
            {
                return "The invoked member is not supported in a dynamic module.";
            }
        }



        /// <summary>
        /// The type code may not be used as a type argument of a custom attribute.
        /// </summary>
        internal static string Argument_InvalidTypeCodeForTypeArgument
        {
            get
            {
                return "The type code may not be used as a type argument of a custom attribute.";
            }
        }



        /// <summary>
        /// 'UnmanagedType.{0}' named parameter is only valid for fields.
        /// </summary>
        internal static string NotSupported_UnmanagedTypeOnlyForFields
        {
            get
            {
                return " 'UnmanagedType.{0}' named parameter is only valid for fields.";
            }
        }


        internal static string FormatNotSupported_UnmanagedTypeOnlyForFields(object arg1)
        {
            return string.Format(" 'UnmanagedType.{0}' named parameter is only valid for fields.", arg1);
        }


        /// <summary>
        /// Custom attribute '{0}' data length is only '{1}'.
        /// </summary>
        internal static string Argument_InvalidCustomAttributeLength
        {
            get
            {
                return "Custom attribute '{0}' data length is only '{1}'.";
            }
        }


        internal static string FormatArgument_InvalidCustomAttributeLength(object arg1, object arg2)
        {
            return string.Format("Custom attribute '{0}' data length is only '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Custom attribute '{0}' prolog invalid.
        /// </summary>
        internal static string Argument_InvalidProlog
        {
            get
            {
                return "Custom attribute '{0}' prolog invalid.";
            }
        }


        internal static string FormatArgument_InvalidProlog(object arg1)
        {
            return string.Format("Custom attribute '{0}' prolog invalid.", arg1);
        }


        /// <summary>
        /// Custom attribute '{0}' has unknown named type '{1}'.
        /// </summary>
        internal static string Argument_UnknownNamedType
        {
            get
            {
                return "Custom attribute '{0}' has unknown named type '{1}'.";
            }
        }


        internal static string FormatArgument_UnknownNamedType(object arg1, object arg2)
        {
            return string.Format("Custom attribute '{0}' has unknown named type '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Type '{0}' not handled in the custom attribute value decoder.
        /// </summary>
        internal static string NotImplemented_TypeForValue
        {
            get
            {
                return "Type '{0}' not handled in the custom attribute value decoder.";
            }
        }


        internal static string FormatNotImplemented_TypeForValue(object arg1)
        {
            return string.Format("Type '{0}' not handled in the custom attribute value decoder.", arg1);
        }


        /// <summary>
        /// DllName cannot be empty.
        /// </summary>
        internal static string Argument_DllNameCannotBeEmpty
        {
            get
            {
                return "DllName cannot be empty.";
            }
        }



        /// <summary>
        /// The specified parameter index is not in range.
        /// </summary>
        internal static string ArgumentOutOfRange_ParamSequence
        {
            get
            {
                return "The specified parameter index is not in range.";
            }
        }



        /// <summary>
        /// Invalid constructor argument {0} provided for MarshalAs attribute.
        /// </summary>
        internal static string Argument_InvalidArgumentForAttribute
        {
            get
            {
                return "Invalid constructor argument {0} provided for MarshalAs attribute.";
            }
        }


        internal static string FormatArgument_InvalidArgumentForAttribute(object arg1)
        {
            return string.Format("Invalid constructor argument {0} provided for MarshalAs attribute.", arg1);
        }


        /// <summary>
        /// Named parameter {0} is not valid for UnmanagedType.{1} type.
        /// </summary>
        internal static string Argument_InvalidParameterForUnmanagedType
        {
            get
            {
                return "Named parameter {0} is not valid for UnmanagedType.{1} type.";
            }
        }


        internal static string FormatArgument_InvalidParameterForUnmanagedType(object arg1, object arg2)
        {
            return string.Format("Named parameter {0} is not valid for UnmanagedType.{1} type.", arg1, arg2);
        }


        /// <summary>
        /// SizeConst parameter must be specified for UnmanagedType.ByValTStr type.
        /// </summary>
        internal static string Argument_SizeConstMustBeSpecified
        {
            get
            {
                return "SizeConst parameter must be specified for UnmanagedType.ByValTStr type.";
            }
        }



        /// <summary>
        /// The generic parameters are already defined on this MethodBuilder.
        /// </summary>
        internal static string InvalidOperation_GenericParametersAlreadySet
        {
            get
            {
                return "The generic parameters are already defined on this MethodBuilder.";
            }
        }



        /// <summary>
        /// Should only set visibility flags when creating EnumBuilder.
        /// </summary>
        internal static string Argument_ShouldOnlySetVisibilityFlags
        {
            get
            {
                return "Should only set visibility flags when creating EnumBuilder.";
            }
        }



        /// <summary>
        /// Constant does not match the defined type.
        /// </summary>
        internal static string Argument_ConstantDoesntMatch
        {
            get
            {
                return "Constant does not match the defined type.";
            }
        }



        /// <summary>
        /// Null is not a valid constant value for this type.
        /// </summary>
        internal static string Argument_ConstantNull
        {
            get
            {
                return "Null is not a valid constant value for this type.";
            }
        }



        /// <summary>
        /// Underlying type information on enumeration is not specified.
        /// </summary>
        internal static string InvalidOperation_NoUnderlyingTypeOnEnum
        {
            get
            {
                return "Underlying type information on enumeration is not specified.";
            }
        }



        /// <summary>
        /// Method body should not exist.
        /// </summary>
        internal static string InvalidOperation_ShouldNotHaveMethodBody
        {
            get
            {
                return "Method body should not exist.";
            }
        }



        /// <summary>
        /// Interface cannot have constructors.
        /// </summary>
        internal static string InvalidOperation_ConstructorNotAllowedOnInterface
        {
            get
            {
                return "Interface cannot have constructors.";
            }
        }



        /// <summary>
        /// Local passed in does not belong to this ILGenerator.
        /// </summary>
        internal static string Argument_UnmatchedMethodForLocal
        {
            get
            {
                return "Local passed in does not belong to this ILGenerator.";
            }
        }



        /// <summary>
        /// Invalid Label.
        /// </summary>
        internal static string Argument_InvalidLabel
        {
            get
            {
                return "Invalid Label.";
            }
        }



        /// <summary>
        /// Only 'OpCode.Switch' can be used.
        /// </summary>
        internal static string Argument_MustBeSwitchOpCode
        {
            get
            {
                return "Only 'OpCode.Switch' can be used.";
            }
        }



        /// <summary>
        /// The specified opcode cannot be passed to EmitCall.
        /// </summary>
        internal static string Argument_NotMethodCallOpcode
        {
            get
            {
                return "The specified opcode cannot be passed to EmitCall.";
            }
        }



        /// <summary>
        /// Unable to access ILGenerator on a constructor created with DefineDefaultConstructor.
        /// </summary>
        internal static string InvalidOperation_DefaultConstructorILGen
        {
            get
            {
                return "Unable to access ILGenerator on a constructor created with DefineDefaultConstructor.";
            }
        }



        /// <summary>
        /// Parent does not have a default constructor. The default constructor must be explicitly defined.
        /// </summary>
        internal static string NotSupported_NoParentDefaultConstructor
        {
            get
            {
                return "Parent does not have a default constructor. The default constructor must be explicitly defined.";
            }
        }



        /// <summary>
        /// Unable to change after type has been created.
        /// </summary>
        internal static string InvalidOperation_TypeHasBeenCreated
        {
            get
            {
                return "Unable to change after type has been created.";
            }
        }



        /// <summary>
        /// The invoked member is not supported before the type is created.
        /// </summary>
        internal static string NotSupported_TypeNotYetCreated
        {
            get
            {
                return "The invoked member is not supported before the type is created.";
            }
        }



        /// <summary>
        /// Method cannot be both static and virtual.
        /// </summary>
        internal static string Argument_NoStaticVirtual
        {
            get
            {
                return "Method cannot be both static and virtual.";
            }
        }



        /// <summary>
        /// Incorrect code generation for exception block.
        /// </summary>
        internal static string Argument_BadExceptionCodeGen
        {
            get
            {
                return "Incorrect code generation for exception block.";
            }
        }



        /// <summary>
        /// Not currently in an exception block.
        /// </summary>
        internal static string Argument_NotInExceptionBlock
        {
            get
            {
                return "Not currently in an exception block.";
            }
        }



        /// <summary>
        /// Should not specify exception type for catch clause for filter block.
        /// </summary>
        internal static string Argument_ShouldNotSpecifyExceptionType
        {
            get
            {
                return "Should not specify exception type for catch clause for filter block.";
            }
        }



        /// <summary>
        /// {0} is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.
        /// </summary>
        internal static string Arg_NotGenericMethodDefinition
        {
            get
            {
                return "{0} is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.";
            }
        }


        internal static string FormatArg_NotGenericMethodDefinition(object arg1)
        {
            return string.Format("{0} is not a GenericMethodDefinition. MakeGenericMethod may only be called on a method for which MethodBase.IsGenericMethodDefinition is true.", arg1);
        }


        /// <summary>
        /// Calling convention must be VarArgs.
        /// </summary>
        internal static string InvalidOperation_NotAVarArgCallingConvention
        {
            get
            {
                return "Calling convention must be VarArgs.";
            }
        }



        /// <summary>
        /// MethodOverride's body must be from this type.
        /// </summary>
        internal static string ArgumentException_BadMethodImplBody
        {
            get
            {
                return "MethodOverride's body must be from this type.";
            }
        }



        /// <summary>
        /// Method must be called on a Type for which Type.IsGenericParameter is false.
        /// </summary>
        internal static string Argument_GenericParameter
        {
            get
            {
                return "Method must be called on a Type for which Type.IsGenericParameter is false.";
            }
        }



        /// <summary>
        /// Type '{0}' tried to override method '{1}' but does not implement or inherit that method.
        /// </summary>
        internal static string Argument_InvalidMethodOverride
        {
            get
            {
                return "Type '{0}' tried to override method '{1}' but does not implement or inherit that method.";
            }
        }


        internal static string FormatArgument_InvalidMethodOverride(object arg1, object arg2)
        {
            return string.Format("Type '{0}' tried to override method '{1}' but does not implement or inherit that method.", arg1, arg2);
        }


        /// <summary>
        /// Interface not found.
        /// </summary>
        internal static string Argument_InterfaceNotFound
        {
            get
            {
                return "Interface not found.";
            }
        }



        /// <summary>
        /// Method '{0}' on type '{1}' is overriding a method that has been overridden.
        /// </summary>
        internal static string Argument_MethodOverridden
        {
            get
            {
                return "Method '{0}' on type '{1}' is overriding a method that has been overridden.";
            }
        }


        internal static string FormatArgument_MethodOverridden(object arg1, object arg2)
        {
            return string.Format("Method '{0}' on type '{1}' is overriding a method that has been overridden.", arg1, arg2);
        }


        /// <summary>
        /// Type passed must be an interface.
        /// </summary>
        internal static string Argument_MustBeInterface
        {
            get
            {
                return "Type passed must be an interface.";
            }
        }



        /// <summary>
        /// Method '{0}' cannot have a method body
        /// </summary>
        internal static string InvalidOperation_BadMethodBody
        {
            get
            {
                return "Method '{0}' cannot have a method body";
            }
        }


        internal static string FormatInvalidOperation_BadMethodBody(object arg1)
        {
            return string.Format("Method '{0}' cannot have a method body", arg1);
        }


        /// <summary>
        /// Type must be declared abstract if any of its methods are abstract.
        /// </summary>
        internal static string InvalidOperation_BadTypeAttributesNotAbstract
        {
            get
            {
                return "Type must be declared abstract if any of its methods are abstract.";
            }
        }



        /// <summary>
        /// Ambiguous match found for '{0} {1}'
        /// </summary>
        internal static string AmbiguousMatch_MemberInfo
        {
            get
            {
                return "Ambiguous match found for '{0} {1}'";
            }
        }


        internal static string FormatAmbiguousMatch_MemberInfo(object arg1, object arg2)
        {
            return string.Format("Ambiguous match found for '{0} {1}'", arg1, arg2);
        }


        /// <summary>
        /// Label defined multiple times.
        /// </summary>
        internal static string Argument_RedefinedLabel
        {
            get
            {
                return "Label defined multiple times.";
            }
        }



        /// <summary>
        /// PInvoke methods must be static and native and cannot be abstract.
        /// </summary>
        internal static string Argument_BadPInvokeMethod
        {
            get
            {
                return "PInvoke methods must be static and native and cannot be abstract.";
            }
        }



        /// <summary>
        /// PInvoke methods cannot exist on interfaces.
        /// </summary>
        internal static string Argument_BadPInvokeOnInterface
        {
            get
            {
                return "PInvoke methods cannot exist on interfaces.";
            }
        }



        /// <summary>
        /// Method has been already defined.
        /// </summary>
        internal static string Argument_MethodRedefined
        {
            get
            {
                return "Method has been already defined.";
            }
        }



        /// <summary>
        /// Global members must be static.
        /// </summary>
        internal static string Argument_GlobalMembersMustBeStatic
        {
            get
            {
                return "Global members must be static.";
            }
        }



        /// <summary>
        /// Type definition of the global function has been completed.
        /// </summary>
        internal static string InvalidOperation_GlobalsHaveBeenCreated
        {
            get
            {
                return "Type definition of the global function has been completed.";
            }
        }



        /// <summary>
        /// Data size must be &gt; 1 and &lt; 0x3f0000.
        /// </summary>
        internal static string Argument_BadSizeForData
        {
            get
            {
                return "Data size must be &gt; 1 and &lt; 0x3f0000.";
            }
        }



        /// <summary>
        /// MetadataToken for the member is not generated until the assembly saved.
        /// </summary>
        internal static string InvalidOperation_TokenNotPopulated
        {
            get
            {
                return "MetadataToken for the member is not generated until the assembly saved.";
            }
        }



        /// <summary>
        /// Incorrect signature format.
        /// </summary>
        internal static string Argument_BadSigFormat
        {
            get
            {
                return "Incorrect signature format.";
            }
        }



        /// <summary>
        /// Must be an array type.
        /// </summary>
        internal static string Argument_HasToBeArrayClass
        {
            get
            {
                return "Must be an array type.";
            }
        }



        /// <summary>
        /// Not supported in a non-reflected type.
        /// </summary>
        internal static string NotSupported_NonReflectedType
        {
            get
            {
                return "Not supported in a non-reflected type.";
            }
        }



        /// <summary>
        /// Not supported in an array method of a type definition that is not complete.
        /// </summary>
        internal static string NotSupported_SymbolMethod
        {
            get
            {
                return "Not supported in an array method of a type definition that is not complete.";
            }
        }



        /// <summary>
        /// Invalid source document.
        /// </summary>
        internal static string InvalidOperation_InvalidDocument
        {
            get
            {
                return "Invalid source document.";
            }
        }



        /// <summary>
        /// Unmatching symbol scope.
        /// </summary>
        internal static string InvalidOperation_UnmatchingSymScope
        {
            get
            {
                return "Unmatching symbol scope.";
            }
        }



        /// <summary>
        /// Type provided must be an Enum.
        /// </summary>
        internal static string Argument_MustBeEnum
        {
            get
            {
                return "Type provided must be an Enum.";
            }
        }

    }
}
