
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.ComponentModel.Annotations", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// The {0} field does not equal any of the values specified in AllowedValuesAttribute.
        /// </summary>
        internal static string AllowedValuesAttribute_Invalid
        {
            get
            {
                return "The {0} field does not equal any of the values specified in AllowedValuesAttribute.";
            }
        }


        internal static string FormatAllowedValuesAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field does not equal any of the values specified in AllowedValuesAttribute.", arg1);
        }


        /// <summary>
        /// The associated metadata type for type '{0}' contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type.
        /// </summary>
        internal static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties
        {
            get
            {
                return "The associated metadata type for type '{0}' contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type.";
            }
        }


        internal static string FormatAssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties(object arg1, object arg2)
        {
            return string.Format("The associated metadata type for type '{0}' contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type.", arg1, arg2);
        }


        /// <summary>
        /// The type '{0}' does not contain a public property named '{1}'.
        /// </summary>
        internal static string AttributeStore_Unknown_Property
        {
            get
            {
                return "The type '{0}' does not contain a public property named '{1}'.";
            }
        }


        internal static string FormatAttributeStore_Unknown_Property(object arg1, object arg2)
        {
            return string.Format("The type '{0}' does not contain a public property named '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The {0} field is not a valid Base64 encoding.
        /// </summary>
        internal static string Base64StringAttribute_Invalid
        {
            get
            {
                return "The {0} field is not a valid Base64 encoding.";
            }
        }


        internal static string FormatBase64StringAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field is not a valid Base64 encoding.", arg1);
        }


        /// <summary>
        /// The property {0}.{1} could not be found.
        /// </summary>
        internal static string Common_PropertyNotFound
        {
            get
            {
                return "The property {0}.{1} could not be found.";
            }
        }


        internal static string FormatCommon_PropertyNotFound(object arg1, object arg2)
        {
            return string.Format("The property {0}.{1} could not be found.", arg1, arg2);
        }


        /// <summary>
        /// '{0}' and '{1}' do not match.
        /// </summary>
        internal static string CompareAttribute_MustMatch
        {
            get
            {
                return "'{0}' and '{1}' do not match.";
            }
        }


        internal static string FormatCompareAttribute_MustMatch(object arg1, object arg2)
        {
            return string.Format("'{0}' and '{1}' do not match.", arg1, arg2);
        }


        /// <summary>
        /// Could not find a property named {0}.
        /// </summary>
        internal static string CompareAttribute_UnknownProperty
        {
            get
            {
                return "Could not find a property named {0}.";
            }
        }


        internal static string FormatCompareAttribute_UnknownProperty(object arg1)
        {
            return string.Format("Could not find a property named {0}.", arg1);
        }


        /// <summary>
        /// The {0} field is not a valid credit card number.
        /// </summary>
        internal static string CreditCardAttribute_Invalid
        {
            get
            {
                return "The {0} field is not a valid credit card number.";
            }
        }


        internal static string FormatCreditCardAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field is not a valid credit card number.", arg1);
        }


        /// <summary>
        /// The CustomValidationAttribute method '{0}' in type '{1}' must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Must_Return_ValidationResult
        {
            get
            {
                return "The CustomValidationAttribute method '{0}' in type '{1}' must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success.";
            }
        }


        internal static string FormatCustomValidationAttribute_Method_Must_Return_ValidationResult(object arg1, object arg2)
        {
            return string.Format("The CustomValidationAttribute method '{0}' in type '{1}' must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success.", arg1, arg2);
        }


        /// <summary>
        /// The CustomValidationAttribute method '{0}' does not exist in type '{1}' or is not public and static.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Not_Found
        {
            get
            {
                return "The CustomValidationAttribute method '{0}' does not exist in type '{1}' or is not public and static.";
            }
        }


        internal static string FormatCustomValidationAttribute_Method_Not_Found(object arg1, object arg2)
        {
            return string.Format("The CustomValidationAttribute method '{0}' does not exist in type '{1}' or is not public and static.", arg1, arg2);
        }


        /// <summary>
        /// The CustomValidationAttribute.Method was not specified.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Required
        {
            get
            {
                return "The CustomValidationAttribute.Method was not specified.";
            }
        }



        /// <summary>
        /// The CustomValidationAttribute method '{0}' in type '{1}' must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional.
        /// </summary>
        internal static string CustomValidationAttribute_Method_Signature
        {
            get
            {
                return "The CustomValidationAttribute method '{0}' in type '{1}' must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional.";
            }
        }


        internal static string FormatCustomValidationAttribute_Method_Signature(object arg1, object arg2, object arg3)
        {
            return string.Format("The CustomValidationAttribute method '{0}' in type '{1}' must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Could not convert the value of type '{0}' to '{1}' as expected by method {2}.{3}.
        /// </summary>
        internal static string CustomValidationAttribute_Type_Conversion_Failed
        {
            get
            {
                return "Could not convert the value of type '{0}' to '{1}' as expected by method {2}.{3}.";
            }
        }


        internal static string FormatCustomValidationAttribute_Type_Conversion_Failed(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format("Could not convert the value of type '{0}' to '{1}' as expected by method {2}.{3}.", arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// The custom validation type '{0}' must be public.
        /// </summary>
        internal static string CustomValidationAttribute_Type_Must_Be_Public
        {
            get
            {
                return "The custom validation type '{0}' must be public.";
            }
        }


        internal static string FormatCustomValidationAttribute_Type_Must_Be_Public(object arg1)
        {
            return string.Format("The custom validation type '{0}' must be public.", arg1);
        }


        /// <summary>
        /// {0} is not valid.
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError
        {
            get
            {
                return "{0} is not valid.";
            }
        }


        internal static string FormatCustomValidationAttribute_ValidationError(object arg1)
        {
            return string.Format("{0} is not valid.", arg1);
        }


        /// <summary>
        /// The CustomValidationAttribute.ValidatorType was not specified.
        /// </summary>
        internal static string CustomValidationAttribute_ValidatorType_Required
        {
            get
            {
                return "The CustomValidationAttribute.ValidatorType was not specified.";
            }
        }



        /// <summary>
        /// The custom DataType string cannot be null or empty.
        /// </summary>
        internal static string DataTypeAttribute_EmptyDataTypeString
        {
            get
            {
                return "The custom DataType string cannot be null or empty.";
            }
        }



        /// <summary>
        /// The {0} field equals one of the values specified in DeniedValuesAttribute.
        /// </summary>
        internal static string DeniedValuesAttribute_Invalid
        {
            get
            {
                return "The {0} field equals one of the values specified in DeniedValuesAttribute.";
            }
        }


        internal static string FormatDeniedValuesAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field equals one of the values specified in DeniedValuesAttribute.", arg1);
        }


        /// <summary>
        /// The {0} property has not been set.  Use the {1} method to get the value.
        /// </summary>
        internal static string DisplayAttribute_PropertyNotSet
        {
            get
            {
                return "The {0} property has not been set.  Use the {1} method to get the value.";
            }
        }


        internal static string FormatDisplayAttribute_PropertyNotSet(object arg1, object arg2)
        {
            return string.Format("The {0} property has not been set.  Use the {1} method to get the value.", arg1, arg2);
        }


        /// <summary>
        /// The {0} field is not a valid e-mail address.
        /// </summary>
        internal static string EmailAddressAttribute_Invalid
        {
            get
            {
                return "The {0} field is not a valid e-mail address.";
            }
        }


        internal static string FormatEmailAddressAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field is not a valid e-mail address.", arg1);
        }


        /// <summary>
        /// The type provided for EnumDataTypeAttribute cannot be null.
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeCannotBeNull
        {
            get
            {
                return "The type provided for EnumDataTypeAttribute cannot be null.";
            }
        }



        /// <summary>
        /// The type '{0}' needs to represent an enumeration type.
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum
        {
            get
            {
                return "The type '{0}' needs to represent an enumeration type.";
            }
        }


        internal static string FormatEnumDataTypeAttribute_TypeNeedsToBeAnEnum(object arg1)
        {
            return string.Format("The type '{0}' needs to represent an enumeration type.", arg1);
        }


        /// <summary>
        /// The {0} field only accepts files with the following extensions: {1}
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid
        {
            get
            {
                return "The {0} field only accepts files with the following extensions: {1}";
            }
        }


        internal static string FormatFileExtensionsAttribute_Invalid(object arg1, object arg2)
        {
            return string.Format("The {0} field only accepts files with the following extensions: {1}", arg1, arg2);
        }


        /// <summary>
        /// Cannot retrieve property '{0}' because localization failed.  Type '{1}' is not public or does not contain a public static string property with the name '{2}'.
        /// </summary>
        internal static string LocalizableString_LocalizationFailed
        {
            get
            {
                return "Cannot retrieve property '{0}' because localization failed.  Type '{1}' is not public or does not contain a public static string property with the name '{2}'.";
            }
        }


        internal static string FormatLocalizableString_LocalizationFailed(object arg1, object arg2, object arg3)
        {
            return string.Format("Cannot retrieve property '{0}' because localization failed.  Type '{1}' is not public or does not contain a public static string property with the name '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length.
        /// </summary>
        internal static string MaxLengthAttribute_InvalidMaxLength
        {
            get
            {
                return "MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length.";
            }
        }



        /// <summary>
        /// The field {0} must be a string or array type with a maximum length of '{1}'.
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError
        {
            get
            {
                return "The field {0} must be a string or array type with a maximum length of '{1}'.";
            }
        }


        internal static string FormatMaxLengthAttribute_ValidationError(object arg1, object arg2)
        {
            return string.Format("The field {0} must be a string or array type with a maximum length of '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// MetadataClassType cannot be null.
        /// </summary>
        internal static string MetadataTypeAttribute_TypeCannotBeNull
        {
            get
            {
                return "MetadataClassType cannot be null.";
            }
        }



        /// <summary>
        /// MinLengthAttribute must have a Length value that is zero or greater.
        /// </summary>
        internal static string MinLengthAttribute_InvalidMinLength
        {
            get
            {
                return "MinLengthAttribute must have a Length value that is zero or greater.";
            }
        }



        /// <summary>
        /// The field {0} must be a string or array type with a minimum length of '{1}'.
        /// </summary>
        internal static string MinLengthAttribute_ValidationError
        {
            get
            {
                return "The field {0} must be a string or array type with a minimum length of '{1}'.";
            }
        }


        internal static string FormatMinLengthAttribute_ValidationError(object arg1, object arg2)
        {
            return string.Format("The field {0} must be a string or array type with a minimum length of '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// LengthAttribute must have a MinimumLength value that is zero or greater.
        /// </summary>
        internal static string LengthAttribute_InvalidMinLength
        {
            get
            {
                return "LengthAttribute must have a MinimumLength value that is zero or greater.";
            }
        }



        /// <summary>
        /// LengthAttribute must have a MaximumLength value that is greater than or equal to MinimumLength.
        /// </summary>
        internal static string LengthAttribute_InvalidMaxLength
        {
            get
            {
                return "LengthAttribute must have a MaximumLength value that is greater than or equal to MinimumLength.";
            }
        }



        /// <summary>
        /// The field {0} must be a string or collection type with a minimum length of '{1}' and maximum length of '{2}'.
        /// </summary>
        internal static string LengthAttribute_ValidationError
        {
            get
            {
                return "The field {0} must be a string or collection type with a minimum length of '{1}' and maximum length of '{2}'.";
            }
        }


        internal static string FormatLengthAttribute_ValidationError(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be a string or collection type with a minimum length of '{1}' and maximum length of '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The field of type {0} must be a string, array or ICollection type.
        /// </summary>
        internal static string LengthAttribute_InvalidValueType
        {
            get
            {
                return "The field of type {0} must be a string, array or ICollection type.";
            }
        }


        internal static string FormatLengthAttribute_InvalidValueType(object arg1)
        {
            return string.Format("The field of type {0} must be a string, array or ICollection type.", arg1);
        }


        /// <summary>
        /// The {0} field is not a valid phone number.
        /// </summary>
        internal static string PhoneAttribute_Invalid
        {
            get
            {
                return "The {0} field is not a valid phone number.";
            }
        }


        internal static string FormatPhoneAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field is not a valid phone number.", arg1);
        }


        /// <summary>
        /// The type {0} must implement {1}.
        /// </summary>
        internal static string RangeAttribute_ArbitraryTypeNotIComparable
        {
            get
            {
                return "The type {0} must implement {1}.";
            }
        }


        internal static string FormatRangeAttribute_ArbitraryTypeNotIComparable(object arg1, object arg2)
        {
            return string.Format("The type {0} must implement {1}.", arg1, arg2);
        }


        /// <summary>
        /// The maximum value '{0}' must be greater than or equal to the minimum value '{1}'.
        /// </summary>
        internal static string RangeAttribute_MinGreaterThanMax
        {
            get
            {
                return "The maximum value '{0}' must be greater than or equal to the minimum value '{1}'.";
            }
        }


        internal static string FormatRangeAttribute_MinGreaterThanMax(object arg1, object arg2)
        {
            return string.Format("The maximum value '{0}' must be greater than or equal to the minimum value '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Cannot use exclusive bounds when the maximum value is equal to the minimum value.
        /// </summary>
        internal static string RangeAttribute_CannotUseExclusiveBoundsWhenTheyAreEqual
        {
            get
            {
                return "Cannot use exclusive bounds when the maximum value is equal to the minimum value.";
            }
        }



        /// <summary>
        /// The minimum and maximum values must be set.
        /// </summary>
        internal static string RangeAttribute_Must_Set_Min_And_Max
        {
            get
            {
                return "The minimum and maximum values must be set.";
            }
        }



        /// <summary>
        /// The OperandType must be set when strings are used for minimum and maximum values.
        /// </summary>
        internal static string RangeAttribute_Must_Set_Operand_Type
        {
            get
            {
                return "The OperandType must be set when strings are used for minimum and maximum values.";
            }
        }



        /// <summary>
        /// The field {0} must be between {1} and {2}.
        /// </summary>
        internal static string RangeAttribute_ValidationError
        {
            get
            {
                return "The field {0} must be between {1} and {2}.";
            }
        }


        internal static string FormatRangeAttribute_ValidationError(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be between {1} and {2}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The field {0} must be between {1} exclusive and {2}.
        /// </summary>
        internal static string RangeAttribute_ValidationError_MinExclusive
        {
            get
            {
                return "The field {0} must be between {1} exclusive and {2}.";
            }
        }


        internal static string FormatRangeAttribute_ValidationError_MinExclusive(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be between {1} exclusive and {2}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The field {0} must be between {1} and {2} exclusive.
        /// </summary>
        internal static string RangeAttribute_ValidationError_MaxExclusive
        {
            get
            {
                return "The field {0} must be between {1} and {2} exclusive.";
            }
        }


        internal static string FormatRangeAttribute_ValidationError_MaxExclusive(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be between {1} and {2} exclusive.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The field {0} must be between {1} exclusive and {2} exclusive.
        /// </summary>
        internal static string RangeAttribute_ValidationError_MinExclusive_MaxExclusive
        {
            get
            {
                return "The field {0} must be between {1} exclusive and {2} exclusive.";
            }
        }


        internal static string FormatRangeAttribute_ValidationError_MinExclusive_MaxExclusive(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be between {1} exclusive and {2} exclusive.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The field {0} must match the regular expression '{1}'.
        /// </summary>
        internal static string RegexAttribute_ValidationError
        {
            get
            {
                return "The field {0} must match the regular expression '{1}'.";
            }
        }


        internal static string FormatRegexAttribute_ValidationError(object arg1, object arg2)
        {
            return string.Format("The field {0} must match the regular expression '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The pattern must be set to a valid regular expression.
        /// </summary>
        internal static string RegularExpressionAttribute_Empty_Pattern
        {
            get
            {
                return "The pattern must be set to a valid regular expression.";
            }
        }



        /// <summary>
        /// The {0} field is required.
        /// </summary>
        internal static string RequiredAttribute_ValidationError
        {
            get
            {
                return "The {0} field is required.";
            }
        }


        internal static string FormatRequiredAttribute_ValidationError(object arg1)
        {
            return string.Format("The {0} field is required.", arg1);
        }


        /// <summary>
        /// The maximum length must be a nonnegative integer.
        /// </summary>
        internal static string StringLengthAttribute_InvalidMaxLength
        {
            get
            {
                return "The maximum length must be a nonnegative integer.";
            }
        }



        /// <summary>
        /// The field {0} must be a string with a maximum length of {1}.
        /// </summary>
        internal static string StringLengthAttribute_ValidationError
        {
            get
            {
                return "The field {0} must be a string with a maximum length of {1}.";
            }
        }


        internal static string FormatStringLengthAttribute_ValidationError(object arg1, object arg2)
        {
            return string.Format("The field {0} must be a string with a maximum length of {1}.", arg1, arg2);
        }


        /// <summary>
        /// The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum
        {
            get
            {
                return "The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.";
            }
        }


        internal static string FormatStringLengthAttribute_ValidationErrorIncludingMinimum(object arg1, object arg2, object arg3)
        {
            return string.Format("The field {0} must be a string with a minimum length of {2} and a maximum length of {1}.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The key parameter at position {0} with value '{1}' is not a string. Every key control parameter must be a string.
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNotAString
        {
            get
            {
                return "The key parameter at position {0} with value '{1}' is not a string. Every key control parameter must be a string.";
            }
        }


        internal static string FormatUIHintImplementation_ControlParameterKeyIsNotAString(object arg1, object arg2)
        {
            return string.Format("The key parameter at position {0} with value '{1}' is not a string. Every key control parameter must be a string.", arg1, arg2);
        }


        /// <summary>
        /// The key parameter at position {0} is null. Every key control parameter must be a string.
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNull
        {
            get
            {
                return "The key parameter at position {0} is null. Every key control parameter must be a string.";
            }
        }


        internal static string FormatUIHintImplementation_ControlParameterKeyIsNull(object arg1)
        {
            return string.Format("The key parameter at position {0} is null. Every key control parameter must be a string.", arg1);
        }


        /// <summary>
        /// The key parameter at position {0} with value '{1}' occurs more than once.
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce
        {
            get
            {
                return "The key parameter at position {0} with value '{1}' occurs more than once.";
            }
        }


        internal static string FormatUIHintImplementation_ControlParameterKeyOccursMoreThanOnce(object arg1, object arg2)
        {
            return string.Format("The key parameter at position {0} with value '{1}' occurs more than once.", arg1, arg2);
        }


        /// <summary>
        /// The number of control parameters must be even.
        /// </summary>
        internal static string UIHintImplementation_NeedEvenNumberOfControlParameters
        {
            get
            {
                return "The number of control parameters must be even.";
            }
        }



        /// <summary>
        /// The {0} field is not a valid fully-qualified http, https, or ftp URL.
        /// </summary>
        internal static string UrlAttribute_Invalid
        {
            get
            {
                return "The {0} field is not a valid fully-qualified http, https, or ftp URL.";
            }
        }


        internal static string FormatUrlAttribute_Invalid(object arg1)
        {
            return string.Format("The {0} field is not a valid fully-qualified http, https, or ftp URL.", arg1);
        }


        /// <summary>
        /// Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.
        /// </summary>
        internal static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource
        {
            get
            {
                return "Either ErrorMessageString or ErrorMessageResourceName must be set, but not both.";
            }
        }



        /// <summary>
        /// IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context).
        /// </summary>
        internal static string ValidationAttribute_IsValid_NotImplemented
        {
            get
            {
                return "IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context).";
            }
        }



        /// <summary>
        /// Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute.
        /// </summary>
        internal static string ValidationAttribute_NeedBothResourceTypeAndResourceName
        {
            get
            {
                return "Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute.";
            }
        }



        /// <summary>
        /// The property '{0}' on resource type '{1}' is not a string type.
        /// </summary>
        internal static string ValidationAttribute_ResourcePropertyNotStringType
        {
            get
            {
                return "The property '{0}' on resource type '{1}' is not a string type.";
            }
        }


        internal static string FormatValidationAttribute_ResourcePropertyNotStringType(object arg1, object arg2)
        {
            return string.Format("The property '{0}' on resource type '{1}' is not a string type.", arg1, arg2);
        }


        /// <summary>
        /// The resource type '{0}' does not have an accessible static property named '{1}'.
        /// </summary>
        internal static string ValidationAttribute_ResourceTypeDoesNotHaveProperty
        {
            get
            {
                return "The resource type '{0}' does not have an accessible static property named '{1}'.";
            }
        }


        internal static string FormatValidationAttribute_ResourceTypeDoesNotHaveProperty(object arg1, object arg2)
        {
            return string.Format("The resource type '{0}' does not have an accessible static property named '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The field {0} is invalid.
        /// </summary>
        internal static string ValidationAttribute_ValidationError
        {
            get
            {
                return "The field {0} is invalid.";
            }
        }


        internal static string FormatValidationAttribute_ValidationError(object arg1)
        {
            return string.Format("The field {0} is invalid.", arg1);
        }


        /// <summary>
        /// The instance provided must match the ObjectInstance on the ValidationContext supplied.
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance
        {
            get
            {
                return "The instance provided must match the ObjectInstance on the ValidationContext supplied.";
            }
        }



        /// <summary>
        /// The value for property '{0}' must be of type '{1}'.
        /// </summary>
        internal static string Validator_Property_Value_Wrong_Type
        {
            get
            {
                return "The value for property '{0}' must be of type '{1}'.";
            }
        }


        internal static string FormatValidator_Property_Value_Wrong_Type(object arg1, object arg2)
        {
            return string.Format("The value for property '{0}' must be of type '{1}'.", arg1, arg2);
        }
    }
}
