
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static partial class SR
    {

        private static global::System.Resources.ResourceManager s_resourceManager;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(s_resourceManager, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Linq.Expressions", typeof(SR).Assembly);
                    s_resourceManager = temp;
                }
                return s_resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// reducible nodes must override Expression.Reduce()
        /// </summary>
        internal static string ReducibleMustOverrideReduce
        {
            get
            {
                return "reducible nodes must override Expression.Reduce()";
            }
        }



        /// <summary>
        /// node cannot reduce to itself or null
        /// </summary>
        internal static string MustReduceToDifferent
        {
            get
            {
                return "node cannot reduce to itself or null";
            }
        }



        /// <summary>
        /// cannot assign from the reduced node type to the original node type
        /// </summary>
        internal static string ReducedNotCompatible
        {
            get
            {
                return "cannot assign from the reduced node type to the original node type";
            }
        }



        /// <summary>
        /// Setter must have parameters.
        /// </summary>
        internal static string SetterHasNoParams
        {
            get
            {
                return "Setter must have parameters.";
            }
        }



        /// <summary>
        /// Property cannot have a managed pointer type.
        /// </summary>
        internal static string PropertyCannotHaveRefType
        {
            get
            {
                return "Property cannot have a managed pointer type.";
            }
        }



        /// <summary>
        /// Indexing parameters of getter and setter must match.
        /// </summary>
        internal static string IndexesOfSetGetMustMatch
        {
            get
            {
                return "Indexing parameters of getter and setter must match.";
            }
        }



        /// <summary>
        /// Accessor method should not have VarArgs.
        /// </summary>
        internal static string AccessorsCannotHaveVarArgs
        {
            get
            {
                return "Accessor method should not have VarArgs.";
            }
        }



        /// <summary>
        /// Accessor indexes cannot be passed ByRef.
        /// </summary>
        internal static string AccessorsCannotHaveByRefArgs
        {
            get
            {
                return "Accessor indexes cannot be passed ByRef.";
            }
        }



        /// <summary>
        /// Bounds count cannot be less than 1
        /// </summary>
        internal static string BoundsCannotBeLessThanOne
        {
            get
            {
                return "Bounds count cannot be less than 1";
            }
        }



        /// <summary>
        /// Type must not be ByRef
        /// </summary>
        internal static string TypeMustNotBeByRef
        {
            get
            {
                return "Type must not be ByRef";
            }
        }



        /// <summary>
        /// Type must not be a pointer type
        /// </summary>
        internal static string TypeMustNotBePointer
        {
            get
            {
                return "Type must not be a pointer type";
            }
        }



        /// <summary>
        /// Setter should have void type.
        /// </summary>
        internal static string SetterMustBeVoid
        {
            get
            {
                return "Setter should have void type.";
            }
        }



        /// <summary>
        /// Property type must match the value type of getter
        /// </summary>
        internal static string PropertyTypeMustMatchGetter
        {
            get
            {
                return "Property type must match the value type of getter";
            }
        }



        /// <summary>
        /// Property type must match the value type of setter
        /// </summary>
        internal static string PropertyTypeMustMatchSetter
        {
            get
            {
                return "Property type must match the value type of setter";
            }
        }



        /// <summary>
        /// Both accessors must be static.
        /// </summary>
        internal static string BothAccessorsMustBeStatic
        {
            get
            {
                return "Both accessors must be static.";
            }
        }



        /// <summary>
        /// Static field requires null instance, non-static field requires non-null instance.
        /// </summary>
        internal static string OnlyStaticFieldsHaveNullInstance
        {
            get
            {
                return "Static field requires null instance, non-static field requires non-null instance.";
            }
        }



        /// <summary>
        /// Static property requires null instance, non-static property requires non-null instance.
        /// </summary>
        internal static string OnlyStaticPropertiesHaveNullInstance
        {
            get
            {
                return "Static property requires null instance, non-static property requires non-null instance.";
            }
        }



        /// <summary>
        /// Static method requires null instance, non-static method requires non-null instance.
        /// </summary>
        internal static string OnlyStaticMethodsHaveNullInstance
        {
            get
            {
                return "Static method requires null instance, non-static method requires non-null instance.";
            }
        }



        /// <summary>
        /// Property cannot have a void type.
        /// </summary>
        internal static string PropertyTypeCannotBeVoid
        {
            get
            {
                return "Property cannot have a void type.";
            }
        }



        /// <summary>
        /// Can only unbox from an object or interface type to a value type.
        /// </summary>
        internal static string InvalidUnboxType
        {
            get
            {
                return "Can only unbox from an object or interface type to a value type.";
            }
        }



        /// <summary>
        /// Expression must be writeable
        /// </summary>
        internal static string ExpressionMustBeWriteable
        {
            get
            {
                return "Expression must be writeable";
            }
        }



        /// <summary>
        /// Argument must not have a value type.
        /// </summary>
        internal static string ArgumentMustNotHaveValueType
        {
            get
            {
                return "Argument must not have a value type.";
            }
        }



        /// <summary>
        /// must be reducible node
        /// </summary>
        internal static string MustBeReducible
        {
            get
            {
                return "must be reducible node";
            }
        }



        /// <summary>
        /// All test values must have the same type.
        /// </summary>
        internal static string AllTestValuesMustHaveSameType
        {
            get
            {
                return "All test values must have the same type.";
            }
        }



        /// <summary>
        /// All case bodies and the default body must have the same type.
        /// </summary>
        internal static string AllCaseBodiesMustHaveSameType
        {
            get
            {
                return "All case bodies and the default body must have the same type.";
            }
        }



        /// <summary>
        /// Default body must be supplied if case bodies are not System.Void.
        /// </summary>
        internal static string DefaultBodyMustBeSupplied
        {
            get
            {
                return "Default body must be supplied if case bodies are not System.Void.";
            }
        }



        /// <summary>
        /// Label type must be System.Void if an expression is not supplied
        /// </summary>
        internal static string LabelMustBeVoidOrHaveExpression
        {
            get
            {
                return "Label type must be System.Void if an expression is not supplied";
            }
        }



        /// <summary>
        /// Type must be System.Void for this label argument
        /// </summary>
        internal static string LabelTypeMustBeVoid
        {
            get
            {
                return "Type must be System.Void for this label argument";
            }
        }



        /// <summary>
        /// Quoted expression must be a lambda
        /// </summary>
        internal static string QuotedExpressionMustBeLambda
        {
            get
            {
                return "Quoted expression must be a lambda";
            }
        }



        /// <summary>
        /// Variable '{0}' uses unsupported type '{1}'. Reference types are not supported for variables.
        /// </summary>
        internal static string VariableMustNotBeByRef
        {
            get
            {
                return "Variable '{0}' uses unsupported type '{1}'. Reference types are not supported for variables.";
            }
        }


        internal static string FormatVariableMustNotBeByRef(object arg1, object arg2)
        {
            return string.Format("Variable '{0}' uses unsupported type '{1}'. Reference types are not supported for variables.", arg1, arg2);
        }


        /// <summary>
        /// Found duplicate parameter '{0}'. Each ParameterExpression in the list must be a unique object.
        /// </summary>
        internal static string DuplicateVariable
        {
            get
            {
                return "Found duplicate parameter '{0}'. Each ParameterExpression in the list must be a unique object.";
            }
        }


        internal static string FormatDuplicateVariable(object arg1)
        {
            return string.Format("Found duplicate parameter '{0}'. Each ParameterExpression in the list must be a unique object.", arg1);
        }


        /// <summary>
        /// Start and End must be well ordered
        /// </summary>
        internal static string StartEndMustBeOrdered
        {
            get
            {
                return "Start and End must be well ordered";
            }
        }



        /// <summary>
        /// fault cannot be used with catch or finally clauses
        /// </summary>
        internal static string FaultCannotHaveCatchOrFinally
        {
            get
            {
                return "fault cannot be used with catch or finally clauses";
            }
        }



        /// <summary>
        /// try must have at least one catch, finally, or fault clause
        /// </summary>
        internal static string TryMustHaveCatchFinallyOrFault
        {
            get
            {
                return "try must have at least one catch, finally, or fault clause";
            }
        }



        /// <summary>
        /// Body of catch must have the same type as body of try.
        /// </summary>
        internal static string BodyOfCatchMustHaveSameTypeAsBodyOfTry
        {
            get
            {
                return "Body of catch must have the same type as body of try.";
            }
        }



        /// <summary>
        /// Extension node must override the property {0}.
        /// </summary>
        internal static string ExtensionNodeMustOverrideProperty
        {
            get
            {
                return "Extension node must override the property {0}.";
            }
        }


        internal static string FormatExtensionNodeMustOverrideProperty(object arg1)
        {
            return string.Format("Extension node must override the property {0}.", arg1);
        }


        /// <summary>
        /// User-defined operator method '{0}' must be static.
        /// </summary>
        internal static string UserDefinedOperatorMustBeStatic
        {
            get
            {
                return "User-defined operator method '{0}' must be static.";
            }
        }


        internal static string FormatUserDefinedOperatorMustBeStatic(object arg1)
        {
            return string.Format("User-defined operator method '{0}' must be static.", arg1);
        }


        /// <summary>
        /// User-defined operator method '{0}' must not be void.
        /// </summary>
        internal static string UserDefinedOperatorMustNotBeVoid
        {
            get
            {
                return "User-defined operator method '{0}' must not be void.";
            }
        }


        internal static string FormatUserDefinedOperatorMustNotBeVoid(object arg1)
        {
            return string.Format("User-defined operator method '{0}' must not be void.", arg1);
        }


        /// <summary>
        /// No coercion operator is defined between types '{0}' and '{1}'.
        /// </summary>
        internal static string CoercionOperatorNotDefined
        {
            get
            {
                return "No coercion operator is defined between types '{0}' and '{1}'.";
            }
        }


        internal static string FormatCoercionOperatorNotDefined(object arg1, object arg2)
        {
            return string.Format("No coercion operator is defined between types '{0}' and '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The unary operator {0} is not defined for the type '{1}'.
        /// </summary>
        internal static string UnaryOperatorNotDefined
        {
            get
            {
                return "The unary operator {0} is not defined for the type '{1}'.";
            }
        }


        internal static string FormatUnaryOperatorNotDefined(object arg1, object arg2)
        {
            return string.Format("The unary operator {0} is not defined for the type '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The binary operator {0} is not defined for the types '{1}' and '{2}'.
        /// </summary>
        internal static string BinaryOperatorNotDefined
        {
            get
            {
                return "The binary operator {0} is not defined for the types '{1}' and '{2}'.";
            }
        }


        internal static string FormatBinaryOperatorNotDefined(object arg1, object arg2, object arg3)
        {
            return string.Format("The binary operator {0} is not defined for the types '{1}' and '{2}'.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Reference equality is not defined for the types '{0}' and '{1}'.
        /// </summary>
        internal static string ReferenceEqualityNotDefined
        {
            get
            {
                return "Reference equality is not defined for the types '{0}' and '{1}'.";
            }
        }


        internal static string FormatReferenceEqualityNotDefined(object arg1, object arg2)
        {
            return string.Format("Reference equality is not defined for the types '{0}' and '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The operands for operator '{0}' do not match the parameters of method '{1}'.
        /// </summary>
        internal static string OperandTypesDoNotMatchParameters
        {
            get
            {
                return "The operands for operator '{0}' do not match the parameters of method '{1}'.";
            }
        }


        internal static string FormatOperandTypesDoNotMatchParameters(object arg1, object arg2)
        {
            return string.Format("The operands for operator '{0}' do not match the parameters of method '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// The return type of overload method for operator '{0}' does not match the parameter type of conversion method '{1}'.
        /// </summary>
        internal static string OverloadOperatorTypeDoesNotMatchConversionType
        {
            get
            {
                return "The return type of overload method for operator '{0}' does not match the parameter type of conversion method '{1}'.";
            }
        }


        internal static string FormatOverloadOperatorTypeDoesNotMatchConversionType(object arg1, object arg2)
        {
            return string.Format("The return type of overload method for operator '{0}' does not match the parameter type of conversion method '{1}'.", arg1, arg2);
        }


        /// <summary>
        /// Conversion is not supported for arithmetic types without operator overloading.
        /// </summary>
        internal static string ConversionIsNotSupportedForArithmeticTypes
        {
            get
            {
                return "Conversion is not supported for arithmetic types without operator overloading.";
            }
        }



        /// <summary>
        /// Argument must be array
        /// </summary>
        internal static string ArgumentMustBeArray
        {
            get
            {
                return "Argument must be array";
            }
        }



        /// <summary>
        /// Argument must be boolean
        /// </summary>
        internal static string ArgumentMustBeBoolean
        {
            get
            {
                return "Argument must be boolean";
            }
        }



        /// <summary>
        /// The user-defined equality method '{0}' must return a boolean value.
        /// </summary>
        internal static string EqualityMustReturnBoolean
        {
            get
            {
                return "The user-defined equality method '{0}' must return a boolean value.";
            }
        }


        internal static string FormatEqualityMustReturnBoolean(object arg1)
        {
            return string.Format("The user-defined equality method '{0}' must return a boolean value.", arg1);
        }


        /// <summary>
        /// Argument must be either a FieldInfo or PropertyInfo
        /// </summary>
        internal static string ArgumentMustBeFieldInfoOrPropertyInfo
        {
            get
            {
                return "Argument must be either a FieldInfo or PropertyInfo";
            }
        }



        /// <summary>
        /// Argument must be either a FieldInfo, PropertyInfo or MethodInfo
        /// </summary>
        internal static string ArgumentMustBeFieldInfoOrPropertyInfoOrMethod
        {
            get
            {
                return "Argument must be either a FieldInfo, PropertyInfo or MethodInfo";
            }
        }



        /// <summary>
        /// Argument must be an instance member
        /// </summary>
        internal static string ArgumentMustBeInstanceMember
        {
            get
            {
                return "Argument must be an instance member";
            }
        }



        /// <summary>
        /// Argument must be of an integer type
        /// </summary>
        internal static string ArgumentMustBeInteger
        {
            get
            {
                return "Argument must be of an integer type";
            }
        }



        /// <summary>
        /// Argument for array index must be of type Int32
        /// </summary>
        internal static string ArgumentMustBeArrayIndexType
        {
            get
            {
                return "Argument for array index must be of type Int32";
            }
        }



        /// <summary>
        /// Argument must be single-dimensional, zero-based array type
        /// </summary>
        internal static string ArgumentMustBeSingleDimensionalArrayType
        {
            get
            {
                return "Argument must be single-dimensional, zero-based array type";
            }
        }



        /// <summary>
        /// Argument types do not match
        /// </summary>
        internal static string ArgumentTypesMustMatch
        {
            get
            {
                return "Argument types do not match";
            }
        }



        /// <summary>
        /// Cannot auto initialize elements of value type through property '{0}', use assignment instead
        /// </summary>
        internal static string CannotAutoInitializeValueTypeElementThroughProperty
        {
            get
            {
                return "Cannot auto initialize elements of value type through property '{0}', use assignment instead";
            }
        }


        internal static string FormatCannotAutoInitializeValueTypeElementThroughProperty(object arg1)
        {
            return string.Format("Cannot auto initialize elements of value type through property '{0}', use assignment instead", arg1);
        }


        /// <summary>
        /// Cannot auto initialize members of value type through property '{0}', use assignment instead
        /// </summary>
        internal static string CannotAutoInitializeValueTypeMemberThroughProperty
        {
            get
            {
                return "Cannot auto initialize members of value type through property '{0}', use assignment instead";
            }
        }


        internal static string FormatCannotAutoInitializeValueTypeMemberThroughProperty(object arg1)
        {
            return string.Format("Cannot auto initialize members of value type through property '{0}', use assignment instead", arg1);
        }


        /// <summary>
        /// The type used in TypeAs Expression must be of reference or nullable type, {0} is neither
        /// </summary>
        internal static string IncorrectTypeForTypeAs
        {
            get
            {
                return "The type used in TypeAs Expression must be of reference or nullable type, {0} is neither";
            }
        }


        internal static string FormatIncorrectTypeForTypeAs(object arg1)
        {
            return string.Format("The type used in TypeAs Expression must be of reference or nullable type, {0} is neither", arg1);
        }


        /// <summary>
        /// Coalesce used with type that cannot be null
        /// </summary>
        internal static string CoalesceUsedOnNonNullType
        {
            get
            {
                return "Coalesce used with type that cannot be null";
            }
        }



        /// <summary>
        /// An expression of type '{0}' cannot be used to initialize an array of type '{1}'
        /// </summary>
        internal static string ExpressionTypeCannotInitializeArrayType
        {
            get
            {
                return "An expression of type '{0}' cannot be used to initialize an array of type '{1}'";
            }
        }


        internal static string FormatExpressionTypeCannotInitializeArrayType(object arg1, object arg2)
        {
            return string.Format("An expression of type '{0}' cannot be used to initialize an array of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Argument type '{0}' does not match the corresponding member type '{1}'
        /// </summary>
        internal static string ArgumentTypeDoesNotMatchMember
        {
            get
            {
                return " Argument type '{0}' does not match the corresponding member type '{1}'";
            }
        }


        internal static string FormatArgumentTypeDoesNotMatchMember(object arg1, object arg2)
        {
            return string.Format(" Argument type '{0}' does not match the corresponding member type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// The member '{0}' is not declared on type '{1}' being created
        /// </summary>
        internal static string ArgumentMemberNotDeclOnType
        {
            get
            {
                return " The member '{0}' is not declared on type '{1}' being created";
            }
        }


        internal static string FormatArgumentMemberNotDeclOnType(object arg1, object arg2)
        {
            return string.Format(" The member '{0}' is not declared on type '{1}' being created", arg1, arg2);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be used for return type '{1}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchReturn
        {
            get
            {
                return "Expression of type '{0}' cannot be used for return type '{1}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchReturn(object arg1, object arg2)
        {
            return string.Format("Expression of type '{0}' cannot be used for return type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be used for assignment to type '{1}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchAssignment
        {
            get
            {
                return "Expression of type '{0}' cannot be used for assignment to type '{1}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchAssignment(object arg1, object arg2)
        {
            return string.Format("Expression of type '{0}' cannot be used for assignment to type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be used for label of type '{1}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchLabel
        {
            get
            {
                return "Expression of type '{0}' cannot be used for label of type '{1}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchLabel(object arg1, object arg2)
        {
            return string.Format("Expression of type '{0}' cannot be used for label of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be invoked
        /// </summary>
        internal static string ExpressionTypeNotInvocable
        {
            get
            {
                return "Expression of type '{0}' cannot be invoked";
            }
        }


        internal static string FormatExpressionTypeNotInvocable(object arg1)
        {
            return string.Format("Expression of type '{0}' cannot be invoked", arg1);
        }


        /// <summary>
        /// Field '{0}' is not defined for type '{1}'
        /// </summary>
        internal static string FieldNotDefinedForType
        {
            get
            {
                return "Field '{0}' is not defined for type '{1}'";
            }
        }


        internal static string FormatFieldNotDefinedForType(object arg1, object arg2)
        {
            return string.Format("Field '{0}' is not defined for type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Instance field '{0}' is not defined for type '{1}'
        /// </summary>
        internal static string InstanceFieldNotDefinedForType
        {
            get
            {
                return "Instance field '{0}' is not defined for type '{1}'";
            }
        }


        internal static string FormatInstanceFieldNotDefinedForType(object arg1, object arg2)
        {
            return string.Format("Instance field '{0}' is not defined for type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Field '{0}.{1}' is not defined for type '{2}'
        /// </summary>
        internal static string FieldInfoNotDefinedForType
        {
            get
            {
                return "Field '{0}.{1}' is not defined for type '{2}'";
            }
        }


        internal static string FormatFieldInfoNotDefinedForType(object arg1, object arg2, object arg3)
        {
            return string.Format("Field '{0}.{1}' is not defined for type '{2}'", arg1, arg2, arg3);
        }


        /// <summary>
        /// Incorrect number of indexes
        /// </summary>
        internal static string IncorrectNumberOfIndexes
        {
            get
            {
                return "Incorrect number of indexes";
            }
        }



        /// <summary>
        /// Incorrect number of parameters supplied for lambda declaration
        /// </summary>
        internal static string IncorrectNumberOfLambdaDeclarationParameters
        {
            get
            {
                return "Incorrect number of parameters supplied for lambda declaration";
            }
        }



        /// <summary>
        /// Incorrect number of members for constructor
        /// </summary>
        internal static string IncorrectNumberOfMembersForGivenConstructor
        {
            get
            {
                return " Incorrect number of members for constructor";
            }
        }



        /// <summary>
        /// Incorrect number of arguments for the given members
        /// </summary>
        internal static string IncorrectNumberOfArgumentsForMembers
        {
            get
            {
                return "Incorrect number of arguments for the given members ";
            }
        }



        /// <summary>
        /// Lambda type parameter must be derived from System.MulticastDelegate
        /// </summary>
        internal static string LambdaTypeMustBeDerivedFromSystemDelegate
        {
            get
            {
                return "Lambda type parameter must be derived from System.MulticastDelegate";
            }
        }



        /// <summary>
        /// Member '{0}' not field or property
        /// </summary>
        internal static string MemberNotFieldOrProperty
        {
            get
            {
                return "Member '{0}' not field or property";
            }
        }


        internal static string FormatMemberNotFieldOrProperty(object arg1)
        {
            return string.Format("Member '{0}' not field or property", arg1);
        }


        /// <summary>
        /// Method {0} contains generic parameters
        /// </summary>
        internal static string MethodContainsGenericParameters
        {
            get
            {
                return "Method {0} contains generic parameters";
            }
        }


        internal static string FormatMethodContainsGenericParameters(object arg1)
        {
            return string.Format("Method {0} contains generic parameters", arg1);
        }


        /// <summary>
        /// Method {0} is a generic method definition
        /// </summary>
        internal static string MethodIsGeneric
        {
            get
            {
                return "Method {0} is a generic method definition";
            }
        }


        internal static string FormatMethodIsGeneric(object arg1)
        {
            return string.Format("Method {0} is a generic method definition", arg1);
        }


        /// <summary>
        /// The method '{0}.{1}' is not a property accessor
        /// </summary>
        internal static string MethodNotPropertyAccessor
        {
            get
            {
                return "The method '{0}.{1}' is not a property accessor";
            }
        }


        internal static string FormatMethodNotPropertyAccessor(object arg1, object arg2)
        {
            return string.Format("The method '{0}.{1}' is not a property accessor", arg1, arg2);
        }


        /// <summary>
        /// The property '{0}' has no 'get' accessor
        /// </summary>
        internal static string PropertyDoesNotHaveGetter
        {
            get
            {
                return "The property '{0}' has no 'get' accessor";
            }
        }


        internal static string FormatPropertyDoesNotHaveGetter(object arg1)
        {
            return string.Format("The property '{0}' has no 'get' accessor", arg1);
        }


        /// <summary>
        /// The property '{0}' has no 'set' accessor
        /// </summary>
        internal static string PropertyDoesNotHaveSetter
        {
            get
            {
                return "The property '{0}' has no 'set' accessor";
            }
        }


        internal static string FormatPropertyDoesNotHaveSetter(object arg1)
        {
            return string.Format("The property '{0}' has no 'set' accessor", arg1);
        }


        /// <summary>
        /// The property '{0}' has no 'get' or 'set' accessors
        /// </summary>
        internal static string PropertyDoesNotHaveAccessor
        {
            get
            {
                return "The property '{0}' has no 'get' or 'set' accessors";
            }
        }


        internal static string FormatPropertyDoesNotHaveAccessor(object arg1)
        {
            return string.Format("The property '{0}' has no 'get' or 'set' accessors", arg1);
        }


        /// <summary>
        /// '{0}' is not a member of type '{1}'
        /// </summary>
        internal static string NotAMemberOfType
        {
            get
            {
                return "'{0}' is not a member of type '{1}'";
            }
        }


        internal static string FormatNotAMemberOfType(object arg1, object arg2)
        {
            return string.Format("'{0}' is not a member of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// '{0}' is not a member of any type
        /// </summary>
        internal static string NotAMemberOfAnyType
        {
            get
            {
                return "'{0}' is not a member of any type";
            }
        }


        internal static string FormatNotAMemberOfAnyType(object arg1)
        {
            return string.Format("'{0}' is not a member of any type", arg1);
        }


        /// <summary>
        /// The expression type '{0}' is not supported
        /// </summary>
        internal static string UnsupportedExpressionType
        {
            get
            {
                return "The expression type '{0}' is not supported";
            }
        }


        internal static string FormatUnsupportedExpressionType(object arg1)
        {
            return string.Format("The expression type '{0}' is not supported", arg1);
        }


        /// <summary>
        /// ParameterExpression of type '{0}' cannot be used for delegate parameter of type '{1}'
        /// </summary>
        internal static string ParameterExpressionNotValidAsDelegate
        {
            get
            {
                return "ParameterExpression of type '{0}' cannot be used for delegate parameter of type '{1}'";
            }
        }


        internal static string FormatParameterExpressionNotValidAsDelegate(object arg1, object arg2)
        {
            return string.Format("ParameterExpression of type '{0}' cannot be used for delegate parameter of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Property '{0}' is not defined for type '{1}'
        /// </summary>
        internal static string PropertyNotDefinedForType
        {
            get
            {
                return "Property '{0}' is not defined for type '{1}'";
            }
        }


        internal static string FormatPropertyNotDefinedForType(object arg1, object arg2)
        {
            return string.Format("Property '{0}' is not defined for type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Instance property '{0}' is not defined for type '{1}'
        /// </summary>
        internal static string InstancePropertyNotDefinedForType
        {
            get
            {
                return "Instance property '{0}' is not defined for type '{1}'";
            }
        }


        internal static string FormatInstancePropertyNotDefinedForType(object arg1, object arg2)
        {
            return string.Format("Instance property '{0}' is not defined for type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Instance property '{0}' that takes no argument is not defined for type '{1}'
        /// </summary>
        internal static string InstancePropertyWithoutParameterNotDefinedForType
        {
            get
            {
                return "Instance property '{0}' that takes no argument is not defined for type '{1}'";
            }
        }


        internal static string FormatInstancePropertyWithoutParameterNotDefinedForType(object arg1, object arg2)
        {
            return string.Format("Instance property '{0}' that takes no argument is not defined for type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Instance property '{0}{1}' is not defined for type '{2}'
        /// </summary>
        internal static string InstancePropertyWithSpecifiedParametersNotDefinedForType
        {
            get
            {
                return "Instance property '{0}{1}' is not defined for type '{2}'";
            }
        }


        internal static string FormatInstancePropertyWithSpecifiedParametersNotDefinedForType(object arg1, object arg2, object arg3)
        {
            return string.Format("Instance property '{0}{1}' is not defined for type '{2}'", arg1, arg2, arg3);
        }


        /// <summary>
        /// Method '{0}' declared on type '{1}' cannot be called with instance of type '{2}'
        /// </summary>
        internal static string InstanceAndMethodTypeMismatch
        {
            get
            {
                return "Method '{0}' declared on type '{1}' cannot be called with instance of type '{2}'";
            }
        }


        internal static string FormatInstanceAndMethodTypeMismatch(object arg1, object arg2, object arg3)
        {
            return string.Format("Method '{0}' declared on type '{1}' cannot be called with instance of type '{2}'", arg1, arg2, arg3);
        }


        /// <summary>
        /// Type {0} contains generic parameters
        /// </summary>
        internal static string TypeContainsGenericParameters
        {
            get
            {
                return "Type {0} contains generic parameters";
            }
        }


        internal static string FormatTypeContainsGenericParameters(object arg1)
        {
            return string.Format("Type {0} contains generic parameters", arg1);
        }


        /// <summary>
        /// Type {0} is a generic type definition
        /// </summary>
        internal static string TypeIsGeneric
        {
            get
            {
                return "Type {0} is a generic type definition";
            }
        }


        internal static string FormatTypeIsGeneric(object arg1)
        {
            return string.Format("Type {0} is a generic type definition", arg1);
        }


        /// <summary>
        /// Type '{0}' does not have a default constructor
        /// </summary>
        internal static string TypeMissingDefaultConstructor
        {
            get
            {
                return "Type '{0}' does not have a default constructor";
            }
        }


        internal static string FormatTypeMissingDefaultConstructor(object arg1)
        {
            return string.Format("Type '{0}' does not have a default constructor", arg1);
        }


        /// <summary>
        /// Element initializer method must be named 'Add'
        /// </summary>
        internal static string ElementInitializerMethodNotAdd
        {
            get
            {
                return "Element initializer method must be named 'Add'";
            }
        }



        /// <summary>
        /// Parameter '{0}' of element initializer method '{1}' must not be a pass by reference parameter
        /// </summary>
        internal static string ElementInitializerMethodNoRefOutParam
        {
            get
            {
                return "Parameter '{0}' of element initializer method '{1}' must not be a pass by reference parameter";
            }
        }


        internal static string FormatElementInitializerMethodNoRefOutParam(object arg1, object arg2)
        {
            return string.Format("Parameter '{0}' of element initializer method '{1}' must not be a pass by reference parameter", arg1, arg2);
        }


        /// <summary>
        /// Element initializer method must have at least 1 parameter
        /// </summary>
        internal static string ElementInitializerMethodWithZeroArgs
        {
            get
            {
                return "Element initializer method must have at least 1 parameter";
            }
        }



        /// <summary>
        /// Element initializer method must be an instance method
        /// </summary>
        internal static string ElementInitializerMethodStatic
        {
            get
            {
                return "Element initializer method must be an instance method";
            }
        }



        /// <summary>
        /// Type '{0}' is not IEnumerable
        /// </summary>
        internal static string TypeNotIEnumerable
        {
            get
            {
                return "Type '{0}' is not IEnumerable";
            }
        }


        internal static string FormatTypeNotIEnumerable(object arg1)
        {
            return string.Format("Type '{0}' is not IEnumerable", arg1);
        }


        /// <summary>
        /// Unhandled binary: {0}
        /// </summary>
        internal static string UnhandledBinary
        {
            get
            {
                return "Unhandled binary: {0}";
            }
        }


        internal static string FormatUnhandledBinary(object arg1)
        {
            return string.Format("Unhandled binary: {0}", arg1);
        }


        /// <summary>
        /// Unhandled binding
        /// </summary>
        internal static string UnhandledBinding
        {
            get
            {
                return "Unhandled binding ";
            }
        }



        /// <summary>
        /// Unhandled Binding Type: {0}
        /// </summary>
        internal static string UnhandledBindingType
        {
            get
            {
                return "Unhandled Binding Type: {0}";
            }
        }


        internal static string FormatUnhandledBindingType(object arg1)
        {
            return string.Format("Unhandled Binding Type: {0}", arg1);
        }


        /// <summary>
        /// Unhandled unary: {0}
        /// </summary>
        internal static string UnhandledUnary
        {
            get
            {
                return "Unhandled unary: {0}";
            }
        }


        internal static string FormatUnhandledUnary(object arg1)
        {
            return string.Format("Unhandled unary: {0}", arg1);
        }


        /// <summary>
        /// Unknown binding type
        /// </summary>
        internal static string UnknownBindingType
        {
            get
            {
                return "Unknown binding type";
            }
        }



        /// <summary>
        /// The user-defined operator method '{1}' for operator '{0}' must have identical parameter and return types.
        /// </summary>
        internal static string UserDefinedOpMustHaveConsistentTypes
        {
            get
            {
                return "The user-defined operator method '{1}' for operator '{0}' must have identical parameter and return types.";
            }
        }


        internal static string FormatUserDefinedOpMustHaveConsistentTypes(object arg1, object arg2)
        {
            return string.Format("The user-defined operator method '{1}' for operator '{0}' must have identical parameter and return types.", arg1, arg2);
        }


        /// <summary>
        /// The user-defined operator method '{1}' for operator '{0}' must return the same type as its parameter or a derived type.
        /// </summary>
        internal static string UserDefinedOpMustHaveValidReturnType
        {
            get
            {
                return "The user-defined operator method '{1}' for operator '{0}' must return the same type as its parameter or a derived type.";
            }
        }


        internal static string FormatUserDefinedOpMustHaveValidReturnType(object arg1, object arg2)
        {
            return string.Format("The user-defined operator method '{1}' for operator '{0}' must return the same type as its parameter or a derived type.", arg1, arg2);
        }


        /// <summary>
        /// The user-defined operator method '{1}' for operator '{0}' must have associated boolean True and False operators.
        /// </summary>
        internal static string LogicalOperatorMustHaveBooleanOperators
        {
            get
            {
                return "The user-defined operator method '{1}' for operator '{0}' must have associated boolean True and False operators.";
            }
        }


        internal static string FormatLogicalOperatorMustHaveBooleanOperators(object arg1, object arg2)
        {
            return string.Format("The user-defined operator method '{1}' for operator '{0}' must have associated boolean True and False operators.", arg1, arg2);
        }


        /// <summary>
        /// No method '{0}' on type '{1}' is compatible with the supplied arguments.
        /// </summary>
        internal static string MethodWithArgsDoesNotExistOnType
        {
            get
            {
                return "No method '{0}' on type '{1}' is compatible with the supplied arguments.";
            }
        }


        internal static string FormatMethodWithArgsDoesNotExistOnType(object arg1, object arg2)
        {
            return string.Format("No method '{0}' on type '{1}' is compatible with the supplied arguments.", arg1, arg2);
        }


        /// <summary>
        /// No generic method '{0}' on type '{1}' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic.
        /// </summary>
        internal static string GenericMethodWithArgsDoesNotExistOnType
        {
            get
            {
                return "No generic method '{0}' on type '{1}' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. ";
            }
        }


        internal static string FormatGenericMethodWithArgsDoesNotExistOnType(object arg1, object arg2)
        {
            return string.Format("No generic method '{0}' on type '{1}' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. ", arg1, arg2);
        }


        /// <summary>
        /// More than one method '{0}' on type '{1}' is compatible with the supplied arguments.
        /// </summary>
        internal static string MethodWithMoreThanOneMatch
        {
            get
            {
                return "More than one method '{0}' on type '{1}' is compatible with the supplied arguments.";
            }
        }


        internal static string FormatMethodWithMoreThanOneMatch(object arg1, object arg2)
        {
            return string.Format("More than one method '{0}' on type '{1}' is compatible with the supplied arguments.", arg1, arg2);
        }


        /// <summary>
        /// More than one property '{0}' on type '{1}' is compatible with the supplied arguments.
        /// </summary>
        internal static string PropertyWithMoreThanOneMatch
        {
            get
            {
                return "More than one property '{0}' on type '{1}' is compatible with the supplied arguments.";
            }
        }


        internal static string FormatPropertyWithMoreThanOneMatch(object arg1, object arg2)
        {
            return string.Format("More than one property '{0}' on type '{1}' is compatible with the supplied arguments.", arg1, arg2);
        }


        /// <summary>
        /// An incorrect number of type arguments were specified for the declaration of a Func type.
        /// </summary>
        internal static string IncorrectNumberOfTypeArgsForFunc
        {
            get
            {
                return "An incorrect number of type arguments were specified for the declaration of a Func type.";
            }
        }



        /// <summary>
        /// An incorrect number of type arguments were specified for the declaration of an Action type.
        /// </summary>
        internal static string IncorrectNumberOfTypeArgsForAction
        {
            get
            {
                return "An incorrect number of type arguments were specified for the declaration of an Action type.";
            }
        }



        /// <summary>
        /// Argument type cannot be System.Void.
        /// </summary>
        internal static string ArgumentCannotBeOfTypeVoid
        {
            get
            {
                return "Argument type cannot be System.Void.";
            }
        }



        /// <summary>
        /// Cannot redefine label '{0}' in an inner block.
        /// </summary>
        internal static string LabelTargetAlreadyDefined
        {
            get
            {
                return "Cannot redefine label '{0}' in an inner block.";
            }
        }


        internal static string FormatLabelTargetAlreadyDefined(object arg1)
        {
            return string.Format("Cannot redefine label '{0}' in an inner block.", arg1);
        }


        /// <summary>
        /// Cannot jump to undefined label '{0}'.
        /// </summary>
        internal static string LabelTargetUndefined
        {
            get
            {
                return "Cannot jump to undefined label '{0}'.";
            }
        }


        internal static string FormatLabelTargetUndefined(object arg1)
        {
            return string.Format("Cannot jump to undefined label '{0}'.", arg1);
        }


        /// <summary>
        /// Control cannot leave a finally block.
        /// </summary>
        internal static string ControlCannotLeaveFinally
        {
            get
            {
                return "Control cannot leave a finally block.";
            }
        }



        /// <summary>
        /// Control cannot leave a filter test.
        /// </summary>
        internal static string ControlCannotLeaveFilterTest
        {
            get
            {
                return "Control cannot leave a filter test.";
            }
        }



        /// <summary>
        /// Cannot jump to ambiguous label '{0}'.
        /// </summary>
        internal static string AmbiguousJump
        {
            get
            {
                return "Cannot jump to ambiguous label '{0}'.";
            }
        }


        internal static string FormatAmbiguousJump(object arg1)
        {
            return string.Format("Cannot jump to ambiguous label '{0}'.", arg1);
        }


        /// <summary>
        /// Control cannot enter a try block.
        /// </summary>
        internal static string ControlCannotEnterTry
        {
            get
            {
                return "Control cannot enter a try block.";
            }
        }



        /// <summary>
        /// Control cannot enter an expression--only statements can be jumped into.
        /// </summary>
        internal static string ControlCannotEnterExpression
        {
            get
            {
                return "Control cannot enter an expression--only statements can be jumped into.";
            }
        }



        /// <summary>
        /// Cannot jump to non-local label '{0}' with a value. Only jumps to labels defined in outer blocks can pass values.
        /// </summary>
        internal static string NonLocalJumpWithValue
        {
            get
            {
                return "Cannot jump to non-local label '{0}' with a value. Only jumps to labels defined in outer blocks can pass values.";
            }
        }


        internal static string FormatNonLocalJumpWithValue(object arg1)
        {
            return string.Format("Cannot jump to non-local label '{0}' with a value. Only jumps to labels defined in outer blocks can pass values.", arg1);
        }


        /// <summary>
        /// CompileToMethod cannot compile constant '{0}' because it is a non-trivial value, such as a live object. Instead, create an expression tree that can construct this value.
        /// </summary>
        internal static string CannotCompileConstant
        {
            get
            {
                return "CompileToMethod cannot compile constant '{0}' because it is a non-trivial value, such as a live object. Instead, create an expression tree that can construct this value.";
            }
        }


        internal static string FormatCannotCompileConstant(object arg1)
        {
            return string.Format("CompileToMethod cannot compile constant '{0}' because it is a non-trivial value, such as a live object. Instead, create an expression tree that can construct this value.", arg1);
        }


        /// <summary>
        /// Dynamic expressions are not supported by CompileToMethod. Instead, create an expression tree that uses System.Runtime.CompilerServices.CallSite.
        /// </summary>
        internal static string CannotCompileDynamic
        {
            get
            {
                return "Dynamic expressions are not supported by CompileToMethod. Instead, create an expression tree that uses System.Runtime.CompilerServices.CallSite.";
            }
        }



        /// <summary>
        /// Invalid lvalue for assignment: {0}.
        /// </summary>
        internal static string InvalidLvalue
        {
            get
            {
                return "Invalid lvalue for assignment: {0}.";
            }
        }


        internal static string FormatInvalidLvalue(object arg1)
        {
            return string.Format("Invalid lvalue for assignment: {0}.", arg1);
        }


        /// <summary>
        /// variable '{0}' of type '{1}' referenced from scope '{2}', but it is not defined
        /// </summary>
        internal static string UndefinedVariable
        {
            get
            {
                return "variable '{0}' of type '{1}' referenced from scope '{2}', but it is not defined";
            }
        }


        internal static string FormatUndefinedVariable(object arg1, object arg2, object arg3)
        {
            return string.Format("variable '{0}' of type '{1}' referenced from scope '{2}', but it is not defined", arg1, arg2, arg3);
        }


        /// <summary>
        /// Cannot close over byref parameter '{0}' referenced in lambda '{1}'
        /// </summary>
        internal static string CannotCloseOverByRef
        {
            get
            {
                return "Cannot close over byref parameter '{0}' referenced in lambda '{1}'";
            }
        }


        internal static string FormatCannotCloseOverByRef(object arg1, object arg2)
        {
            return string.Format("Cannot close over byref parameter '{0}' referenced in lambda '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Unexpected VarArgs call to method '{0}'
        /// </summary>
        internal static string UnexpectedVarArgsCall
        {
            get
            {
                return "Unexpected VarArgs call to method '{0}'";
            }
        }


        internal static string FormatUnexpectedVarArgsCall(object arg1)
        {
            return string.Format("Unexpected VarArgs call to method '{0}'", arg1);
        }


        /// <summary>
        /// Rethrow statement is valid only inside a Catch block.
        /// </summary>
        internal static string RethrowRequiresCatch
        {
            get
            {
                return "Rethrow statement is valid only inside a Catch block.";
            }
        }



        /// <summary>
        /// Try expression is not allowed inside a filter body.
        /// </summary>
        internal static string TryNotAllowedInFilter
        {
            get
            {
                return "Try expression is not allowed inside a filter body.";
            }
        }



        /// <summary>
        /// When called from '{0}', rewriting a node of type '{1}' must return a non-null value of the same type. Alternatively, override '{2}' and change it to not visit children of this type.
        /// </summary>
        internal static string MustRewriteToSameNode
        {
            get
            {
                return "When called from '{0}', rewriting a node of type '{1}' must return a non-null value of the same type. Alternatively, override '{2}' and change it to not visit children of this type.";
            }
        }


        internal static string FormatMustRewriteToSameNode(object arg1, object arg2, object arg3)
        {
            return string.Format("When called from '{0}', rewriting a node of type '{1}' must return a non-null value of the same type. Alternatively, override '{2}' and change it to not visit children of this type.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Rewriting child expression from type '{0}' to type '{1}' is not allowed, because it would change the meaning of the operation. If this is intentional, override '{2}' and change it to allow this rewrite.
        /// </summary>
        internal static string MustRewriteChildToSameType
        {
            get
            {
                return "Rewriting child expression from type '{0}' to type '{1}' is not allowed, because it would change the meaning of the operation. If this is intentional, override '{2}' and change it to allow this rewrite.";
            }
        }


        internal static string FormatMustRewriteChildToSameType(object arg1, object arg2, object arg3)
        {
            return string.Format("Rewriting child expression from type '{0}' to type '{1}' is not allowed, because it would change the meaning of the operation. If this is intentional, override '{2}' and change it to allow this rewrite.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Rewritten expression calls operator method '{0}', but the original node had no operator method. If this is intentional, override '{1}' and change it to allow this rewrite.
        /// </summary>
        internal static string MustRewriteWithoutMethod
        {
            get
            {
                return "Rewritten expression calls operator method '{0}', but the original node had no operator method. If this is intentional, override '{1}' and change it to allow this rewrite.";
            }
        }


        internal static string FormatMustRewriteWithoutMethod(object arg1, object arg2)
        {
            return string.Format("Rewritten expression calls operator method '{0}', but the original node had no operator method. If this is intentional, override '{1}' and change it to allow this rewrite.", arg1, arg2);
        }


        /// <summary>
        /// The value null is not of type '{0}' and cannot be used in this collection.
        /// </summary>
        internal static string InvalidNullValue
        {
            get
            {
                return "The value null is not of type '{0}' and cannot be used in this collection.";
            }
        }


        internal static string FormatInvalidNullValue(object arg1)
        {
            return string.Format("The value null is not of type '{0}' and cannot be used in this collection.", arg1);
        }


        /// <summary>
        /// The value '{0}' is not of type '{1}' and cannot be used in this collection.
        /// </summary>
        internal static string InvalidObjectType
        {
            get
            {
                return "The value '{0}' is not of type '{1}' and cannot be used in this collection.";
            }
        }


        internal static string FormatInvalidObjectType(object arg1, object arg2)
        {
            return string.Format("The value '{0}' is not of type '{1}' and cannot be used in this collection.", arg1, arg2);
        }


        /// <summary>
        /// TryExpression is not supported as an argument to method '{0}' because it has an argument with by-ref type. Construct the tree so the TryExpression is not nested inside of this expression.
        /// </summary>
        internal static string TryNotSupportedForMethodsWithRefArgs
        {
            get
            {
                return "TryExpression is not supported as an argument to method '{0}' because it has an argument with by-ref type. Construct the tree so the TryExpression is not nested inside of this expression.";
            }
        }


        internal static string FormatTryNotSupportedForMethodsWithRefArgs(object arg1)
        {
            return string.Format("TryExpression is not supported as an argument to method '{0}' because it has an argument with by-ref type. Construct the tree so the TryExpression is not nested inside of this expression.", arg1);
        }


        /// <summary>
        /// TryExpression is not supported as a child expression when accessing a member on type '{0}' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.
        /// </summary>
        internal static string TryNotSupportedForValueTypeInstances
        {
            get
            {
                return "TryExpression is not supported as a child expression when accessing a member on type '{0}' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.";
            }
        }


        internal static string FormatTryNotSupportedForValueTypeInstances(object arg1)
        {
            return string.Format("TryExpression is not supported as a child expression when accessing a member on type '{0}' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.", arg1);
        }


        /// <summary>
        /// Enumeration has either not started or has already finished.
        /// </summary>
        internal static string EnumerationIsDone
        {
            get
            {
                return "Enumeration has either not started or has already finished.";
            }
        }



        /// <summary>
        /// Test value of type '{0}' cannot be used for the comparison method parameter of type '{1}'
        /// </summary>
        internal static string TestValueTypeDoesNotMatchComparisonMethodParameter
        {
            get
            {
                return "Test value of type '{0}' cannot be used for the comparison method parameter of type '{1}'";
            }
        }


        internal static string FormatTestValueTypeDoesNotMatchComparisonMethodParameter(object arg1, object arg2)
        {
            return string.Format("Test value of type '{0}' cannot be used for the comparison method parameter of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Switch value of type '{0}' cannot be used for the comparison method parameter of type '{1}'
        /// </summary>
        internal static string SwitchValueTypeDoesNotMatchComparisonMethodParameter
        {
            get
            {
                return "Switch value of type '{0}' cannot be used for the comparison method parameter of type '{1}'";
            }
        }


        internal static string FormatSwitchValueTypeDoesNotMatchComparisonMethodParameter(object arg1, object arg2)
        {
            return string.Format("Switch value of type '{0}' cannot be used for the comparison method parameter of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// DebugInfoGenerator created by CreatePdbGenerator can only be used with LambdaExpression.CompileToMethod.
        /// </summary>
        internal static string PdbGeneratorNeedsExpressionCompiler
        {
            get
            {
                return "DebugInfoGenerator created by CreatePdbGenerator can only be used with LambdaExpression.CompileToMethod.";
            }
        }



        /// <summary>
        /// Invalid argument value
        /// </summary>
        internal static string InvalidArgumentValue_ParamName
        {
            get
            {
                return "Invalid argument value";
            }
        }



        /// <summary>
        /// Non-empty collection required
        /// </summary>
        internal static string NonEmptyCollectionRequired
        {
            get
            {
                return "Non-empty collection required";
            }
        }



        /// <summary>
        /// Collection was modified; enumeration operation may not execute.
        /// </summary>
        internal static string CollectionModifiedWhileEnumerating
        {
            get
            {
                return "Collection was modified; enumeration operation may not execute.";
            }
        }



        /// <summary>
        /// Expression must be readable
        /// </summary>
        internal static string ExpressionMustBeReadable
        {
            get
            {
                return "Expression must be readable";
            }
        }



        /// <summary>
        /// Expression of type '{0}' cannot be used for parameter of type '{1}' of method '{2}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchMethodParameter
        {
            get
            {
                return "Expression of type '{0}' cannot be used for parameter of type '{1}' of method '{2}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchMethodParameter(object arg1, object arg2, object arg3)
        {
            return string.Format("Expression of type '{0}' cannot be used for parameter of type '{1}' of method '{2}'", arg1, arg2, arg3);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be used for parameter of type '{1}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchParameter
        {
            get
            {
                return "Expression of type '{0}' cannot be used for parameter of type '{1}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchParameter(object arg1, object arg2)
        {
            return string.Format("Expression of type '{0}' cannot be used for parameter of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Expression of type '{0}' cannot be used for constructor parameter of type '{1}'
        /// </summary>
        internal static string ExpressionTypeDoesNotMatchConstructorParameter
        {
            get
            {
                return "Expression of type '{0}' cannot be used for constructor parameter of type '{1}'";
            }
        }


        internal static string FormatExpressionTypeDoesNotMatchConstructorParameter(object arg1, object arg2)
        {
            return string.Format("Expression of type '{0}' cannot be used for constructor parameter of type '{1}'", arg1, arg2);
        }


        /// <summary>
        /// Incorrect number of arguments supplied for call to method '{0}'
        /// </summary>
        internal static string IncorrectNumberOfMethodCallArguments
        {
            get
            {
                return "Incorrect number of arguments supplied for call to method '{0}'";
            }
        }


        internal static string FormatIncorrectNumberOfMethodCallArguments(object arg1)
        {
            return string.Format("Incorrect number of arguments supplied for call to method '{0}'", arg1);
        }


        /// <summary>
        /// Incorrect number of arguments supplied for lambda invocation
        /// </summary>
        internal static string IncorrectNumberOfLambdaArguments
        {
            get
            {
                return "Incorrect number of arguments supplied for lambda invocation";
            }
        }



        /// <summary>
        /// Incorrect number of arguments for constructor
        /// </summary>
        internal static string IncorrectNumberOfConstructorArguments
        {
            get
            {
                return "Incorrect number of arguments for constructor";
            }
        }



        /// <summary>
        /// The constructor should not be static
        /// </summary>
        internal static string NonStaticConstructorRequired
        {
            get
            {
                return "The constructor should not be static";
            }
        }



        /// <summary>
        /// Can't compile a NewExpression with a constructor declared on an abstract class
        /// </summary>
        internal static string NonAbstractConstructorRequired
        {
            get
            {
                return "Can't compile a NewExpression with a constructor declared on an abstract class";
            }
        }



        /// <summary>
        /// First argument of delegate must be CallSite
        /// </summary>
        internal static string FirstArgumentMustBeCallSite
        {
            get
            {
                return "First argument of delegate must be CallSite";
            }
        }



        /// <summary>
        /// No or Invalid rule produced
        /// </summary>
        internal static string NoOrInvalidRuleProduced
        {
            get
            {
                return "No or Invalid rule produced";
            }
        }



        /// <summary>
        /// Type must be derived from System.Delegate
        /// </summary>
        internal static string TypeMustBeDerivedFromSystemDelegate
        {
            get
            {
                return "Type must be derived from System.Delegate";
            }
        }



        /// <summary>
        /// Type parameter is {0}. Expected a delegate.
        /// </summary>
        internal static string TypeParameterIsNotDelegate
        {
            get
            {
                return "Type parameter is {0}. Expected a delegate.";
            }
        }


        internal static string FormatTypeParameterIsNotDelegate(object arg1)
        {
            return string.Format("Type parameter is {0}. Expected a delegate.", arg1);
        }


        /// <summary>
        /// Argument type cannot be void
        /// </summary>
        internal static string ArgumentTypeCannotBeVoid
        {
            get
            {
                return "Argument type cannot be void";
            }
        }



        /// <summary>
        /// Argument count must be greater than number of named arguments.
        /// </summary>
        internal static string ArgCntMustBeGreaterThanNameCnt
        {
            get
            {
                return "Argument count must be greater than number of named arguments.";
            }
        }



        /// <summary>
        /// The result type '{0}' of the binder '{1}' is not compatible with the result type '{2}' expected by the call site.
        /// </summary>
        internal static string BinderNotCompatibleWithCallSite
        {
            get
            {
                return "The result type '{0}' of the binder '{1}' is not compatible with the result type '{2}' expected by the call site.";
            }
        }


        internal static string FormatBinderNotCompatibleWithCallSite(object arg1, object arg2, object arg3)
        {
            return string.Format("The result type '{0}' of the binder '{1}' is not compatible with the result type '{2}' expected by the call site.", arg1, arg2, arg3);
        }


        /// <summary>
        /// Bind cannot return null.
        /// </summary>
        internal static string BindingCannotBeNull
        {
            get
            {
                return "Bind cannot return null.";
            }
        }



        /// <summary>
        /// The result type '{0}' of the dynamic binding produced by binder '{1}' is not compatible with the result type '{2}' expected by the call site.
        /// </summary>
        internal static string DynamicBinderResultNotAssignable
        {
            get
            {
                return "The result type '{0}' of the dynamic binding produced by binder '{1}' is not compatible with the result type '{2}' expected by the call site.";
            }
        }


        internal static string FormatDynamicBinderResultNotAssignable(object arg1, object arg2, object arg3)
        {
            return string.Format("The result type '{0}' of the dynamic binding produced by binder '{1}' is not compatible with the result type '{2}' expected by the call site.", arg1, arg2, arg3);
        }


        /// <summary>
        /// The result of the dynamic binding produced by the object with type '{0}' for the binder '{1}' needs at least one restriction.
        /// </summary>
        internal static string DynamicBindingNeedsRestrictions
        {
            get
            {
                return "The result of the dynamic binding produced by the object with type '{0}' for the binder '{1}' needs at least one restriction.";
            }
        }


        internal static string FormatDynamicBindingNeedsRestrictions(object arg1, object arg2)
        {
            return string.Format("The result of the dynamic binding produced by the object with type '{0}' for the binder '{1}' needs at least one restriction.", arg1, arg2);
        }


        /// <summary>
        /// The result type '{0}' of the dynamic binding produced by the object with type '{1}' for the binder '{2}' is not compatible with the result type '{3}' expected by the call site.
        /// </summary>
        internal static string DynamicObjectResultNotAssignable
        {
            get
            {
                return "The result type '{0}' of the dynamic binding produced by the object with type '{1}' for the binder '{2}' is not compatible with the result type '{3}' expected by the call site.";
            }
        }


        internal static string FormatDynamicObjectResultNotAssignable(object arg1, object arg2, object arg3, object arg4)
        {
            return string.Format("The result type '{0}' of the dynamic binding produced by the object with type '{1}' for the binder '{2}' is not compatible with the result type '{3}' expected by the call site.", arg1, arg2, arg3, arg4);
        }


        /// <summary>
        /// An IDynamicMetaObjectProvider {0} created an invalid DynamicMetaObject instance.
        /// </summary>
        internal static string InvalidMetaObjectCreated
        {
            get
            {
                return "An IDynamicMetaObjectProvider {0} created an invalid DynamicMetaObject instance.";
            }
        }


        internal static string FormatInvalidMetaObjectCreated(object arg1)
        {
            return string.Format("An IDynamicMetaObjectProvider {0} created an invalid DynamicMetaObject instance.", arg1);
        }


        /// <summary>
        /// More than one key matching '{0}' was found in the ExpandoObject.
        /// </summary>
        internal static string AmbiguousMatchInExpandoObject
        {
            get
            {
                return "More than one key matching '{0}' was found in the ExpandoObject.";
            }
        }


        internal static string FormatAmbiguousMatchInExpandoObject(object arg1)
        {
            return string.Format("More than one key matching '{0}' was found in the ExpandoObject.", arg1);
        }


        /// <summary>
        /// Collection is read-only.
        /// </summary>
        internal static string CollectionReadOnly
        {
            get
            {
                return "Collection is read-only.";
            }
        }



        /// <summary>
        /// The specified key '{0}' does not exist in the ExpandoObject.
        /// </summary>
        internal static string KeyDoesNotExistInExpando
        {
            get
            {
                return "The specified key '{0}' does not exist in the ExpandoObject.";
            }
        }


        internal static string FormatKeyDoesNotExistInExpando(object arg1)
        {
            return string.Format("The specified key '{0}' does not exist in the ExpandoObject.", arg1);
        }


        /// <summary>
        /// An element with the same key '{0}' already exists in the ExpandoObject.
        /// </summary>
        internal static string SameKeyExistsInExpando
        {
            get
            {
                return "An element with the same key '{0}' already exists in the ExpandoObject.";
            }
        }


        internal static string FormatSameKeyExistsInExpando(object arg1)
        {
            return string.Format("An element with the same key '{0}' already exists in the ExpandoObject.", arg1);
        }


        /// <summary>
        /// The given key '{0}' was not present in the dictionary.
        /// </summary>
        internal static string Arg_KeyNotFoundWithKey
        {
            get
            {
                return "The given key '{0}' was not present in the dictionary.";
            }
        }


        internal static string FormatArg_KeyNotFoundWithKey(object arg1)
        {
            return string.Format("The given key '{0}' was not present in the dictionary.", arg1);
        }


        /// <summary>
        /// Nullable lifting on non-primitive type '{0}' is only supported in expression trees when dynamic code generation is available.
        /// </summary>
        internal static string LiftingInExpressionRequiresDynamicCode
        {
            get
            {
                return "Nullable lifting on non-primitive type '{0}' is only supported in expression trees when dynamic code generation is available.";
            }
        }


        internal static string FormatLiftingInExpressionRequiresDynamicCode(object arg1)
        {
            return string.Format("Nullable lifting on non-primitive type '{0}' is only supported in expression trees when dynamic code generation is available.", arg1);
        }
    }
}
